"use client";

import {useEffect,useState} from "react";
import d from "./dashboard.module.css";
import {createTierTestClient as createClient} from "../../lib/supabase/client";

type League={id:number;name:string;region:string;coverage:string};
type Tab="overview"|"leagues"|"team"|"reporting"|"billing";
type PlanStatus={active_officials:number;capacity:number|null};
type TeamAccess={id:string;user_id?:string;email:string;role:string;viewer_permissions:string[];status:string};
type TeamData={members:TeamAccess[];invitations:TeamAccess[]};

const roleLabels:Record<string,string>={owner:"Organization owner",admin:"Organization administrator",assignor:"Assignor",billing:"Billing manager",viewer:"Read-only viewer"};
const viewerSections=[
 ["overview","Overview dashboard"],["leagues","Leagues and coverage"],["games","Games and schedules"],
 ["assignments","Assignments"],["officials","Officials directory"],["reporting","Reporting"],
 ["analytics","Analytics"],["payroll","Payroll summaries"],["billing","Billing information"],
 ["training_documents","Training and documents"]
] as const;
const editableRoles=["assignor","admin","billing","viewer"] as const;

function PermissionPicker({selected,onChange}:{selected:string[];onChange:(permissions:string[])=>void}){
 return <fieldset className={d.permissionPicker}><legend>Viewer can see</legend><div>{viewerSections.map(([code,label])=><label key={code}><input type="checkbox" checked={selected.includes(code)} onChange={event=>onChange(event.target.checked?[...selected,code]:selected.filter(item=>item!==code))}/><span>{label}</span></label>)}</div><small>Viewer access is always read-only.</small></fieldset>
}

function AccessEditor({item,busy,onSave,onRemove}:{item:TeamAccess;busy:boolean;onSave:(role:string,permissions:string[])=>void;onRemove:()=>void}){
 const [editRole,setEditRole]=useState(item.role);
 const [permissions,setPermissions]=useState(item.viewer_permissions||[]);
 useEffect(()=>{setEditRole(item.role);setPermissions(item.viewer_permissions||[])},[item]);
 if(item.role==="owner")return <div className={d.ownerProtection}><b>Protected</b><small>The organization owner cannot be changed or removed.</small></div>;
 return <div className={d.accessEditor}><label>Role<select value={editRole} onChange={event=>setEditRole(event.target.value)}>{editableRoles.map(code=><option value={code} key={code}>{roleLabels[code]}</option>)}</select></label>{editRole==="viewer"&&<PermissionPicker selected={permissions} onChange={setPermissions}/>}<div className={d.accessActions}><button disabled={busy||editRole==="viewer"&&permissions.length===0} onClick={()=>onSave(editRole,permissions)}>{busy?"Saving…":"Save changes"}</button><button className={d.dangerButton} disabled={busy} onClick={onRemove}>{item.status==="pending"?"Revoke invitation":"Remove access"}</button></div></div>
}

export default function TestWorkspaceDashboard({organizationId,organization,sport,officials,planName,includedOfficials,estimate,textingEnabled,leagues,accessRole,viewerPermissions,onEdit}:{organizationId:string;organization:string;sport:string;officials:number;planName:string;includedOfficials:number|null;estimate:string;textingEnabled:boolean;leagues:League[];accessRole:string;viewerPermissions:string[];onEdit:()=>void}){
 const [tab,setTab]=useState<Tab>("overview");
 const [email,setEmail]=useState("");
 const [role,setRole]=useState("assignor");
 const [inviteViewerPermissions,setInviteViewerPermissions]=useState<string[]>(["overview"]);
 const [team,setTeam]=useState<TeamData>({members:[],invitations:[]});
 const [inviteMessage,setInviteMessage]=useState("");
 const [busyId,setBusyId]=useState("");
 const [planStatus,setPlanStatus]=useState<PlanStatus|null>(null);
 const managesOrganization=accessRole==="owner"||accessRole==="admin";
 const canView=(section:string)=>accessRole!=="viewer"||viewerPermissions.includes(section);
 const availableTabs:Tab[]=[canView("overview")&&"overview",canView("leagues")&&"leagues",managesOrganization&&"team",(canView("reporting")||canView("analytics")||canView("payroll"))&&"reporting",canView("billing")&&"billing"].filter(Boolean) as Tab[];
 const availableTabKey=availableTabs.join("|");
 const hasVisibleTab=availableTabs.includes(tab);
 const loadTeam=async()=>{if(!organizationId)return;const {data,error}=await createClient().rpc("get_organization_team",{p_organization_id:organizationId});if(error){setInviteMessage(error.message);return}setTeam((data||{members:[],invitations:[]}) as TeamData)};
 const invite=async()=>{if(!email.includes("@")||!organizationId)return;setInviteMessage("");setBusyId("invite");const supabase=createClient();const {error}=await supabase.functions.invoke("send-organization-invitation",{body:{organizationId,email,role,viewerPermissions:role==="viewer"?inviteViewerPermissions:[]}});if(error){let message=error.message;try{const details=await error.context?.json();if(details?.error)message=details.error}catch{}setInviteMessage(message);setBusyId("");return}await loadTeam();setEmail("");setRole("assignor");setInviteViewerPermissions(["overview"]);setBusyId("");setInviteMessage("Invitation email sent. The teammate can use the link to join this workspace.")};
 const saveAccess=async(item:TeamAccess,newRole:string,permissions:string[])=>{setBusyId(item.id);setInviteMessage("");const supabase=createClient();const args={p_role:newRole,p_viewer_permissions:newRole==="viewer"?permissions:[]};const {error}=item.status==="pending"?await supabase.rpc("update_organization_invitation",{p_invitation_id:item.id,...args}):await supabase.rpc("update_organization_member_access",{p_organization_id:organizationId,p_user_id:item.user_id,p_current_role:item.role,p_new_role:newRole,p_viewer_permissions:args.p_viewer_permissions});if(error)setInviteMessage(error.message);else{await loadTeam();setInviteMessage("Team access updated.")}setBusyId("")};
 const removeAccess=async(item:TeamAccess)=>{setBusyId(item.id);setInviteMessage("");const supabase=createClient();const {error}=item.status==="pending"?await supabase.rpc("revoke_organization_invitation",{p_invitation_id:item.id}):await supabase.rpc("remove_organization_member",{p_organization_id:organizationId,p_user_id:item.user_id,p_role:item.role});if(error)setInviteMessage(error.message);else{await loadTeam();setInviteMessage(item.status==="pending"?"Invitation revoked.":"Team access removed.")}setBusyId("")};
 useEffect(()=>{if(!organizationId)return;const supabase=createClient();void supabase.rpc("get_organization_plan_status",{p_organization_id:organizationId}).then(({data})=>setPlanStatus(data as PlanStatus));if(managesOrganization)void supabase.rpc("get_organization_team",{p_organization_id:organizationId}).then(({data,error})=>{if(error){setInviteMessage(error.message);return}setTeam((data||{members:[],invitations:[]}) as TeamData)})},[organizationId,managesOrganization]);
 useEffect(()=>{if(!availableTabs.includes(tab)&&availableTabs[0])setTab(availableTabs[0])},[accessRole,viewerPermissions,tab,availableTabKey]);
 const title={overview:"Overview",leagues:"Leagues & coverage",team:"Team & roles",reporting:"Reporting & analytics",billing:"Plan & billing"}[tab];
 return <div className={d.workspaceFrame}><section className={d.shell} id="organization-setup">
  <aside><div className={d.orgMark}>{organization.slice(0,2).toUpperCase()}</div><div className={d.orgName}><b>{organization}</b><span>{sport} · {roleLabels[accessRole]||accessRole}</span></div><nav>{canView("overview")&&<button className={tab==="overview"?d.active:""} onClick={()=>setTab("overview")}>⌂ Overview</button>}{canView("leagues")&&<button className={tab==="leagues"?d.active:""} onClick={()=>setTab("leagues")}>▦ Leagues & coverage</button>}{managesOrganization&&<button className={tab==="team"?d.active:""} onClick={()=>setTab("team")}>♟ Team & roles</button>}{(canView("reporting")||canView("analytics")||canView("payroll"))&&<button className={tab==="reporting"?d.active:""} onClick={()=>setTab("reporting")}>▥ Reporting & analytics</button>}{canView("billing")&&<button className={tab==="billing"?d.active:""} onClick={()=>setTab("billing")}>▤ Plan & billing</button>}</nav><div className={d.testBadge}><b>Isolated test mode</b><p>{accessRole==="viewer"?"Read-only access":"No charges or production data."}</p></div></aside>
  <div className={d.content}><header><div><p>Organization workspace</p><h2>{title}</h2></div>{managesOrganization&&<button onClick={onEdit}>Edit setup</button>}</header>
   {!hasVisibleTab&&<article className={d.panel}><span className={d.kicker}>Read-only access</span><h3>No dashboard section selected</h3><p>Your organization administrator has not enabled one of the available dashboard sections for this Viewer account.</p></article>}
   {hasVisibleTab&&<>
   {tab==="overview"&&<><div className={d.metrics}><article><span>Active officials</span><strong>{planStatus?.active_officials??0}</strong><small>Rolling previous six months</small></article><article><span>League coverage</span><strong>{leagues.length}</strong><small>Configured leagues</small></article><article><span>Current plan</span><strong>{planName}</strong><small>{estimate} estimated annually</small></article></div><div className={d.columns}><article className={d.panel}><div className={d.panelHead}><div><span>Official capacity</span><h3>{planStatus?.active_officials??0} of {planStatus?.capacity??includedOfficials??"custom"}</h3></div><b>{includedOfficials===null?"Custom":"Live usage"}</b></div>{includedOfficials!==null&&<><div className={d.progress}><i style={{width:`${Math.min(100,Math.round(((planStatus?.active_officials??0)/(planStatus?.capacity||includedOfficials))*100))}%`}}/></div><p>{Math.max(0,(planStatus?.capacity||includedOfficials)-(planStatus?.active_officials??0))} active official spaces remaining.</p></>}<div className={d.rule}><b>Who counts as active?</b><p>An official who logged in and accepted or declined a game within the previous six months.</p></div></article><article className={d.panel}><div className={d.panelHead}><div><span>Setup progress</span><h3>Ready for team testing</h3></div><b>75%</b></div><ul className={d.checklist}><li className={d.done}>Organization configured</li><li className={d.done}>League coverage added</li><li>Invite assignors and administrators</li><li className={d.done}>Secure test authentication</li></ul><button onClick={()=>setTab("team")}>Invite your team →</button></article></div></>}
   {tab==="leagues"&&<article className={d.panel}><div className={d.tableHead}><div><h3>Configured league coverage</h3><p>Organizations may share a league while maintaining separate assignor regions.</p></div>{managesOrganization&&<button onClick={onEdit}>+ Add league</button>}</div><div className={d.table}>{leagues.map(league=><div className={d.tableRow} key={league.id}><div className={d.leagueIcon}>L</div><div><b>{league.name}</b><span>{league.region||"Region not specified"}</span></div><div><span>Coverage</span><b>{league.coverage}</b></div><em>Draft</em></div>)}</div></article>}
   {tab==="team"&&<div className={d.teamLayout}><article className={d.panel}><span className={d.kicker}>Invite a team member</span><h3>Assign workspace access</h3><p>Choose a role. For read-only viewers, select only the sections they should see.</p><label>Email address<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="assignor@example.com" type="email"/></label><label>Workspace role<select value={role} onChange={e=>setRole(e.target.value)}>{editableRoles.map(code=><option value={code} key={code}>{roleLabels[code]}</option>)}</select></label>{role==="viewer"&&<PermissionPicker selected={inviteViewerPermissions} onChange={setInviteViewerPermissions}/>}<button disabled={busyId==="invite"||!email.includes("@")||!organizationId||role==="viewer"&&inviteViewerPermissions.length===0} onClick={()=>void invite()}>{busyId==="invite"?"Sending invitation…":"Send invitation"}</button>{inviteMessage&&<p className={d.teamMessage}>{inviteMessage}</p>}</article><article className={`${d.panel} ${d.teamPanel}`}><span className={d.kicker}>Team access</span><h3>{team.members.length} active · {team.invitations.length} pending</h3>{team.members.length===0&&team.invitations.length===0?<div className={d.empty}><b>No team access configured</b><p>Add a teammate and choose the access they need.</p></div>:<div className={d.accessList}>{[...team.members,...team.invitations].map(item=><section className={d.accessCard} key={item.id}><div className={d.accessIdentity}><span>{item.email[0].toUpperCase()}</span><div><b>{item.email}</b><small>{roleLabels[item.role]||item.role}</small></div><em>{item.status==="pending"?"Pending":"Active"}</em></div>{item.role==="viewer"&&item.viewer_permissions.length>0&&<p className={d.permissionSummary}>{item.viewer_permissions.map(code=>viewerSections.find(([value])=>value===code)?.[1]||code).join(" · ")}</p>}<AccessEditor item={item} busy={busyId===item.id} onSave={(newRole,permissions)=>void saveAccess(item,newRole,permissions)} onRemove={()=>void removeAccess(item)}/></section>)}</div>}</article></div>}
   {tab==="reporting"&&<div className={d.columns}><article className={d.panel}><span className={d.kicker}>Reporting access</span><h3>{planName==="Starter"?"Basic reporting":"Advanced reporting"}</h3><ul className={d.features}><li>Game and assignment totals <b>Enabled</b></li><li>Official activity report <b>Enabled</b></li><li>Payroll summaries <b>{planName==="Starter"?"Upgrade required":"Enabled"}</b></li><li>Custom report filters <b>{planName==="Starter"?"Upgrade required":"Enabled"}</b></li><li>Scheduled exports <b>{planName==="Starter"?"Upgrade required":"Enabled"}</b></li></ul></article><article className={d.panel}><span className={d.kicker}>Analytics access</span><h3>{planName==="Premier"||planName==="Enterprise"?"Advanced analytics enabled":"Plan upgrade required"}</h3><p>Advanced analytics includes assignment fill rates, response trends, official utilization and league-level comparisons.</p><div className={d.metrics}><article><span>Active officials</span><strong>{planStatus?.active_officials??0}</strong><small>Last six months</small></article><article><span>Capacity</span><strong>{planStatus?.capacity??"Custom"}</strong><small>Current plan</small></article></div></article></div>}
   {tab==="billing"&&<div className={d.columns}><article className={d.panel}><span className={d.kicker}>Subscription</span><div className={d.planTitle}><h3>{planName}</h3><b>Test draft</b></div><div className={d.billLine}><span>Active officials</span><b>{planStatus?.active_officials??0}</b></div><div className={d.billLine}><span>Plan capacity</span><b>{planStatus?.capacity??"Custom"}</b></div><div className={d.billLine}><span>Text messaging</span><b>{planName==="Enterprise"?"Included":textingEnabled?"$15 / month":"Not selected"}</b></div><div className={d.billLine}><span>Estimated annual total</span><b>{estimate}</b></div><div className={d.billLine}><span>Renewal date</span><b>Not scheduled</b></div><button disabled>Activate billing after approval</button></article><article className={d.panel}><span className={d.kicker}>Feature access</span><h3>Plan controls are ready</h3><ul className={d.features}><li>Game management <b>Enabled</b></li><li>Official assignments <b>Enabled</b></li><li>Text messaging <b>{textingEnabled?"Enabled":"Optional add-on"}</b></li><li>Reporting <b>{planName==="Starter"?"Basic":"Advanced"}</b></li><li>Payroll <b>{planName==="Starter"?"Not included":"Enabled"}</b></li><li>Multi-sport <b>{planName==="Premier"||planName==="Enterprise"?"Enabled":"Not included"}</b></li></ul></article></div>}
   </>}
  </div>
 </section></div>
}
