"use client";

import {useEffect,useState} from "react";
import d from "./dashboard.module.css";
import {createTierTestClient as createClient} from "../../lib/supabase/client";

type League={id:number;name:string;region:string;coverage:string};
type Tab="overview"|"leagues"|"team"|"reporting"|"billing";
type PlanStatus={active_officials:number;capacity:number|null};
type TeamAccess={id:string;email:string;role:string;status:string};
type TeamData={members:TeamAccess[];invitations:TeamAccess[]};

const roleLabels:Record<string,string>={owner:"Organization owner",admin:"Organization administrator",assignor:"Assignor",billing:"Billing manager",viewer:"Read-only viewer"};

export default function TestWorkspaceDashboard({organizationId,organization,sport,officials,planName,includedOfficials,estimate,leagues,onEdit}:{organizationId:string;organization:string;sport:string;officials:number;planName:string;includedOfficials:number|null;estimate:string;leagues:League[];onEdit:()=>void}){
 const [tab,setTab]=useState<Tab>("overview");
 const [email,setEmail]=useState("");
 const [role,setRole]=useState("Assignor");
 const [team,setTeam]=useState<TeamData>({members:[],invitations:[]});
 const [inviteMessage,setInviteMessage]=useState("");
 const [planStatus,setPlanStatus]=useState<PlanStatus|null>(null);
 const loadTeam=async()=>{if(!organizationId)return;const {data,error}=await createClient().rpc("get_organization_team",{p_organization_id:organizationId});if(error){setInviteMessage(error.message);return}setTeam((data||{members:[],invitations:[]}) as TeamData)};
 const invite=async()=>{if(!email.includes("@")||!organizationId)return;setInviteMessage("");const roleCode:{[key:string]:string}={Assignor:"assignor","Organization administrator":"admin","Billing manager":"billing","Read-only viewer":"viewer"};const supabase=createClient();const {error}=await supabase.rpc("create_organization_invitation",{p_organization_id:organizationId,p_email:email,p_role:roleCode[role]});if(error){setInviteMessage(error.message);return}await supabase.rpc("accept_my_organization_invitations");await loadTeam();setEmail("");setInviteMessage("Team role saved in this organization.")};
 useEffect(()=>{if(!organizationId)return;const supabase=createClient();void supabase.rpc("get_organization_plan_status",{p_organization_id:organizationId}).then(({data})=>setPlanStatus(data as PlanStatus));void supabase.rpc("get_organization_team",{p_organization_id:organizationId}).then(({data,error})=>{if(error){setInviteMessage(error.message);return}setTeam((data||{members:[],invitations:[]}) as TeamData)})},[organizationId]);
 const title={overview:"Overview",leagues:"Leagues & coverage",team:"Team & roles",reporting:"Reporting & analytics",billing:"Plan & billing"}[tab];
 return <div className={d.workspaceFrame}><section className={d.shell} id="organization-setup">
  <aside><div className={d.orgMark}>{organization.slice(0,2).toUpperCase()}</div><div className={d.orgName}><b>{organization}</b><span>{sport} · Test workspace</span></div><nav><button className={tab==="overview"?d.active:""} onClick={()=>setTab("overview")}>⌂ Overview</button><button className={tab==="leagues"?d.active:""} onClick={()=>setTab("leagues")}>▦ Leagues & coverage</button><button className={tab==="team"?d.active:""} onClick={()=>setTab("team")}>♟ Team & roles</button><button className={tab==="reporting"?d.active:""} onClick={()=>setTab("reporting")}>▥ Reporting & analytics</button><button className={tab==="billing"?d.active:""} onClick={()=>setTab("billing")}>▤ Plan & billing</button></nav><div className={d.testBadge}><b>Isolated test mode</b><p>No charges or production data.</p></div></aside>
  <div className={d.content}><header><div><p>Organization workspace</p><h2>{title}</h2></div><button onClick={onEdit}>Edit setup</button></header>
   {tab==="overview"&&<><div className={d.metrics}><article><span>Active officials</span><strong>{planStatus?.active_officials??0}</strong><small>Rolling previous six months</small></article><article><span>League coverage</span><strong>{leagues.length}</strong><small>Configured leagues</small></article><article><span>Current plan</span><strong>{planName}</strong><small>{estimate} estimated annually</small></article></div><div className={d.columns}><article className={d.panel}><div className={d.panelHead}><div><span>Official capacity</span><h3>{planStatus?.active_officials??0} of {planStatus?.capacity??includedOfficials??"custom"}</h3></div><b>{includedOfficials===null?"Custom":"Live usage"}</b></div>{includedOfficials!==null&&<><div className={d.progress}><i style={{width:`${Math.min(100,Math.round(((planStatus?.active_officials??0)/(planStatus?.capacity||includedOfficials))*100))}%`}}/></div><p>{Math.max(0,(planStatus?.capacity||includedOfficials)-(planStatus?.active_officials??0))} active official spaces remaining.</p></>}<div className={d.rule}><b>Who counts as active?</b><p>An official who logged in and accepted or declined a game within the previous six months.</p></div></article><article className={d.panel}><div className={d.panelHead}><div><span>Setup progress</span><h3>Ready for team testing</h3></div><b>75%</b></div><ul className={d.checklist}><li className={d.done}>Organization configured</li><li className={d.done}>League coverage added</li><li>Invite assignors and administrators</li><li className={d.done}>Secure test authentication</li></ul><button onClick={()=>setTab("team")}>Invite your team →</button></article></div></>}
   {tab==="leagues"&&<article className={d.panel}><div className={d.tableHead}><div><h3>Configured league coverage</h3><p>Organizations may share a league while maintaining separate assignor regions.</p></div><button onClick={onEdit}>+ Add league</button></div><div className={d.table}>{leagues.map(league=><div className={d.tableRow} key={league.id}><div className={d.leagueIcon}>L</div><div><b>{league.name}</b><span>{league.region||"Region not specified"}</span></div><div><span>Coverage</span><b>{league.coverage}</b></div><em>Draft</em></div>)}</div></article>}
   {tab==="team"&&<div className={d.columns}><article className={d.panel}><span className={d.kicker}>Invite a team member</span><h3>Assign workspace access</h3><p>Each role is saved to this organization&apos;s isolated test workspace and restored when you return.</p><label>Email address<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="assignor@example.com" type="email"/></label><label>Workspace role<select value={role} onChange={e=>setRole(e.target.value)}><option>Assignor</option><option>Organization administrator</option><option>Billing manager</option><option>Read-only viewer</option></select></label><button disabled={!email.includes("@")||!organizationId} onClick={()=>void invite()}>Save team role</button>{inviteMessage&&<p>{inviteMessage}</p>}</article><article className={d.panel}><span className={d.kicker}>Team access</span><h3>{team.members.length} active · {team.invitations.length} pending</h3>{team.members.length===0&&team.invitations.length===0?<div className={d.empty}><b>No team access configured</b><p>Add a teammate and choose the access they need.</p></div>:<div className={d.invites}>{team.members.map(item=><div key={item.id}><span>{item.email[0].toUpperCase()}</span><div><b>{item.email}</b><small>{roleLabels[item.role]||item.role}</small></div><em>Active</em></div>)}{team.invitations.map(item=><div key={item.id}><span>{item.email[0].toUpperCase()}</span><div><b>{item.email}</b><small>{roleLabels[item.role]||item.role}</small></div><em>Pending</em></div>)}</div>}</article></div>}
   {tab==="reporting"&&<div className={d.columns}><article className={d.panel}><span className={d.kicker}>Reporting access</span><h3>{planName==="Starter"?"Basic reporting":"Advanced reporting"}</h3><ul className={d.features}><li>Game and assignment totals <b>Enabled</b></li><li>Official activity report <b>Enabled</b></li><li>Payroll summaries <b>{planName==="Starter"?"Upgrade required":"Enabled"}</b></li><li>Custom report filters <b>{planName==="Starter"?"Upgrade required":"Enabled"}</b></li><li>Scheduled exports <b>{planName==="Starter"?"Upgrade required":"Enabled"}</b></li></ul></article><article className={d.panel}><span className={d.kicker}>Analytics access</span><h3>{planName==="Premier"||planName==="Enterprise"?"Advanced analytics enabled":"Plan upgrade required"}</h3><p>Advanced analytics includes assignment fill rates, response trends, official utilization and league-level comparisons.</p><div className={d.metrics}><article><span>Active officials</span><strong>{planStatus?.active_officials??0}</strong><small>Last six months</small></article><article><span>Capacity</span><strong>{planStatus?.capacity??"Custom"}</strong><small>Current plan</small></article></div></article></div>}
   {tab==="billing"&&<div className={d.columns}><article className={d.panel}><span className={d.kicker}>Subscription</span><div className={d.planTitle}><h3>{planName}</h3><b>Test draft</b></div><div className={d.billLine}><span>Active officials</span><b>{planStatus?.active_officials??0}</b></div><div className={d.billLine}><span>Plan capacity</span><b>{planStatus?.capacity??"Custom"}</b></div><div className={d.billLine}><span>Estimated annual total</span><b>{estimate}</b></div><div className={d.billLine}><span>Renewal date</span><b>Not scheduled</b></div><button disabled>Activate billing after approval</button></article><article className={d.panel}><span className={d.kicker}>Feature access</span><h3>Plan controls are ready</h3><ul className={d.features}><li>Game management <b>Enabled</b></li><li>Official assignments <b>Enabled</b></li><li>Reporting <b>{planName==="Starter"?"Basic":"Advanced"}</b></li><li>Payroll <b>{planName==="Starter"?"Not included":"Enabled"}</b></li><li>Multi-sport <b>{planName==="Premier"||planName==="Enterprise"?"Enabled":"Not included"}</b></li></ul></article></div>}
  </div>
 </section></div>
}
