"use client";

import {useMemo,useState} from "react";
import {OFFICIAL_BLOCK_ANNUAL_PRICE_CENTS,OFFICIAL_BLOCK_SIZE,PLAN_CATALOG,PlanCode} from "../../lib/saas/planCatalog";
import styles from "./tier-test.module.css";

const money=(cents:number|null)=>cents===null?"Custom":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(cents/100);
const orderedPlans:PlanCode[]=["starter","pro","pro_founding","premier","enterprise"];
const descriptions:Record<PlanCode,string>={starter:"For small leagues and clubs",pro:"For growing assigning organizations",pro_founding:"Limited introductory Pro rate",premier:"For larger, multi-sport organizations",enterprise:"For state associations and complex programs"};
const features:Record<PlanCode,string[]>={starter:["Game management","Official assignments","Basic reporting","Email support"],pro:["Everything in Starter","Payroll processing","Advanced reporting","Custom rules and settings","Priority support"],pro_founding:["Everything in Pro","Founding member pricing","Rate locked during introductory term","Priority support"],premier:["Everything in Pro","Multi-sport support","Advanced analytics","Custom integrations","Priority support"],enterprise:["Everything in Premier","Custom development options","Dedicated account manager","Onboarding and training","Ongoing partnership support"]};

export default function TierTestExperience({databaseConnected}:{databaseConnected:boolean}){
 const [officials,setOfficials]=useState(75);
 const [selected,setSelected]=useState<PlanCode>("pro");
 const [setupOpen,setSetupOpen]=useState(false);
 const [organization,setOrganization]=useState("");
 const [sport,setSport]=useState("Soccer");
 const plan=PLAN_CATALOG[selected];
 const extraBlocks=plan.includedOfficials===null?0:Math.max(0,Math.ceil((officials-plan.includedOfficials)/OFFICIAL_BLOCK_SIZE));
 const estimate=plan.annualPriceCents===null?null:plan.annualPriceCents+extraBlocks*OFFICIAL_BLOCK_ANNUAL_PRICE_CENTS;
 const recommendation=useMemo<PlanCode>(()=>officials<=50?"starter":officials<=100?"pro":officials<=250?"premier":"enterprise",[officials]);
 const choose=(code:PlanCode)=>{setSelected(code);setSetupOpen(true);requestAnimationFrame(()=>document.getElementById("organization-setup")?.scrollIntoView({behavior:"smooth",block:"start"}));};

 return <main className={styles.page}>
  <nav className={styles.nav}><div className={styles.brand}><img src="/brand/ref-pro-group-logo.png" alt="Ref Pro Group — Powering Better Officiating" width="78" height="64" style={{width:"78px",height:"64px",objectFit:"contain"}}/><span/><img src="/brand/refassign-logo.png" alt="RefAssign — Assign, Develop, Manage" width="246" height="65" style={{width:"auto",height:"58px",objectFit:"contain"}}/></div><div className={styles.navLinks}><a href="#plans">Plans</a><a href="#how-it-works">How it works</a><button onClick={()=>setSetupOpen(true)}>Start setup</button></div></nav>
  <header className={styles.hero}>
   <div className={styles.heroCopy}><p className={styles.eyebrow}>Assign · Develop · Manage</p><h1>A plan that grows with your officiating program.</h1><p>Manage games, assignments, officials and payments in one place. Officials always create and use their accounts at no cost.</p><div className={styles.heroActions}><a href="#plans">Compare plans</a><span>14-day free trial · No credit card</span></div></div>
   <div className={styles.capacityPanel}><div className={styles.capacityTop}><div><span>Plan finder</span><h2>How many active officials?</h2></div><strong>{officials}</strong></div><input aria-label="Number of active officials" type="range" min="10" max="350" step="5" value={officials} onChange={e=>setOfficials(Number(e.target.value))}/><div className={styles.rangeLabels}><span>10</span><span>350+</span></div><div className={styles.recommendation}><span>Recommended</span><b>{PLAN_CATALOG[recommendation].name}</b><small>{PLAN_CATALOG[recommendation].includedOfficials?`Includes up to ${PLAN_CATALOG[recommendation].includedOfficials} active officials`:"Custom capacity and support"}</small></div></div>
  </header>
  <section className={styles.status}><span className={databaseConnected?styles.statusDot:styles.statusDotWarning}/><b>{databaseConnected?"Test environment connected":"Test connection needs attention"}</b><p>This preview uses separate test data and does not access Iowa Soccer.</p></section>
  <section className={styles.plans} id="plans"><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Simple annual pricing</p><h2>Choose the right level of support</h2></div><p>Need more capacity? Add officials in blocks of 25 for $50 per year.</p></div><div className={styles.planGrid}>
   {orderedPlans.map(code=>{const item=PLAN_CATALOG[code];const popular=code==="pro";const recommended=code===recommendation;return <article className={`${styles.card} ${popular?styles.popular:""} ${selected===code?styles.selected:""}`} key={code}>{popular&&<div className={styles.ribbon}>Most popular</div>}<div className={styles.cardHead}><div><h3>{item.name}</h3><p>{descriptions[code]}</p></div>{recommended&&<span className={styles.match}>Your match</span>}</div><div className={styles.price}>{money(item.annualPriceCents)}{item.annualPriceCents!==null&&<small>/ year</small>}</div><p className={styles.capacity}>{item.includedOfficials===null?"250+ officials":"Up to "+item.includedOfficials+" officials"}</p><ul>{features[code].map(feature=><li key={feature}><span>✓</span>{feature}</li>)}</ul><button onClick={()=>choose(code)}>{code==="enterprise"?"Talk with our team":"Choose "+item.name}</button></article>})}
  </div></section>
  {setupOpen&&<section className={styles.setup} id="organization-setup"><div className={styles.setupIntro}><p className={styles.eyebrow}>Organization setup</p><h2>Let’s configure your RefAssign workspace.</h2><p>This creates a draft in the isolated test environment. Nothing is billed or added to Iowa Soccer.</p><ol><li className={styles.currentStep}>Organization</li><li>League coverage</li><li>Review</li></ol></div><form className={styles.form} onSubmit={event=>event.preventDefault()}><div className={styles.formHeader}><div><span>Selected plan</span><h3>{plan.name}</h3></div><button type="button" onClick={()=>document.getElementById("plans")?.scrollIntoView({behavior:"smooth"})}>Change plan</button></div><label>Organization name<input value={organization} onChange={e=>setOrganization(e.target.value)} placeholder="Example: Central Iowa Officials Association"/></label><div className={styles.formRow}><label>Primary sport<select value={sport} onChange={e=>setSport(e.target.value)}><option>Soccer</option><option>Basketball</option><option>Baseball</option><option>Softball</option><option>Volleyball</option><option>Football</option><option>Other</option></select></label><label>Expected active officials<input type="number" min="1" value={officials} onChange={e=>setOfficials(Math.max(1,Number(e.target.value)))}/></label></div><div className={styles.summary}><div><span>Base plan</span><b>{money(plan.annualPriceCents)}</b></div><div><span>Additional official blocks</span><b>{plan.includedOfficials===null?"Custom":extraBlocks}</b></div><div className={styles.total}><span>Estimated annual total</span><b>{money(estimate)}</b></div></div><button className={styles.continue} type="button" disabled={!organization.trim()}>Continue to league coverage <span>→</span></button><small>Draft only. Billing will not begin from this preview.</small></form></section>}
  <section className={styles.how} id="how-it-works"><div><span>1</span><h3>Set up your organization</h3><p>Add the organization, sport and expected official count.</p></div><div><span>2</span><h3>Connect league coverage</h3><p>Assign leagues, locations and assignor responsibility.</p></div><div><span>3</span><h3>Invite your team</h3><p>Officials join free and your plan tracks active usage.</p></div></section>
  <footer><div><img src="/brand/ref-pro-group-logo.png" alt="Ref Pro Group, LLC" width="63" height="52" style={{width:"63px",height:"52px",objectFit:"contain"}}/><span aria-hidden="true" style={{height:"30px",width:"1px",background:"#71859b",margin:"0 12px"}}/><img src="/brand/refassign-logo.png" alt="RefAssign" width="189" height="50" style={{width:"auto",height:"42px",objectFit:"contain"}}/></div><p>RefAssign is a Ref Pro Group, LLC platform.</p><span>© 2026 Ref Pro Group, LLC</span></footer>
 </main>;
}
