const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),ts=require('typescript'),vm=require('vm');
const path='app/api/assignments/read-only/route.ts';
function setup({user={id:'mentor'},permission=true,subscription=true,leagues=[{league_id:'allowed-league'}]}={}) {
 const calls=[];const responses={organization_memberships:{data:permission?{viewer_permissions:['assignments']}:null},refassign_subscriptions:{data:subscription?{status:'active'}:null},organization_member_league_access:{data:leagues},games:{data:[{id:'allowed-game'}]}};
 const service={from:table=>{const call={table,filters:[]};calls.push(call);const q={then:(resolve,reject)=>Promise.resolve(responses[table]).then(resolve,reject)};for(const method of ['select','eq','order','limit','maybeSingle','in','gte','range'])q[method]=(...args)=>{call.filters.push([method,...args]);return q};return q}};
 const module={exports:{}};const mockRequire=name=>name==='next/server'?{NextResponse:{json:(body,opts)=>({body,status:opts?.status||200})}}:name.endsWith('/supabase/server')?{createServerSupabaseClient:async()=>({auth:{getUser:async()=>({data:{user}})}})}:name.endsWith('/supabase/admin')?{createServiceClient:()=>service}:require(name);
 vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,require:mockRequire,Date,Number,Promise});
 return {calls,run:query=>module.exports.GET({nextUrl:new URL('https://ref-assign.com/api/assignments/read-only?'+(query||'organizationId=selected-org'))})};
}
test('rejects anonymous, missing permission and inactive subscription',async()=>{for(const [options,status] of [[{user:null},401],[{permission:false},403],[{subscription:false},402]]){const t=setup(options);assert.equal((await t.run()).status,status);assert(!t.calls.some(c=>c.table==='games'));}});
test('reads only granted organization and leagues with safe fields',async()=>{const t=setup();assert.equal((await t.run()).status,200);const q=t.calls.find(c=>c.table==='games');assert(q.filters.some(f=>f[0]==='eq'&&f[1]==='organization_id'&&f[2]==='selected-org'));assert.deepEqual(q.filters.find(f=>f[0]==='in')[2],['allowed-league']);const projection=q.filters.find(f=>f[0]==='select')[1];for(const secret of ['response_token','email','phone','rank','pay_rate'])assert(!projection.includes(secret));assert(t.calls.find(c=>c.table==='organization_memberships').filters.some(f=>f[1]==='user_id'&&f[2]==='mentor'));});
test('no league grants yields no game query, invalid date and page rejected',async()=>{const t=setup({leagues:[]});assert.equal((await t.run()).body.games.length,0);assert(!t.calls.some(c=>c.table==='games'));assert.equal((await setup().run('organizationId=o&from=invalid')).status,400);assert.equal((await setup().run('organizationId=o&offset=-1')).status,400);});
test('mentor preset maps to viewer with assignments only; page has no assignment mutations',()=>{const source=fs.readFileSync('components/OrganizationTeamManager.tsx','utf8');assert(source.includes('role:role==="mentor_viewer"?"viewer":role'));assert(source.includes('newRole="viewer";newPermissions=["assignments"]'));assert(!source.includes('p_new_role:newRole,...args'));const view=fs.readFileSync('components/ReadOnlyAssignments.tsx','utf8');assert(!/\.rpc\(|\.update\(|\.insert\(|method:\s*["']POST/.test(view));});
