const {test}=require('node:test');const assert=require('node:assert/strict');const ts=require('typescript');const fs=require('fs');const vm=require('vm');
function setup(contact, primaryOk=true, copyOk=true) {
 const calls=[],logs=[];const module={exports:{}};
 const fakeFetch=async(url,init)=>{calls.push({url,init});return new Response(JSON.stringify({id:'primary-id'}),{status:(calls.length===1?primaryOk:copyOk)?200:500});};
 vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/communications/officialCc.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,require,fetch:fakeFetch,Headers,URLSearchParams,AbortSignal,console});
 const service={from:table=>table==='official_cc_contacts'?{select:()=>({eq:()=>({maybeSingle:async()=>({data:contact,error:null})})})}:{insert:async row=>{logs.push(row);return {error:null}}}};
 return {...module.exports,calls,logs,service};
}
const email={method:'POST',headers:{'Idempotency-Key':'original'},body:JSON.stringify({to:['ref@example.com'],subject:'Assignment',html:'Details <a href="https://ref-assign.com/assignment/secret">View Assignment</a>'})};
test('email copy preserves primary, removes bearer link, uses distinct idempotency key',async()=>{const t=setup({name:'Parent',email:'parent@example.com'});const r=await t.sendOfficialNotification(t.service,'official','https://api.resend.com/emails',email);assert.equal((await r.json()).id,'primary-id');assert.equal(t.calls.length,2);assert.equal(t.calls[0].init.body,email.body);const copy=JSON.parse(t.calls[1].init.body);assert.equal(copy.to[0],'parent@example.com');assert(!copy.html.includes('/assignment/secret'));assert(copy.html.includes('Details'));assert.notEqual(t.calls[1].init.headers.get('Idempotency-Key'),'original');assert.equal(t.logs[0].status,'sent');});
test('text copy follows text channel and retains message without response token',async()=>{const t=setup({name:'Parent',phone:'+15155551212',email:'other@example.com'});await t.sendOfficialNotification(t.service,'o','https://api.twilio.com/messages',{method:'POST',body:new URLSearchParams({To:'+15155551000',Body:'Game tomorrow https://ref-assign.com/assignment/token',StatusCallback:'callback'})});const b=t.calls[1].init.body;assert.equal(b.get('To'),'+15155551212');assert(b.get('Body').includes('Game tomorrow'));assert(!b.get('Body').includes('/assignment/token'));assert.equal(b.get('StatusCallback'),null);});
test('no CC when optional contact is empty, primary fails, or address is duplicate',async()=>{for(const [contact,ok] of [[null,true],[{name:'Parent',email:'parent@example.com'},false],[{name:'Parent',email:'REF@example.com'},true]]){const t=setup(contact,ok);await t.sendOfficialNotification(t.service,'o','https://api.resend.com/emails',email);assert.equal(t.calls.length,1);}});
test('missing selected channel and CC provider failure are recorded without failing original',async()=>{for(const [contact,copyOk] of [[{name:'Parent',phone:'+15155551212'},true],[{name:'Parent',email:'parent@example.com'},false]]){const t=setup(contact,true,copyOk);const r=await t.sendOfficialNotification(t.service,'o','https://api.resend.com/emails',email);assert(r.ok);assert.equal(t.logs[0].status,'failed');}});
test('all assignment email routes select the referee id',()=>{for(const path of ['assignments/publish','assignments/confirm','games/status','cron/assignment-reminders','communications/send']){const s=fs.readFileSync(`app/api/${path}/route.ts`,'utf8');assert(s.includes('official_id,'),path);assert(s.includes('sendOfficialNotification('),path);}});
