'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { createClient } from '../lib/supabase/client'

type Game = { id:number; date:string; time:string; sport:string; level:string; home:string; away:string; location:string; needed:number; assigned:number }
type Official = { id:string; first_name:string; last_name:string; email:string|null; phone:string|null; home_area:string|null; sports:string[]; certification_level:string|null; active:boolean }
type RankRow = { official_id:string; rank:number }
const SPORTS=['Soccer','Football','Basketball','Baseball','Softball','Volleyball','Wrestling','Track & Field','Other']
const emptyForm={first_name:'',last_name:'',email:'',phone:'',home_area:'',sports:['Soccer'],certification_level:'',rank:1}

const initialGames: Game[] = [
 {id:1,date:'Aug 28',time:'7:00 PM',sport:'Soccer',level:'Varsity',home:'Ankeny',away:'Johnston',location:'Ankeny Stadium',needed:3,assigned:0},
 {id:2,date:'Aug 29',time:'6:30 PM',sport:'Soccer',level:'Varsity',home:'Waukee',away:'Urbandale',location:'Waukee Stadium',needed:3,assigned:2},
 {id:3,date:'Aug 30',time:'7:00 PM',sport:'Football',level:'Varsity',home:'Southeast Polk',away:'Dowling',location:'SEP Stadium',needed:5,assigned:5},
 {id:4,date:'Sep 1',time:'6:00 PM',sport:'Volleyball',level:'JV',home:'Johnston',away:'Ankeny',location:'Johnston HS',needed:2,assigned:1}
]
const nav=['Dashboard','Games','Officials','Assignments','Calendar','Sports & Rules']

export default function Home(){
 const supabase=useMemo(()=>createClient(),[]); const [section,setSection]=useState('Dashboard'); const [games,setGames]=useState(initialGames); const [sport,setSport]=useState('All')
 const stats=useMemo(()=>({games:games.length,need:games.filter(g=>g.assigned===0).length,partial:games.filter(g=>g.assigned>0&&g.assigned<g.needed).length,full:games.filter(g=>g.assigned>=g.needed).length}),[games])
 const filtered=sport==='All'?games:games.filter(g=>g.sport===sport); const badge=(g:Game)=>g.assigned>=g.needed?<span className="badge green">Fully assigned</span>:g.assigned?<span className="badge amber">Partially assigned</span>:<span className="badge red">Needs officials</span>; const autoAssign=()=>setGames(gs=>gs.map(g=>({...g,assigned:g.needed})))
 async function signOut(){await supabase.auth.signOut();window.location.href='/login'}
 return <div className="shell"><aside><div className="brand">Ref<span>Assign</span></div><div className="tag">OFFICIALS MANAGEMENT</div><nav>{nav.map(n=><button key={n} className={section===n?'active':''} onClick={()=>setSection(n)}>{n}</button>)}</nav><div className="asideFoot">Built for soccer.<br/>Ready for every sport.<br/><button className="signOutButton" onClick={signOut}>Sign out</button></div></aside><main>
 <header><div><h1>{section}</h1><p>{section==='Dashboard'?'Multi-sport officials scheduling • Soccer-ready':'RefAssign scheduling workspace'}</p></div><div className="headerActions"><button className="secondary">Import Games</button><button className="primary">+ Add Game</button></div></header>
 {section==='Dashboard'&&<><div className="metrics"><Metric n={stats.games} t="Games this week"/><Metric n={stats.need} t="Need officials"/><Metric n={stats.partial} t="Partially assigned"/><Metric n={stats.full} t="Fully assigned"/><Metric n={0} t="Potential conflicts"/></div><div className="columns"><section className="card"><div className="cardHead"><h2>Upcoming Games</h2><button onClick={()=>setSection('Games')}>View all</button></div><GameTable games={games} badge={badge}/></section><section className="card"><h2>Open Positions</h2>{games.filter(g=>g.assigned<g.needed).map(g=><div className="open" key={g.id}><div><b>{g.home} vs {g.away}</b><small>{g.sport} • {g.date} • {g.needed-g.assigned} open</small></div><button onClick={()=>setSection('Assignments')}>Assign</button></div>)}</section></div></>}
 {section==='Games'&&<section className="card"><div className="toolbar"><h2>Game Schedule</h2><select value={sport} onChange={e=>setSport(e.target.value)}><option>All</option>{SPORTS.slice(0,6).map(s=><option key={s}>{s}</option>)}</select></div><GameTable games={filtered} badge={badge}/></section>}
 {section==='Officials'&&<OfficialsDirectory/>}
 {section==='Assignments'&&<><div className="actionbar"><div><h2>Assignment Center</h2><p>Fill required crew positions and optionally add a Mentor.</p></div><button className="success" onClick={autoAssign}>⚡ Auto Assign Open Games</button></div>{games.map(g=><section className="card assignment" key={g.id}><div><h3>{g.home} vs {g.away}</h3><p>{g.date} • {g.time} • {g.sport} • {g.location}</p>{g.sport==='Soccer'&&<small>Optional: 4th Official • Mentor</small>}</div><div className="fill"><b>{g.assigned}/{g.needed}</b><span>required positions filled</span></div>{badge(g)}</section>)}</>}
 {section==='Calendar'&&<section className="card"><h2>Calendar</h2><div className="calendar">{Array.from({length:28},(_,i)=><div className="day" key={i}><b>{i+1}</b>{i<games.length&&<span>{games[i].sport}<br/>{games[i].home}</span>}</div>)}</div></section>}
 {section==='Sports & Rules'&&<section className="card"><h2>Sport Assignment Rules</h2><Rule sport="Soccer" count="3 required" roles="Center Referee • AR1 • AR2 • optional 4th Official • optional Mentor"/><Rule sport="Football" count="5–7" roles="Referee • Umpire • Lines • Back/Field/Side Judges"/><Rule sport="Basketball" count="2–3" roles="Crew Chief • Referees"/><Rule sport="Baseball / Softball" count="2–4" roles="Plate Umpire • Base Umpires"/><Rule sport="Volleyball" count="2–4" roles="R1 • R2 • Line Judges"/></section>}
 </main></div>
}

function OfficialsDirectory(){
 const supabase=useMemo(()=>createClient(),[]); const [officials,setOfficials]=useState<Official[]>([]); const [ranks,setRanks]=useState<Record<string,number>>({}); const [canRank,setCanRank]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [showForm,setShowForm]=useState(false); const [saving,setSaving]=useState(false); const [editingId,setEditingId]=useState<string|null>(null); const [query,setQuery]=useState(''); const [sportFilter,setSportFilter]=useState('All'); const [form,setForm]=useState(emptyForm)
 async function load(){setLoading(true);setError('');const {data,error}=await supabase.from('officials').select('id,first_name,last_name,email,phone,home_area,sports,certification_level,active').order('last_name').order('first_name');if(error){setError(error.message);setLoading(false);return}setOfficials((data||[]) as Official[]);const {data:userData}=await supabase.auth.getUser();if(userData.user){const {data:profile}=await supabase.from('profiles').select('role').eq('id',userData.user.id).maybeSingle();const allowed=['admin','assignor','scheduler'].includes(profile?.role||'');setCanRank(allowed);if(allowed){const {data:rankData}=await supabase.from('official_rankings').select('official_id,rank');const map:Record<string,number>={};((rankData||[]) as RankRow[]).forEach(r=>map[r.official_id]=Number(r.rank));setRanks(map)}}setLoading(false)}
 useEffect(()=>{load()},[])
 function toggleSport(s:string){setForm(f=>({...f,sports:f.sports.includes(s)?f.sports.filter(x=>x!==s):[...f.sports,s]}))}
 function startAdd(){setEditingId(null);setForm(emptyForm);setShowForm(true);setError('')}
 function startEdit(o:Official){setEditingId(o.id);setForm({first_name:o.first_name,last_name:o.last_name,email:o.email||'',phone:o.phone||'',home_area:o.home_area||'',sports:o.sports,certification_level:o.certification_level||'',rank:ranks[o.id]??1});setShowForm(true);setError('')}
 async function saveOfficial(e:FormEvent){e.preventDefault();if(!form.sports.length){setError('Select at least one sport.');return}setSaving(true);setError('');const payload={first_name:form.first_name.trim(),last_name:form.last_name.trim(),email:form.email.trim()||null,phone:form.phone.trim()||null,home_area:form.home_area.trim()||null,sports:form.sports,certification_level:form.certification_level.trim()||null};let officialId=editingId;if(editingId){const {error}=await supabase.from('officials').update(payload).eq('id',editingId);if(error){setSaving(false);setError(error.message);return}}else{const {data,error}=await supabase.from('officials').insert(payload).select('id').single();if(error){setSaving(false);setError(error.message);return}officialId=data.id}if(canRank&&officialId){const rank=Math.round(Number(form.rank)*10)/10;if(rank<1||rank>10){setSaving(false);setError('Rank must be between 1.0 and 10.0.');return}const {error:rankError}=await supabase.from('official_rankings').upsert({official_id:officialId,rank});if(rankError){setSaving(false);setError(rankError.message);return}}setSaving(false);setShowForm(false);setEditingId(null);setForm(emptyForm);load()}
 async function toggle(o:Official){const {error}=await supabase.from('officials').update({active:!o.active}).eq('id',o.id);if(error)setError(error.message);else load()}
 const visible=officials.filter(o=>{const q=query.toLowerCase().trim();const matches=!q||`${o.first_name} ${o.last_name} ${o.email||''} ${o.phone||''} ${o.home_area||''}`.toLowerCase().includes(q);return matches&&(sportFilter==='All'||o.sports.includes(sportFilter))})
 return <section className="card"><div className="cardHead"><div><h2>Officials Directory</h2><p>{officials.length} officials in your live database</p></div><button className="primary" onClick={showForm?()=>setShowForm(false):startAdd}>{showForm?'Cancel':'+ Add Official'}</button></div>
 <div className="toolbar"><input placeholder="Search officials…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={sportFilter} onChange={e=>setSportFilter(e.target.value)}><option>All</option>{SPORTS.map(s=><option key={s}>{s}</option>)}</select></div>
 {showForm&&<form className="officialForm" onSubmit={saveOfficial}><label>First name<input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Last name<input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Home area<input placeholder="Des Moines" value={form.home_area} onChange={e=>setForm({...form,home_area:e.target.value})}/></label><label>Certification / level<input placeholder="USSF Grassroots, Varsity" value={form.certification_level} onChange={e=>setForm({...form,certification_level:e.target.value})}/></label><fieldset><legend>Sports</legend><div className="sportChecks">{SPORTS.map(s=><label key={s}><input type="checkbox" checked={form.sports.includes(s)} onChange={()=>toggleSport(s)}/>{s}</label>)}</div></fieldset>{canRank&&<label>Rank <small>Admin / Assignor only</small><input type="number" min="1" max="10" step="0.1" required value={form.rank.toFixed(1)} onChange={e=>setForm({...form,rank:Number(e.target.value)})}/></label>}<div className="formActions"><button type="button" className="secondary" onClick={()=>setShowForm(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':editingId?'Save Changes':'Save Official'}</button></div></form>}
 {error&&<div className="errorBox">{error}</div>}{loading?<p>Loading officials…</p>:visible.length===0?<div className="emptyState"><h3>No officials found</h3><p>{officials.length?'Try changing your search or sport filter.':'Add your first official to start building the RefAssign directory.'}</p></div>:<div className="tableWrap"><table><thead><tr><th>Official</th><th>Sports</th><th>Area</th><th>Level</th>{canRank&&<th>Rank</th>}<th>Status</th><th></th></tr></thead><tbody>{visible.map(o=><tr key={o.id}><td><b>{o.first_name} {o.last_name}</b><small>{o.email||o.phone||'No contact info'}</small></td><td>{o.sports.join(', ')}</td><td>{o.home_area||'—'}</td><td>{o.certification_level||'—'}</td>{canRank&&<td><b>{(ranks[o.id]??1).toFixed(1)}</b></td>}<td><span className={o.active?'badge green':'badge red'}>{o.active?'Active':'Inactive'}</span></td><td><button className="tableButton" onClick={()=>startEdit(o)}>Edit</button> <button className="tableButton" onClick={()=>toggle(o)}>{o.active?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div>}</section>
}
function Metric({n,t}:{n:number,t:string}){return <div className="metric"><i></i><strong>{n}</strong><span>{t}</span></div>}
function GameTable({games,badge}:{games:Game[],badge:(g:Game)=>React.ReactNode}){return <div className="tableWrap"><table><thead><tr><th>Date</th><th>Game</th><th>Sport</th><th>Location</th><th>Officials</th><th>Status</th></tr></thead><tbody>{games.map(g=><tr key={g.id}><td>{g.date}<small>{g.time}</small></td><td><b>{g.home} vs {g.away}</b><small>{g.level}</small></td><td>{g.sport}</td><td>{g.location}</td><td>{g.assigned}/{g.needed}</td><td>{badge(g)}</td></tr>)}</tbody></table></div>}
function Rule({sport,count,roles}:{sport:string,count:string,roles:string}){return <div className="rule"><div><b>{sport}</b><small>{roles}</small></div><span className="badge blue">{count} officials</span></div>}
