'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../lib/supabase/client'
type Game={id:string;sport_id:string;league_id:string|null;level_id:string|null;starts_at:string;officials_needed:number;sports:{name:string}|null;leagues:{name:string}|null;home:{name:string}|null;away:{name:string}|null;venue:{name:string;city:string|null;state:string|null;latitude:number|null;longitude:number|null}|null}
type Official={id:string;first_name:string;last_name:string;sports:string[];active:boolean;home_city:string|null;home_state:string|null;home_latitude:number|null;home_longitude:number|null}
type Position={id:string;sport_id:string;name:string;required:boolean;sort_order:number}
type Assignment={id:string;game_id:string;official_id:string;position_id:string;status:string}
type Rank={official_id:string;rank:number};type EligL={official_id:string;league_id:string};type EligV={official_id:string;level_id:string}
function miles(a:number|null,b:number|null,c:number|null,d:number|null){if([a,b,c,d].some(x=>x==null))return null;const r=3958.7613,p=Math.PI/180,dlat=(c!-a!)*p,dlon=(d!-b!)*p;const q=Math.sin(dlat/2)**2+Math.cos(a!*p)*Math.cos(c!*p)*Math.sin(dlon/2)**2;return r*2*Math.asin(Math.sqrt(q))}
export default function AssignmentsManager(){const supabase=useMemo(()=>createClient(),[]);const [games,setGames]=useState<Game[]>([]);const [officials,setOfficials]=useState<Official[]>([]);const [positions,setPositions]=useState<Position[]>([]);const [assignments,setAssignments]=useState<Assignment[]>([]);const [ranks,setRanks]=useState<Record<string,number>>({});const [leagueElig,setLeagueElig]=useState<EligL[]>([]);const [levelElig,setLevelElig]=useState<EligV[]>([]);const [selected,setSelected]=useState<string>('');const [error,setError]=useState('');const [saving,setSaving]=useState('')
async function load(){setError('');const [g,o,p,a,r,le,ve]=await Promise.all([supabase.from('games').select('id,sport_id,league_id,level_id,starts_at,officials_needed,sports(name),leagues(name),home:teams!games_home_team_id_fkey(name),away:teams!games_away_team_id_fkey(name),venue:venues(name,city,state,latitude,longitude)').order('starts_at'),supabase.from('officials').select('id,first_name,last_name,sports,active,home_city,home_state,home_latitude,home_longitude').eq('active',true),supabase.from('sport_positions').select('id,sport_id,name,required,sort_order').order('sort_order'),supabase.from('assignments').select('id,game_id,official_id,position_id,status'),supabase.from('official_rankings').select('official_id,rank'),supabase.from('official_league_eligibility').select('official_id,league_id'),supabase.from('official_level_eligibility').select('official_id,level_id')]);const err=g.error||o.error||p.error||a.error||r.error||le.error||ve.error;if(err){setError(err.message);return}setGames((g.data||[]) as unknown as Game[]);setOfficials((o.data||[]) as Official[]);setPositions((p.data||[]) as Position[]);setAssignments((a.data||[]) as Assignment[]);const rm:Record<string,number>={};((r.data||[]) as Rank[]).forEach(x=>rm[x.official_id]=Number(x.rank));setRanks(rm);setLeagueElig((le.data||[]) as EligL[]);setLevelElig((ve.data||[]) as EligV[]);if(!selected&&g.data?.[0])setSelected(g.data[0].id)}useEffect(()=>{load()},[])
const game=games.find(g=>g.id===selected);const gamePositions=game?positions.filter(p=>p.sport_id===game.sport_id):[]
function eligible(o:Official){if(!game)return false;if(!o.sports.some(s=>s.toLowerCase()===game.sports?.name.toLowerCase()))return false;const ol=leagueElig.filter(x=>x.official_id===o.id);const ov=levelElig.filter(x=>x.official_id===o.id);if(game.league_id&&ol.length&&!ol.some(x=>x.league_id===game.league_id))return false;if(game.level_id&&ov.length&&!ov.some(x=>x.level_id===game.level_id))return false;return true}
function candidates(positionId:string){if(!game)return[];const used=new Set(assignments.filter(a=>a.game_id===game.id&&a.position_id!==positionId).map(a=>a.official_id));return officials.filter(o=>eligible(o)&&!used.has(o.id)).map(o=>({...o,distance:miles(o.home_latitude,o.home_longitude,game.venue?.latitude??null,game.venue?.longitude??null),rank:ranks[o.id]??1})).sort((a,b)=>b.rank-a.rank||((a.distance??9999)-(b.distance??9999)))}
async function assign(positionId:string,officialId:string){if(!game)return;setSaving(positionId);setError('');const existing=assignments.find(a=>a.game_id===game.id&&a.position_id===positionId);let result;if(!officialId&&existing)result=await supabase.from('assignments').delete().eq('id',existing.id);else if(existing)result=await supabase.from('assignments').update({official_id:officialId,status:'proposed'}).eq('id',existing.id);else result=await supabase.from('assignments').insert({game_id:game.id,official_id:officialId,position_id:positionId,status:'proposed'});if(result.error)setError(result.error.message);await load();setSaving('')}
return <><section className="card"><div className="cardHead"><div><h2>Assignment Center</h2><p>Eligible officials are filtered by sport, league and level, then ranked by Rank and distance.</p></div></div>{error&&<div className="errorBox">{error}</div>}<label>Select Game<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select a game</option>{games.map(g=><option key={g.id} value={g.id}>{new Date(g.starts_at).toLocaleDateString()} — {g.home?.name||'TBD'} vs {g.away?.name||'TBD'}</option>)}</select></label></section>{game&&<section className="card"><div className="cardHead"><div><h2>{game.home?.name||'TBD'} vs {game.away?.name||'TBD'}</h2><p>{new Date(game.starts_at).toLocaleString()} • {game.sports?.name} • {game.leagues?.name||'No league'} • {game.venue?.name||'TBD'}</p></div></div><div className="tableWrap"><table><thead><tr><th>Position</th><th>Assigned Official</th><th>Eligible Candidates</th></tr></thead><tbody>{gamePositions.map(pos=>{const current=assignments.find(a=>a.game_id===game.id&&a.position_id===pos.id);const list=candidates(pos.id);return <tr key={pos.id}><td><b>{pos.name}</b><small>{pos.required?'Required':'Optional'}</small></td><td>{current?officials.find(o=>o.id===current.official_id)?.first_name+' '+officials.find(o=>o.id===current.official_id)?.last_name:'Open'}</td><td><select disabled={saving===pos.id} value={current?.official_id||''} onChange={e=>assign(pos.id,e.target.value)}><option value="">Open / Unassign</option>{list.map(o=><option key={o.id} value={o.id}>{o.first_name} {o.last_name} — Rank {o.rank.toFixed(1)}{o.distance!=null?` — ${o.distance.toFixed(1)} mi`:''}</option>)}</select></td></tr>})}</tbody></table></div><p><small>Distance appears when both the official home and venue have latitude/longitude coordinates. Officials with no league or level restrictions are treated as eligible for all leagues/levels in their sport.</small></p></section>}</>}
