'use client'

import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../lib/supabase/client'

type Detail={assignment_id:string;official_name:string;official_email:string|null;position_name:string|null;starts_at:string;home_team:string|null;away_team:string|null;location_name:string|null;location_address:string|null;location_city:string|null;location_state:string|null;league_name:string|null;level_name:string|null;notes:string|null;status:string;published_at:string;accept_by:string|null;responded_at:string|null;decline_reason:string|null}
const reasons=['Schedule Conflict','Travel / Distance','Team Conflict','Injury / Illness','Already Assigned','Other']

export default function AssignmentResponse({token}:{token:string}){const supabase=useMemo(()=>createClient(),[]);const [detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[working,setWorking]=useState(false),[declining,setDeclining]=useState(false),[reason,setReason]=useState('Schedule Conflict'),[other,setOther]=useState('')
async function load(){setLoading(true);setError('');const {data,error:e}=await supabase.rpc('get_assignment_by_token',{p_token:token});if(e)setError(e.message);else setDetail((data?.[0]||null) as Detail|null);setLoading(false)}useEffect(()=>{void load()},[token])
async function respond(response:'accepted'|'declined'){const why=response==='declined'?(reason==='Other'?other.trim():reason):null;if(response==='declined'&&!why){setError('Please enter a decline reason.');return}setWorking(true);setError('');const {error:e}=await supabase.rpc('respond_to_assignment',{p_token:token,p_response:response,p_decline_reason:why});if(e)setError(e.message);else{setDeclining(false);await load()}setWorking(false)}
if(loading)return <main className="publicAssignment"><section className="card"><p>Loading assignment…</p></section></main>;if(error&&!detail)return <main className="publicAssignment"><section className="card"><h1>Assignment unavailable</h1><div className="errorBox">{error}</div></section></main>;if(!detail)return <main className="publicAssignment"><section className="card"><h1>Assignment not found</h1></section></main>
const done=['accepted','confirmed','declined'].includes(detail.status);const expired=!!detail.accept_by&&new Date()>new Date(detail.accept_by);const address=[detail.location_address,detail.location_city,detail.location_state].filter(Boolean).join(', ')
return <main className="publicAssignment"><section className="card assignmentResponseCard"><div className="responseBrand"><b>REF PRO GROUP</b><span>Game Assignment</span></div><h1>{detail.home_team||'TBD'} <span>vs</span> {detail.away_team||'TBD'}</h1><p className="responseGreeting">{detail.official_name}, you have been assigned to this game.</p><div className="assignmentDetailGrid"><div><small>Date & Time</small><b>{new Date(detail.starts_at).toLocaleString()}</b></div><div><small>Position</small><b>{detail.position_name||'Official'}</b></div><div><small>Location</small><b>{detail.location_name||'TBD'}</b><span>{address}</span></div><div><small>League / Level</small><b>{detail.league_name||'—'}{detail.level_name?` • ${detail.level_name}`:''}</b></div></div>{detail.notes&&<div className="responseNotes"><small>Game Information</small><p>{detail.notes}</p></div>}{detail.accept_by&&!done&&<div className="deadlineBox"><b>Response required by</b><span>{new Date(detail.accept_by).toLocaleString()}</span></div>}{error&&<div className="errorBox">{error}</div>}{done?<div className={`responseResult ${detail.status==='declined'?'declined':'accepted'}`}><h2>{detail.status==='declined'?'Assignment Declined':'Assignment Accepted'}</h2><p>{detail.status==='declined'?(detail.decline_reason||'Your decline has been recorded.'):'You are confirmed for this assignment.'}</p></div>:expired?<div className="errorBox">The response deadline for this assignment has passed. Please contact your assignor.</div>:declining?<div className="declinePanel"><h3>Why are you declining?</h3><select value={reason} onChange={e=>setReason(e.target.value)}>{reasons.map(x=><option key={x}>{x}</option>)}</select>{reason==='Other'&&<textarea placeholder="Enter reason" value={other} onChange={e=>setOther(e.target.value)}/>}<div className="responseActions"><button className="secondary" onClick={()=>setDeclining(false)}>Cancel</button><button className="dangerButton" disabled={working} onClick={()=>void respond('declined')}>{working?'Submitting…':'Confirm Decline'}</button></div></div>:<div className="responseActions"><button className="acceptButton" disabled={working} onClick={()=>void respond('accepted')}>{working?'Submitting…':'Accept Assignment'}</button><button className="dangerButton" disabled={working} onClick={()=>setDeclining(true)}>Decline Assignment</button></div>}<p className="responseFooter">© 2026 Ref Pro Group, LLC. All rights reserved.</p></section></main>}
