"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../lib/supabase/client";

type Audit={id:number;entity_type:"assignment"|"game";entity_id:string;game_id:string|null;assignment_id:string|null;action:string;actor_name:string|null;summary:string;old_data:Record<string,unknown>|null;new_data:Record<string,unknown>|null;occurred_at:string};
const actionLabels:Record<string,string>={assigned:"Assigned",unassigned:"Unassigned",assignment_changed:"Assignment Changed",confirmed:"Confirmed",assignment_cancelled:"Assignment Cancelled",assignment_status_changed:"Status Changed",published:"Published",game_status_changed:"Game Status Changed",game_edited:"Game Edited"};
export default function AuditHistoryManager(){
 const supabase=useMemo(()=>createClient(),[]),[rows,setRows]=useState<Audit[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[entity,setEntity]=useState("all"),[action,setAction]=useState("all"),[search,setSearch]=useState(""),[expanded,setExpanded]=useState<number|null>(null);
 async function load(){setLoading(true);setError("");const{data,error:e}=await supabase.from("audit_history").select("id,entity_type,entity_id,game_id,assignment_id,action,actor_name,summary,old_data,new_data,occurred_at").order("occurred_at",{ascending:false}).limit(500);if(e)setError(e.message);else setRows((data||[]) as Audit[]);setLoading(false)}
 useEffect(()=>{void load()},[supabase]);
 const actions=[...new Set(rows.map(r=>r.action))].sort(),q=search.trim().toLowerCase(),visible=rows.filter(r=>(entity==="all"||r.entity_type===entity)&&(action==="all"||r.action===action)&&(!q||r.summary.toLowerCase().includes(q)||(r.actor_name||"").toLowerCase().includes(q)));
 return <section className="card"><div className="cardHead"><div><h2>Assignment &amp; Game Audit History</h2><p>Who changed assignments or games, what changed, and when.</p></div><button className="secondary" disabled={loading} onClick={()=>void load()}>Refresh</button></div><div className="toolbar" style={{justifyContent:"flex-start",margin:"14px 0",flexWrap:"wrap"}}><select value={entity} onChange={e=>setEntity(e.target.value)}><option value="all">All records</option><option value="assignment">Assignments</option><option value="game">Games</option></select><select value={action} onChange={e=>setAction(e.target.value)}><option value="all">All actions</option>{actions.map(a=><option key={a} value={a}>{actionLabels[a]||a}</option>)}</select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search person or game"/></div>{error&&<div className="errorBox">{error}</div>}{loading?<p>Loading audit history…</p>:visible.length?<div className="tableWrap"><table><thead><tr><th>Time</th><th>Action</th><th>Details</th><th>Changed By</th><th></th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{new Date(r.occurred_at).toLocaleDateString()}<small>{new Date(r.occurred_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit",second:"2-digit"})}</small></td><td><span className={`badge ${r.action.includes("cancel")||r.action==="unassigned"?"red":r.action==="confirmed"?"green":"blue"}`}>{actionLabels[r.action]||r.action}</span></td><td><b>{r.summary}</b><small>{r.entity_type==='assignment'?'Assignment record':'Game record'}</small>{expanded===r.id&&<pre style={{whiteSpace:"pre-wrap",fontSize:10,maxWidth:700,background:"#f8fafc",padding:10,borderRadius:7,overflow:"auto"}}>{JSON.stringify({before:r.old_data,after:r.new_data},null,2)}</pre>}</td><td>{r.actor_name||"System"}</td><td><button className="tableButton" onClick={()=>setExpanded(expanded===r.id?null:r.id)}>{expanded===r.id?"Hide":"View Changes"}</button></td></tr>)}</tbody></table></div>:<div className="emptyState"><p>No audit records match these filters.</p></div>}</section>
}
