"use client";

import { addReportCopyright } from "../lib/pdfCopyright";

import { useEffect, useMemo, useState } from "react";
import ReportSavedViews from "./ReportSavedViews";

type Named = { name: string } | Array<{ name: string }> | null;
type Audit = { id: number; organization_id: string | null; entity_type: "assignment" | "game"; entity_id: string; game_id: string | null; assignment_id: string | null; action: string; actor_name: string | null; summary: string; old_data: Record<string, unknown> | null; new_data: Record<string, unknown> | null; occurred_at: string };
type ImportError = { id: number; organization_id: string | null; import_type: string; file_name: string | null; error_message: string; row_number: number | null; resolved_at: string | null; created_at: string };
type SyncRun = { id: string; organization_id: string | null; source_system: string; source_event_id: string; started_at: string; finished_at: string | null; status: string; groups_checked: number; games_found: number; games_added: number; games_updated: number; games_cancelled: number; games_skipped: number; error_message: string | null };
type Game = { id: string; organization_id: string | null; game_number: string | null; starts_at: string; status: string; source_system: string | null; source_event_id: string | null; source_match_id: string | null; source_synced_at: string | null; leagues: Named; levels: Named; location: Named; home: Named; away: Named };
type Assignment = { id: string; game_id: string; status: string; email_error: string | null; cancellation_email_error: string | null };
type Communication = { id: string; game_id: string; delivery_status: string; error_message: string | null; created_at: string };
type Organization = { id: string; name: string };
type CenterData = { reportingAccess: "standard" | "premium"; organizations: Organization[]; audit: Audit[]; importErrors: ImportError[]; syncRuns: SyncRun[]; games: Game[]; assignments: Assignment[]; communications: Communication[] };
type View = "activity" | "insights";

const actionLabels: Record<string, string> = { assigned: "Assigned", unassigned: "Unassigned", assignment_changed: "Assignment changed", confirmed: "Confirmed", assignment_cancelled: "Assignment cancelled", assignment_status_changed: "Status changed", published: "Published", game_status_changed: "Game status changed", game_edited: "Game edited" };
const scheduleFields: Record<string, string> = { starts_at: "Date or time", location_id: "Venue", home_team_id: "Home team", away_team_id: "Away team", level_id: "Level", league_id: "League", status: "Status", officials_needed: "Officials needed", duration_minutes: "Duration" };
const oneName = (value: Named) => (Array.isArray(value) ? value[0]?.name : value?.name) || "";
const quote = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;
const pct = (value: number, total: number) => total ? Math.round(value / total * 100) : 100;
const changeFields = (row: Audit) => Object.keys(scheduleFields).filter((key) => JSON.stringify(row.old_data?.[key]) !== JSON.stringify(row.new_data?.[key]));
const tone = (action: string) => action.includes("cancel") || action === "unassigned" ? "red" : action === "confirmed" || action === "assigned" ? "green" : "blue";
const sourceLabel = (source: string) => source === "gotsport" ? "GotSport" : source.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function AuditHistoryManager({ organizationId }: { organizationId?: string }) {
  const [data, setData] = useState<CenterData | null>(null), [view, setView] = useState<View>("activity"), [loading, setLoading] = useState(true), [error, setError] = useState(""), [entity, setEntity] = useState("all"), [action, setAction] = useState("all"), [organization, setOrganization] = useState("all"), [period, setPeriod] = useState("90"), [search, setSearch] = useState(""), [expanded, setExpanded] = useState<number | null>(null), [resolving, setResolving] = useState<number | null>(null);
  const load = async () => { setLoading(true); setError(""); try { const query = organizationId ? `?organizationId=${encodeURIComponent(organizationId)}` : ""; const response = await fetch(`/api/change-audit${query}`, { cache: "no-store" }), result = await response.json(); if (!response.ok) throw new Error(result.error || "Change and audit records could not be loaded."); setData(result); setOrganization(organizationId || "all"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Change and audit records could not be loaded."); } setLoading(false); };
  useEffect(() => { void load(); }, [organizationId]);

  const premium = data?.reportingAccess === "premium", organizationNames = useMemo(() => new Map((data?.organizations || []).map((row) => [row.id, row.name])), [data?.organizations]), games = useMemo(() => new Map((data?.games || []).map((row) => [row.id, row])), [data?.games]), assignmentsByGame = useMemo(() => { const rows = new Map<string, Assignment[]>(); (data?.assignments || []).forEach((row) => rows.set(row.game_id, [...(rows.get(row.game_id) || []), row])); return rows; }, [data?.assignments]), failuresByGame = useMemo(() => { const rows = new Map<string, number>(); (data?.communications || []).filter((row) => row.delivery_status === "failed").forEach((row) => rows.set(row.game_id, (rows.get(row.game_id) || 0) + 1)); (data?.assignments || []).filter((row) => row.email_error || row.cancellation_email_error).forEach((row) => rows.set(row.game_id, (rows.get(row.game_id) || 0) + 1)); return rows; }, [data?.assignments, data?.communications]);
  const cutoff = period === "all" ? 0 : Date.now() - Number(period) * 86400000, query = search.trim().toLowerCase();
  const visibleAudit = useMemo(() => (data?.audit || []).filter((row) => (entity === "all" || row.entity_type === entity) && (action === "all" || row.action === action) && (organization === "all" || row.organization_id === organization) && new Date(row.occurred_at).getTime() >= cutoff && (!query || row.summary.toLowerCase().includes(query) || (row.actor_name || "").toLowerCase().includes(query) || (row.game_id ? games.get(row.game_id)?.game_number || "" : "").toLowerCase().includes(query))), [data?.audit, entity, action, organization, cutoff, query, games]);
  const scheduleChanges = useMemo(() => (data?.audit || []).filter((row) => row.entity_type === "game" && changeFields(row).length && (organization === "all" || row.organization_id === organization) && new Date(row.occurred_at).getTime() >= cutoff).map((row) => { const game = row.game_id ? games.get(row.game_id) : undefined, assignments = row.game_id ? assignmentsByGame.get(row.game_id) || [] : []; return { row, game, fields: changeFields(row), assignments: assignments.filter((item) => !["declined", "cancelled", "canceled"].includes(item.status)).length, failures: row.game_id ? failuresByGame.get(row.game_id) || 0 : 0 }; }), [data?.audit, organization, cutoff, games, assignmentsByGame, failuresByGame]);
  const visibleErrors = (data?.importErrors || []).filter((row) => (organization === "all" || row.organization_id === organization) && new Date(row.created_at).getTime() >= cutoff && (!query || `${row.import_type} ${row.file_name || ""} ${row.error_message}`.toLowerCase().includes(query))), visibleRuns = (data?.syncRuns || []).filter((row) => (organization === "all" || row.organization_id === organization) && new Date(row.started_at).getTime() >= cutoff), unresolved = visibleErrors.filter((row) => !row.resolved_at), successfulRuns = visibleRuns.filter((row) => row.status === "success"), reliability = pct(successfulRuns.length, visibleRuns.length), lastRun = visibleRuns[0], impactedAssignments = new Set(scheduleChanges.filter((change) => change.assignments).flatMap((change) => (assignmentsByGame.get(change.row.game_id || "") || []).map((row) => row.id))).size, notificationFailures = scheduleChanges.reduce((sum, row) => sum + row.failures, 0);
  const actions = [...new Set((data?.audit || []).map((row) => row.action))].sort();
  const trends = useMemo(() => Array.from({ length: 6 }, (_, index) => { const start = new Date(); start.setDate(1); start.setHours(0, 0, 0, 0); start.setMonth(start.getMonth() - 5 + index); const end = new Date(start); end.setMonth(end.getMonth() + 1); const changes = (data?.audit || []).filter((row) => row.entity_type === "game" && changeFields(row).length && new Date(row.occurred_at) >= start && new Date(row.occurred_at) < end).length, errors = (data?.importErrors || []).filter((row) => new Date(row.created_at) >= start && new Date(row.created_at) < end).length; return { label: start.toLocaleDateString(undefined, { month: "short" }), changes, errors }; }), [data?.audit, data?.importErrors]);
  const comparisons = useMemo(() => { const rows = new Map<string, { changes: number; affected: Set<string>; errors: number }>(); scheduleChanges.forEach((change) => { const label = organizationNames.get(change.row.organization_id || "") || oneName(change.game?.leagues || null) || "Not assigned", current = rows.get(label) || { changes: 0, affected: new Set<string>(), errors: 0 }; current.changes++; (assignmentsByGame.get(change.row.game_id || "") || []).forEach((row) => current.affected.add(row.id)); rows.set(label, current); }); visibleErrors.forEach((item) => { const label = organizationNames.get(item.organization_id || "") || "Not assigned", current = rows.get(label) || { changes: 0, affected: new Set<string>(), errors: 0 }; current.errors++; rows.set(label, current); }); return [...rows.entries()].sort((a, b) => b[1].changes + b[1].errors - a[1].changes - a[1].errors); }, [scheduleChanges, visibleErrors, organizationNames, assignmentsByGame]);
  const resolveError = async (item: ImportError) => { setResolving(item.id); try { const query = organizationId ? `?organizationId=${encodeURIComponent(organizationId)}` : ""; const response = await fetch(`/api/change-audit${query}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ importErrorId: item.id, resolved: !item.resolved_at }) }), result = await response.json(); if (!response.ok) throw new Error(result.error || "Import error could not be updated."); setData((current) => current ? { ...current, importErrors: current.importErrors.map((row) => row.id === item.id ? { ...row, resolved_at: result.resolved_at } : row) } : current); } catch (reason) { setError(reason instanceof Error ? reason.message : "Import error could not be updated."); } setResolving(null); };
  const exportCsv = () => { const rows = view === "activity" ? [["Time", "Organization", "Record", "Action", "Summary", "Changed By"], ...visibleAudit.map((row) => [new Date(row.occurred_at).toLocaleString(), organizationNames.get(row.organization_id || "") || "", row.entity_type, actionLabels[row.action] || row.action, row.summary, row.actor_name || "System"])] : [["Time", "Game", "Organization", "Changed Fields", "Assignments Affected", "Notification Failures"], ...scheduleChanges.map((item) => [new Date(item.row.occurred_at).toLocaleString(), item.game?.game_number || "", organizationNames.get(item.row.organization_id || "") || oneName(item.game?.leagues || null), item.fields.map((field) => scheduleFields[field]).join(", "), item.assignments, item.failures])]; const blob = new Blob([rows.map((row) => row.map(quote).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }), url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; anchor.download = view === "activity" ? "refassign-audit-history.csv" : "refassign-schedule-import-insights.csv"; anchor.click(); URL.revokeObjectURL(url); };
  const exportPdf = async () => { if (!premium) return; const [{ jsPDF }, { default: autoTable }] = await Promise.all([import("jspdf"), import("jspdf-autotable")]), document = new jsPDF({ orientation: "landscape" }); document.setTextColor(12, 30, 55); document.setFontSize(18); document.text("RefAssign Change & Audit Center", 14, 17); document.setFontSize(9); document.text(`${reliability}% sync reliability • ${scheduleChanges.length} schedule changes • ${impactedAssignments} assignments affected • ${unresolved.length} unresolved import errors`, 14, 25); autoTable(document, { startY: 32, head: [["Time", "Game", "Organization", "Changed", "Assignments", "Notification failures"]], body: scheduleChanges.map((item) => [new Date(item.row.occurred_at).toLocaleString(), item.game?.game_number || "—", organizationNames.get(item.row.organization_id || "") || oneName(item.game?.leagues || null) || "—", item.fields.map((field) => scheduleFields[field]).join(", "), item.assignments, item.failures]), styles: { fontSize: 7 }, headStyles: { fillColor: [37, 99, 235] } }); autoTable(document, { head: [["Import time", "Type / File", "Row", "Problem", "Status"]], body: visibleErrors.map((item) => [new Date(item.created_at).toLocaleString(), `${item.import_type}${item.file_name ? ` / ${item.file_name}` : ""}`, item.row_number || "—", item.error_message, item.resolved_at ? "Resolved" : "Needs review"]), styles: { fontSize: 7 }, headStyles: { fillColor: [12, 30, 55] } }); addReportCopyright(document); document.save("refassign-change-audit-center.pdf"); };

  return <section className="card changeAuditCenter"><div className="cardHead"><div><h2>Change &amp; Audit Center</h2><p>Review activity, schedule changes, import results, and affected assignments in one place.</p></div><div className="headerActions">{premium ? <span className="badge">Premium reporting</span> : null}<button className="secondary" disabled={loading || (view === "activity" ? !visibleAudit.length : !scheduleChanges.length)} onClick={exportCsv}>Export CSV</button>{premium ? <button className="secondary" onClick={() => void exportPdf()}>Export PDF</button> : null}<button className="secondary" disabled={loading} onClick={() => void load()}>Refresh</button></div></div>
    <div className="reportDimensionTabs changeAuditTabs"><button className={view === "activity" ? "active" : ""} onClick={() => setView("activity")}>Activity Log</button><button className={view === "insights" ? "active" : ""} onClick={() => setView("insights")}>Schedule &amp; Import Insights</button></div>
    <div className="reportFilters changeAuditFilters"><label>Organization<select value={organization} onChange={(event) => setOrganization(event.target.value)}><option value="all">All organizations</option>{(data?.organizations || []).map((row) => <option value={row.id} key={row.id}>{row.name}</option>)}</select></label><label>Period<select value={period} onChange={(event) => setPeriod(event.target.value)}><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last year</option><option value="all">All history</option></select></label>{view === "activity" ? <><label>Record type<select value={entity} onChange={(event) => setEntity(event.target.value)}><option value="all">All records</option><option value="assignment">Assignments</option><option value="game">Games</option></select></label><label>Action<select value={action} onChange={(event) => setAction(event.target.value)}><option value="all">All actions</option>{actions.map((item) => <option key={item} value={item}>{actionLabels[item] || item}</option>)}</select></label></> : null}<label className="changeAuditSearch">Search<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Person, game, file, or problem" /></label></div>
    <ReportSavedViews organizationId={organizationId} reportKey="audit" filters={{ view, organization, period, entity, action, search }} onApply={(saved) => { if (saved.view) setView(saved.view as View); if (saved.organization) setOrganization(saved.organization); if (saved.period) setPeriod(saved.period); if (saved.entity) setEntity(saved.entity); if (saved.action) setAction(saved.action); setSearch(saved.search || ""); }} />
    {error ? <div className="errorBox">{error}</div> : null}{loading ? <p>Loading change and audit records…</p> : view === "activity" ? <>{visibleAudit.length ? <div className="tableWrap"><table className="officialReportTable auditTable"><thead><tr><th>Time</th><th>Organization</th><th>Action</th><th>Details</th><th>Changed by</th><th></th></tr></thead><tbody>{visibleAudit.map((row) => <tr key={row.id}><td>{new Date(row.occurred_at).toLocaleDateString()}<small>{new Date(row.occurred_at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit", second: "2-digit" })}</small></td><td>{organizationNames.get(row.organization_id || "") || "—"}</td><td><span className={`badge ${tone(row.action)}`}>{actionLabels[row.action] || row.action}</span></td><td><b>{row.summary}</b><small>{row.entity_type === "assignment" ? "Assignment record" : "Game record"}</small>{expanded === row.id ? <pre className="auditChanges">{JSON.stringify({ before: row.old_data, after: row.new_data }, null, 2)}</pre> : null}</td><td>{row.actor_name || "System"}</td><td><button className="tableButton" onClick={() => setExpanded(expanded === row.id ? null : row.id)}>{expanded === row.id ? "Hide" : "View changes"}</button></td></tr>)}</tbody></table></div> : <div className="emptyState"><p>No audit records match these filters.</p></div>}</> : <>
      <div className="reportMetrics changeAuditMetrics"><div><span>Sync reliability</span><b>{reliability}%</b><small>{successfulRuns.length} of {visibleRuns.length} runs successful</small></div><div><span>Schedule changes</span><b>{scheduleChanges.length}</b><small>Material changes in this period</small></div><div><span>Assignments affected</span><b>{impactedAssignments}</b><small>Officials potentially impacted</small></div><div><span>Needs review</span><b>{unresolved.length}</b><small>Unresolved import errors</small></div><div><span>Notification failures</span><b>{notificationFailures}</b><small>On changed games</small></div><div><span>Last schedule sync</span><b>{lastRun ? new Date(lastRun.started_at).toLocaleDateString() : "—"}</b><small>{lastRun ? `${sourceLabel(lastRun.source_system)} · ${lastRun.status}` : "No automated sync history"}</small></div></div>
      {!premium ? <div className="reportPremiumNotice"><b>Premium insights</b><span>Unlock change trends, organization comparisons, reliability analysis, prioritized alerts, and PDF summaries.</span></div> : null}
      {premium ? <div className="reportCharts"><article className="reportChart"><h4>Six-month change trend</h4><div className="trendRows auditTrend">{trends.map((row) => <div key={row.label}><span>{row.label}</span><div><i className="gamesTrend" style={{ width: `${Math.max(4, Math.min(100, row.changes * 8))}%` }}><b>{row.changes} changes</b></i><i className="auditErrorTrend" style={{ width: `${Math.max(4, Math.min(100, row.errors * 8))}%` }}><b>{row.errors} errors</b></i></div></div>)}</div></article><article className="reportChart"><h4>Organization comparison</h4><div className="reportBars">{comparisons.slice(0, 8).map(([label, row]) => <div className="reportBarRow" key={label}><span title={label}>{label}</span><i><em style={{ width: `${Math.min(100, (row.changes + row.errors) * 10)}%` }} /></i><b>{row.changes + row.errors}</b></div>)}{!comparisons.length ? <p>No changes to compare.</p> : null}</div></article></div> : null}
      <div className="changeAuditGrid"><article><h3>Schedule change impact</h3><div className="tableWrap"><table className="officialReportTable changeImpactTable"><thead><tr><th>Changed</th><th>Game</th><th>What changed</th><th>Assignments</th><th>Delivery</th></tr></thead><tbody>{scheduleChanges.slice(0, 150).map((item) => <tr key={item.row.id}><td>{new Date(item.row.occurred_at).toLocaleDateString()}<small>{item.row.actor_name || "System"}</small></td><td><b>#{item.game?.game_number || "—"}</b><small>{oneName(item.game?.home || null)} vs {oneName(item.game?.away || null)}</small></td><td>{item.fields.map((field) => scheduleFields[field]).join(", ")}</td><td>{item.assignments}</td><td>{item.failures ? <span className="badge red">{item.failures} failed</span> : <span className="badge green">No failures</span>}</td></tr>)}{!scheduleChanges.length ? <tr><td colSpan={5}>No material schedule changes match these filters.</td></tr> : null}</tbody></table></div></article><article><h3>Automated schedule runs</h3><div className="tableWrap"><table className="officialReportTable syncRunTable"><thead><tr><th>Run</th><th>Source</th><th>Result</th><th>Added</th><th>Updated</th><th>Cancelled</th><th>Skipped</th></tr></thead><tbody>{visibleRuns.slice(0, 100).map((run) => <tr key={run.id}><td>{new Date(run.started_at).toLocaleString()}</td><td>{sourceLabel(run.source_system)}<small>Event {run.source_event_id}</small></td><td><span className={`badge ${run.status === "success" ? "green" : run.status === "failed" ? "red" : "blue"}`}>{run.status}</span>{run.error_message ? <small>{run.error_message}</small> : null}</td><td>{run.games_added}</td><td>{run.games_updated}</td><td>{run.games_cancelled}</td><td>{run.games_skipped}</td></tr>)}{!visibleRuns.length ? <tr><td colSpan={7}>No automated schedule runs match this period.</td></tr> : null}</tbody></table></div></article></div>
      <h3>Import problems</h3><div className="tableWrap"><table className="officialReportTable importProblemTable"><thead><tr><th>Imported</th><th>Organization</th><th>Type / File</th><th>Row</th><th>Problem</th><th>Status</th><th></th></tr></thead><tbody>{visibleErrors.map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleString()}</td><td>{organizationNames.get(item.organization_id || "") || "—"}</td><td>{sourceLabel(item.import_type)}<small>{item.file_name || "No filename recorded"}</small></td><td>{item.row_number || "—"}</td><td>{item.error_message}</td><td><span className={`badge ${item.resolved_at ? "green" : "red"}`}>{item.resolved_at ? "Resolved" : "Needs review"}</span></td><td><button className="tableButton" disabled={resolving === item.id} onClick={() => void resolveError(item)}>{resolving === item.id ? "Saving…" : item.resolved_at ? "Reopen" : "Mark resolved"}</button></td></tr>)}{!visibleErrors.length ? <tr><td colSpan={7}>No import problems match these filters.</td></tr> : null}</tbody></table></div>
    </>}</section>;
}
