'use client'

import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../lib/supabase/client'

type Level={id:string;name:string}
type Position={id:string;name:string;sport_id:string;sports?:{name:string}|null}
type Rule={id:string;level_id:string|null;position_id:string;max_games_per_day:number;rest_days:number;same_team_days:number;active:boolean}

export default function AutoAssignManager(){
 const supabase=useMemo(()=>createClient(),[])
 const [levels,setLevels]=useState<Level[]>([]),[positions,setPositions]=useState<Position[]>([]),[rules,setRules]=useState<Rule[]>([]),[levelId,setLevelId]=useState(''),[positionId,setPositionId]=useState(''),[maxGames,setMaxGames]=useState(2),[restDays,setRestDays]=useState(0),[sameTeamDays,setSameTeamDays]=useState(7),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false)
 async function load(){const[l,p,r]=await Promise.all([supabase.from('levels').select('id,name').order('name'),supabase.from('sport_positions').select('id,name,sport_id,sports(name)').order('sort_order'),supabase.from('auto_assign_rules').select('*')]);const e=l.error||p.error||r.error;if(e){setError(e.message);return}setLevels((l.data||[]) as Level[]);setPositions((p.data||[]) as unknown as Position[]);setRules((r.data||[]) as Rule[])}
 useEffect(()=>{void load()},[])
 async function save(){if(!positionId){setError('Select a position.');return}setSaving(true);setError('');setNotice('');const existing=rules.find(r=>(r.level_id||'')===levelId&&r.position_id===positionId);const payload={level_id:levelId||null,position_id:positionId,max_games_per_day:maxGames,rest_days:restDays,same_team_days:sameTeamDays,active:true};const result=existing?await supabase.from('auto_assign_rules').update(payload).eq('id',existing.id):await supabase.from('auto_assign_rules').insert(payload);if(result.error)setError(result.error.message);else setNotice('Auto Assign rule saved.');await load();setSaving(false)}
 async function remove(id:string){const{error:e}=await supabase.from('auto_assign_rules').delete().eq('id',id);if(e)setError(e.message);else{setNotice('Rule removed.');await load()}}
 const levelName=(id:string|null)=>id?levels.find(x=>x.id===id)?.name||'Unknown':'All Levels',posName=(id:string)=>{const p=positions.find(x=>x.id===id);return p?`${p.sports?.name||''} — ${p.name}`:id}
 return <><section className="card"><div className="cardHead"><div><h2>Auto Assign Settings</h2><p>Set workload, recovery and team-repeat rules by level and position.</p></div></div>{error&&<div className="errorBox">{error}</div>}{notice&&<div className="loginMessage">{notice}</div>}<div className="formGrid"><label>Level<select value={levelId} onChange={e=>setLevelId(e.target.value)}><option value="">All Levels</option>{levels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Position<select value={positionId} onChange={e=>setPositionId(e.target.value)}><option value="">Select position</option>{positions.map(x=><option key={x.id} value={x.id}>{x.sports?.name||'Sport'} — {x.name}</option>)}</select></label><label>Maximum Games Per Day<input type="number" min={1} max={10} value={maxGames} onChange={e=>setMaxGames(Number(e.target.value))}/></label><label>Rest Days<input type="number" min={0} max={30} value={restDays} onChange={e=>setRestDays(Number(e.target.value))}/><small>Minimum full days before/after another assignment for this level and position.</small></label><label>Days Before Same Team Again<input type="number" min={0} max={90} value={sameTeamDays} onChange={e=>setSameTeamDays(Number(e.target.value))}/><small>Prevents repeatedly assigning the same official to either team too soon.</small></label></div><div className="headerActions" style={{marginTop:14}}><button className="primary" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save Auto Assign Rule'}</button></div></section><section className="card"><div className="cardHead"><div><h2>Current Rules</h2><p>A level-specific rule takes priority over an All Levels rule for the same position.</p></div></div><div className="tableWrap"><table><thead><tr><th>Level</th><th>Position</th><th>Games / Day</th><th>Rest Days</th><th>Same Team</th><th></th></tr></thead><tbody>{rules.length?rules.map(r=><tr key={r.id}><td>{levelName(r.level_id)}</td><td>{posName(r.position_id)}</td><td>{r.max_games_per_day}</td><td>{r.rest_days}</td><td>{r.same_team_days} days</td><td><button className="secondary" onClick={()=>void remove(r.id)}>Remove</button></td></tr>):<tr><td colSpan={6}>No Auto Assign rules yet.</td></tr>}</tbody></table></div></section></>}
