"use client";

import { addReportCopyright } from "../lib/pdfCopyright";

import { useEffect, useMemo, useState } from "react";

type Named = { id: string; name: string } | null;
type Official = { id: string; first_name: string; last_name: string; email: string | null; active: boolean; certification_level: string | null; college_license_level: string | null; high_school_license_level: string | null; us_soccer_license_level: string | null };
type Registration = { id: string; official_id: string; registration_year: number; status: string; payment_status: string; paid_at: string | null; reviewed_at: string | null; registration_program_id: string | null; registration_programs: Named | Named[] };
type Program = { id: string; name: string; slug: string; active: boolean };
type Module = { id: string; program_id: string; title: string; required: boolean; active: boolean; content_type: string; course_end_at: string | null };
type Progress = { module_id: string; official_id: string; status: string; completed_at: string | null };
type Eligibility = { official_id: string; league_id?: string; level_id?: string; leagues?: Named | Named[]; levels?: Named | Named[] };
type Assignment = { id: string; official_id: string; status: string; games: { id: string; game_number: string | null; starts_at: string; status: string; league_id: string | null; level_id: string | null; organization_id: string | null; leagues: { name: string } | { name: string }[] | null; levels: { name: string } | { name: string }[] | null; location: { name: string } | { name: string }[] | null; home: { name: string } | { name: string }[] | null; away: { name: string } | { name: string }[] | null } | null; sport_positions: { name: string } | { name: string }[] | null };
type ComplianceRow = { official: Official; organizationIds: string[]; programIds: string[]; registration: "Complete" | "Action needed" | "Not required"; payment: "Complete" | "Action needed" | "Not required"; certification: boolean; trainingComplete: number; trainingRequired: number; leagues: string[]; levels: string[]; issues: string[]; critical: boolean; assignedViolations: Assignment[]; expiresIn: number | null };

const one = <T,>(value: T | T[] | null | undefined): T | null => Array.isArray(value) ? value[0] || null : value || null;
const officialName = (official: Official) => `${official.first_name} ${official.last_name}`.trim();
const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const quote = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;

export default function ComplianceEligibilityReport({ organizationId }: { organizationId?: string }) {
  const [officials, setOfficials] = useState<Official[]>([]), [registrations, setRegistrations] = useState<Registration[]>([]), [programs, setPrograms] = useState<Program[]>([]), [memberships, setMemberships] = useState<Array<{ program_id: string; official_id: string }>>([]), [organizationLinks, setOrganizationLinks] = useState<Array<{ organization_id: string; official_id: string }>>([]), [organizations, setOrganizations] = useState<Array<{ id: string; name: string }>>([]), [modules, setModules] = useState<Module[]>([]), [progress, setProgress] = useState<Progress[]>([]), [quizAttempts, setQuizAttempts] = useState<Progress[]>([]), [leagueEligibility, setLeagueEligibility] = useState<Eligibility[]>([]), [levelEligibility, setLevelEligibility] = useState<Eligibility[]>([]), [assignments, setAssignments] = useState<Assignment[]>([]), [reportingAccess, setReportingAccess] = useState<"standard" | "premium">("standard"), [organization, setOrganization] = useState("all"), [program, setProgram] = useState("all"), [status, setStatus] = useState("all"), [issue, setIssue] = useState("all"), [search, setSearch] = useState(""), [warningDays, setWarningDays] = useState(90), [loading, setLoading] = useState(true), [error, setError] = useState("");

  useEffect(() => { void (async () => { try { const response = await fetch(`/api/reports/compliance?organizationId=${encodeURIComponent(organizationId || "")}`, { cache: "no-store" }), result = await response.json(); if (!response.ok) throw new Error(result.error || "Compliance reporting could not be loaded."); setOfficials(result.officials || []); setRegistrations(result.registrations || []); setPrograms(result.programs || []); setMemberships(result.programMemberships || []); setOrganizationLinks(result.organizationOfficials || []); setOrganizations(result.organizations || []); setModules(result.modules || []); setProgress(result.progress || []); setQuizAttempts(result.quizAttempts || []); setLeagueEligibility(result.leagueEligibility || []); setLevelEligibility(result.levelEligibility || []); setAssignments(result.assignments || []); setReportingAccess(result.reportingAccess === "premium" ? "premium" : "standard"); const stored = window.localStorage.getItem("refassign-compliance-warning-days"); if (stored) setWarningDays(Math.max(1, Number(stored) || 90)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Compliance reporting could not be loaded."); } setLoading(false); })(); }, [organizationId]);

  const premium = reportingAccess === "premium", currentYear = new Date().getFullYear();
  const rows = useMemo<ComplianceRow[]>(() => officials.map((official) => {
    const organizationIds = organizationLinks.filter((link) => link.official_id === official.id).map((link) => link.organization_id), programIds = memberships.filter((link) => link.official_id === official.id).map((link) => link.program_id), requiredModules = modules.filter((module) => programIds.includes(module.program_id)), completedIds = new Set([...progress.filter((item) => item.official_id === official.id && item.status === "completed").map((item) => item.module_id), ...quizAttempts.filter((item) => item.official_id === official.id).map((item) => item.module_id)]), currentRegistrations = registrations.filter((item) => item.official_id === official.id && item.registration_year === currentYear && (!item.registration_program_id || programIds.includes(item.registration_program_id))), registrationRequired = programIds.length > 0, registrationComplete = !registrationRequired || programIds.every((id) => currentRegistrations.some((item) => item.registration_program_id === id && item.status === "approved")), paymentComplete = !registrationRequired || programIds.every((id) => currentRegistrations.some((item) => item.registration_program_id === id && ["paid", "waived"].includes(item.payment_status))), certification = [official.certification_level, official.college_license_level, official.high_school_license_level, official.us_soccer_license_level].some((value) => Boolean(value?.trim())), leagues = leagueEligibility.filter((item) => item.official_id === official.id).map((item) => one(item.leagues)?.name).filter(Boolean) as string[], levels = levelEligibility.filter((item) => item.official_id === official.id).map((item) => one(item.levels)?.name).filter(Boolean) as string[], incompleteTraining = requiredModules.filter((module) => !completedIds.has(module.id)), issues: string[] = [];
    if (!official.active) issues.push("Inactive official"); if (registrationRequired && !registrationComplete) issues.push("Registration incomplete"); if (registrationRequired && !paymentComplete) issues.push("Payment incomplete"); if (!certification) issues.push("Certification missing"); if (incompleteTraining.length) issues.push("Required training incomplete"); if (!leagues.length) issues.push("No league eligibility"); if (!levels.length) issues.push("No level eligibility");
    const assignedViolations = assignments.filter((assignment) => { if (assignment.official_id !== official.id || !assignment.games) return false; const game = assignment.games, leagueIds = leagueEligibility.filter((item) => item.official_id === official.id).map((item) => item.league_id), levelIds = levelEligibility.filter((item) => item.official_id === official.id).map((item) => item.level_id); return !official.active || (leagueIds.length > 0 && Boolean(game.league_id) && !leagueIds.includes(game.league_id || undefined)) || (levelIds.length > 0 && Boolean(game.level_id) && !levelIds.includes(game.level_id || undefined)) || !registrationComplete || !paymentComplete || incompleteTraining.length > 0; });
    if (assignedViolations.length) issues.unshift("Assigned while ineligible");
    const completeRegistration = currentRegistrations.find((item) => item.status === "approved"), yearEnd = new Date(currentYear, 11, 31, 23, 59, 59), expiresIn = completeRegistration ? Math.ceil((yearEnd.getTime() - Date.now()) / 86400000) : null;
    return { official, organizationIds, programIds, registration: !registrationRequired ? "Not required" : registrationComplete ? "Complete" : "Action needed", payment: !registrationRequired ? "Not required" : paymentComplete ? "Complete" : "Action needed", certification, trainingComplete: requiredModules.filter((module) => completedIds.has(module.id)).length, trainingRequired: requiredModules.length, leagues, levels, issues, critical: !official.active || !registrationComplete || !paymentComplete || incompleteTraining.length > 0 || assignedViolations.length > 0, assignedViolations, expiresIn };
  }), [officials, organizationLinks, memberships, modules, progress, quizAttempts, registrations, currentYear, leagueEligibility, levelEligibility, assignments]);
  const issueOptions = useMemo(() => [...new Set(rows.flatMap((row) => row.issues))].sort(), [rows]);
  const visible = useMemo(() => rows.filter((row) => { if (organization !== "all" && !row.organizationIds.includes(organization)) return false; if (program !== "all" && !row.programIds.includes(program)) return false; if (status === "eligible" && row.issues.length) return false; if (status === "action" && !row.issues.length) return false; if (issue !== "all" && !row.issues.includes(issue)) return false; const query = search.trim().toLowerCase(); return !query || officialName(row.official).toLowerCase().includes(query) || (row.official.email || "").toLowerCase().includes(query); }), [rows, organization, program, status, issue, search]);
  const metric = (test: (row: ComplianceRow) => boolean) => visible.filter(test).length, eligible = metric((row) => !row.issues.length), actionNeeded = visible.length - eligible, registrationComplete = metric((row) => row.registration !== "Action needed"), trainingComplete = metric((row) => row.trainingComplete === row.trainingRequired), certified = metric((row) => row.certification), violations = visible.reduce((sum, row) => sum + row.assignedViolations.length, 0);
  const coverage = [{ label: "Active", value: metric((row) => row.official.active) }, { label: "Registration", value: registrationComplete }, { label: "Payment", value: metric((row) => row.payment !== "Action needed") }, { label: "Certification", value: certified }, { label: "Training", value: trainingComplete }, { label: "League eligibility", value: metric((row) => row.leagues.length > 0) }, { label: "Level eligibility", value: metric((row) => row.levels.length > 0) }];
  const expirations = visible.filter((row) => row.expiresIn !== null && row.expiresIn >= 0 && row.expiresIn <= warningDays).sort((a, b) => (a.expiresIn || 0) - (b.expiresIn || 0));
  const followUp = [...visible].filter((row) => row.issues.length || row.expiresIn !== null && row.expiresIn <= warningDays).sort((a, b) => (b.assignedViolations.length - a.assignedViolations.length) || Number(b.critical) - Number(a.critical) || (a.expiresIn ?? 9999) - (b.expiresIn ?? 9999));
  const exportCsv = () => { const headings = ["Official", "Email", "Status", "Registration", "Payment", "Certification", "Required Training", "League Eligibility", "Level Eligibility", "Assigned Violations", "Issues"], body = visible.map((row) => [officialName(row.official), row.official.email, row.issues.length ? "Action needed" : "Eligible", row.registration, row.payment, row.certification ? "Recorded" : "Missing", `${row.trainingComplete}/${row.trainingRequired}`, row.leagues.join("; "), row.levels.join("; "), row.assignedViolations.length, row.issues.join("; ")]), blob = new Blob([[headings, ...body].map((line) => line.map(quote).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }), url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; anchor.download = "refassign-compliance-eligibility.csv"; anchor.click(); URL.revokeObjectURL(url); };
  const exportPdf = async () => { if (!premium) return; const [{ jsPDF }, { default: autoTable }] = await Promise.all([import("jspdf"), import("jspdf-autotable")]), document = new jsPDF({ orientation: "landscape" }); document.setTextColor(12, 30, 55); document.setFontSize(18); document.text("RefAssign Compliance & Eligibility", 14, 16); document.setFontSize(9); document.text(`${visible.length} officials • ${eligible} eligible • ${actionNeeded} need action • ${violations} upcoming assignment violations`, 14, 24); autoTable(document, { startY: 31, head: [["Official", "Status", "Registration", "Payment", "Certification", "Training", "League / Level", "Issues"]], body: visible.map((row) => [officialName(row.official), row.issues.length ? "Action needed" : "Eligible", row.registration, row.payment, row.certification ? "Recorded" : "Missing", `${row.trainingComplete}/${row.trainingRequired}`, `${row.leagues.length} / ${row.levels.length}`, row.issues.join(", ") || "None"]), styles: { fontSize: 7 }, headStyles: { fillColor: [37, 99, 235] } }); addReportCopyright(document); document.save("refassign-compliance-eligibility.pdf"); };

  if (loading) return <section className="card"><p>Loading compliance and eligibility…</p></section>;
  return <section className="card officialReports complianceReport"><div className="cardHead"><div><h2>Compliance &amp; Eligibility</h2><p>Review registration, payment, certification, training, and assignment eligibility in one place.</p></div><div className="headerActions">{premium && <span className="badge">Premium reporting</span>}<button className="secondary" disabled={!visible.length} onClick={exportCsv}>Export CSV</button>{premium && <button className="secondary" disabled={!visible.length} onClick={exportPdf}>Export PDF</button>}</div></div>{error && <div className="errorBox">{error}</div>}{!error && <>
    <div className="reportFilters complianceFilters"><label>Organization<select value={organization} onChange={(event) => setOrganization(event.target.value)}><option value="all">All organizations</option>{organizations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Program<select value={program} onChange={(event) => setProgram(event.target.value)}><option value="all">All programs</option>{programs.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Eligibility status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All officials</option><option value="eligible">Eligible</option><option value="action">Action needed</option></select></label><label>Compliance issue<select value={issue} onChange={(event) => setIssue(event.target.value)}><option value="all">All issues</option>{issueOptions.map((item) => <option key={item}>{item}</option>)}</select></label><label>Search official<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name or email" /></label></div>
    <div className="reportMetrics operationsMetrics"><div><span>Officials</span><b>{visible.length}</b></div><div><span>Eligible</span><b>{eligible}</b></div><div><span>Need action</span><b>{actionNeeded}</b></div><div><span>Registration complete</span><b>{registrationComplete}</b></div><div><span>Training complete</span><b>{trainingComplete}</b></div><div><span>Certification recorded</span><b>{certified}</b></div>{premium && <div className="premiumMetric"><span>Assignment violations</span><b>{violations}</b></div>}</div>
    {!premium && <div className="reportPremiumNotice"><b>Standard reporting</b><span>Upcoming assignment checks, expiration warnings, compliance graphics, prioritized follow-up, configurable alerts, and PDF export are available with Premium Reporting.</span></div>}
    {premium && <><div className="compliancePremiumHead"><label>Expiration warning<select value={warningDays} onChange={(event) => { const value = Number(event.target.value); setWarningDays(value); window.localStorage.setItem("refassign-compliance-warning-days", String(value)); }}><option value={30}>Next 30 days</option><option value={60}>Next 60 days</option><option value={90}>Next 90 days</option><option value={180}>Next 180 days</option></select></label></div><div className="reportCharts"><article className="reportChart"><h4>Requirement completion</h4><div className="reportBars">{coverage.map((item) => <div className="reportBarRow complianceBar" key={item.label}><span>{item.label}</span><i><em style={{ width: `${visible.length ? item.value / visible.length * 100 : 0}%` }} /></i><b>{visible.length ? `${Math.round(item.value / visible.length * 100)}%` : "0%"}</b></div>)}</div></article><article className="reportChart"><h4>Upcoming registration expiration</h4>{expirations.length ? <div className="complianceExpirations">{expirations.slice(0, 8).map((row) => <p key={row.official.id}><b>{officialName(row.official)}</b><span>{row.expiresIn} days remaining</span></p>)}</div> : <div className="emptyState"><p>No registrations expire within the selected warning window.</p></div>}</article></div><div className="complianceFollowUp"><h3>Prioritized follow-up</h3>{followUp.length ? followUp.slice(0, 12).map((row) => <article key={row.official.id}><div><b>{officialName(row.official)}</b><span>{row.issues.join(" • ") || `Registration expires in ${row.expiresIn} days`}</span></div>{row.assignedViolations.length > 0 && <strong>{row.assignedViolations.length} upcoming assignment{row.assignedViolations.length === 1 ? "" : "s"}</strong>}</article>) : <div className="emptyState"><p>No officials need follow-up.</p></div>}</div></>}
    <h3>Official eligibility detail</h3><div className="tableWrap"><table className="officialReportTable complianceTable"><thead><tr><th>Official</th><th>Status</th><th>Registration / Payment</th><th>Certification</th><th>Required training</th><th>League / Level eligibility</th>{premium && <th>Upcoming assignments</th>}<th>Issues</th></tr></thead><tbody>{visible.map((row) => <tr key={row.official.id}><td><b>{officialName(row.official)}</b><small>{row.official.email || "No email"}</small></td><td><span className={`budgetStatus ${row.issues.length ? "warning" : "onTrack"}`}>{row.issues.length ? "Action needed" : "Eligible"}</span></td><td>{row.registration}<small>{row.payment} payment</small></td><td>{row.certification ? "Recorded" : "Missing"}<small>{[row.official.us_soccer_license_level, row.official.high_school_license_level, row.official.college_license_level, row.official.certification_level].filter(Boolean).join(" • ") || "No license information"}</small></td><td>{row.trainingComplete}/{row.trainingRequired}<small>{row.trainingRequired ? `${row.trainingRequired - row.trainingComplete} remaining` : "None required"}</small></td><td>{row.leagues.length} league{row.leagues.length === 1 ? "" : "s"}<small>{row.levels.length} level{row.levels.length === 1 ? "" : "s"}</small></td>{premium && <td>{row.assignedViolations.length ? <span className="budgetStatus warning">{row.assignedViolations.length} violation{row.assignedViolations.length === 1 ? "" : "s"}</span> : "Clear"}</td>}<td>{row.issues.length ? row.issues.map((item) => <small className="complianceIssue" key={item}>{item}</small>) : "None"}</td></tr>)}{!visible.length && <tr><td colSpan={premium ? 8 : 7}>No officials match these filters.</td></tr>}</tbody></table></div><p className="reportFootnote">Eligibility checks use the requirements currently recorded in RefAssign. An official with no configured league or level eligibility is flagged for review rather than automatically blocked.</p>
  </>}</section>;
}
