'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {createClient} from '../lib/supabase/client'

type Opt={id:string;name:string;level_id?:string|null}
type Contact={id:string;contact_type:'admin'|'coach';first_name:string;last_name:string;email:string;phone:string|null;active:boolean}
type Access={locations:string[];leagues:string[];levels:string[];teams:string[]}
const emptyAccess:Access={locations:[],leagues:[],levels:[],teams:[]}

export default function ContactsManager(){
 const supabase=useMemo(()=>createClient(),[]);const [contacts,setContacts]=useState<Contact[]>([]);const [locations,setLocations]=useState<Opt[]>([]);const [leagues,setLeagues]=useState<Opt[]>([]);const [levels,setLevels]=useState<Opt[]>([]);const [teams,setTeams]=useState<Opt[]>([]);const [access,setAccess]=useState<Record<string,Access>>({});const [editing,setEditing]=useState<Contact|null>(null);const [showForm,setShowForm]=useState(false);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 const [form,setForm]=useState({contact_type:'coach' as 'admin'|'coach',first_name:'',last_name:'',email:'',phone:'',active:true});const [selected,setSelected]=useState<Access>(emptyAccess)
 useEffect(()=>{load()},[])
 async function load(){
  const [{data:c},{data:lo},{data:lg},{data:lv},{data:t}]=await Promise.all([supabase.from('contacts').select('id,contact_type,first_name,last_name,email,phone,active').order('last_name'),supabase.from('locations').select('id,name').order('name'),supabase.from('leagues').select('id,name').order('name'),supabase.from('levels').select('id,name').order('name'),supabase.from('teams').select('id,name,level_id').order('name')]);
  const cs=(c||[]) as Contact[];setContacts(cs);setLocations((lo||[]) as Opt[]);setLeagues((lg||[]) as Opt[]);setLevels((lv||[]) as Opt[]);setTeams((t||[]) as Opt[])
  if(cs.length){const ids=cs.map(x=>x.id);const [{data:a},{data:b},{data:d},{data:e}]=await Promise.all([supabase.from('contact_location_access').select('contact_id,location_id').in('contact_id',ids),supabase.from('contact_league_access').select('contact_id,league_id').in('contact_id',ids),supabase.from('contact_level_access').select('contact_id,level_id').in('contact_id',ids),supabase.from('contact_team_access').select('contact_id,team_id').in('contact_id',ids)]);const m:Record<string,Access>={};ids.forEach(id=>m[id]={locations:[],leagues:[],levels:[],teams:[]});(a||[]).forEach((x:any)=>m[x.contact_id]?.locations.push(x.location_id));(b||[]).forEach((x:any)=>m[x.contact_id]?.leagues.push(x.league_id));(d||[]).forEach((x:any)=>m[x.contact_id]?.levels.push(x.level_id));(e||[]).forEach((x:any)=>m[x.contact_id]?.teams.push(x.team_id));setAccess(m)}else setAccess({})
 }
 function openNew(){setEditing(null);setForm({contact_type:'coach',first_name:'',last_name:'',email:'',phone:'',active:true});setSelected({locations:[],leagues:[],levels:[],teams:[]});setShowForm(true);setNotice('')}
 function openEdit(c:Contact){setEditing(c);setForm({contact_type:c.contact_type,first_name:c.first_name,last_name:c.last_name,email:c.email,phone:c.phone||'',active:c.active});setSelected(access[c.id]||{...emptyAccess});setShowForm(true);setNotice('')}
 function toggle(kind:keyof Access,id:string){setSelected(s=>({...s,[kind]:s[kind].includes(id)?s[kind].filter(x=>x!==id):[...s[kind],id]}))}
 function toggleAll(kind:keyof Access,opts:Opt[]){setSelected(s=>({...s,[kind]:s[kind].length===opts.length?[]:opts.map(o=>o.id)}))}
 async function save(e:FormEvent){e.preventDefault();if(!form.first_name.trim()||!form.last_name.trim()||!form.email.trim()){setNotice('First name, last name and email are required.');return}if(form.contact_type==='coach'&&!selected.locations.length&&!selected.leagues.length&&!selected.levels.length&&!selected.teams.length){setNotice('A Coach must have at least one Game access selection.');return}setBusy(true);setNotice('');let id=editing?.id
  const payload={...form,first_name:form.first_name.trim(),last_name:form.last_name.trim(),email:form.email.trim().toLowerCase(),phone:form.phone.trim()||null}
  if(id){const {error}=await supabase.from('contacts').update(payload).eq('id',id);if(error){setNotice(error.message);setBusy(false);return}}else{const {data,error}=await supabase.from('contacts').insert(payload).select('id').single();if(error){setNotice(error.message);setBusy(false);return}id=data.id}
  const specs:[string,string,keyof Access][]=[['contact_location_access','location_id','locations'],['contact_league_access','league_id','leagues'],['contact_level_access','level_id','levels'],['contact_team_access','team_id','teams']];for(const [table,col,key] of specs){await supabase.from(table).delete().eq('contact_id',id!);if(selected[key].length){const {error}=await supabase.from(table).insert(selected[key].map(v=>({contact_id:id,[col]:v})));if(error){setNotice(error.message);setBusy(false);return}}}
  setBusy(false);setShowForm(false);setNotice('Contact saved.');await load()
 }
 function names(kind:keyof Access,opts:Opt[],id:string){const ids=access[id]?.[kind]||[];if(!ids.length)return 'All';return opts.filter(x=>ids.includes(x.id)).map(x=>x.name).join(', ')}
 function Selector({title,kind,opts}:{title:string;kind:keyof Access;opts:Opt[]}){const allSelected=opts.length>0&&selected[kind].length===opts.length;return <div style={{border:'1px solid #e2e8f0',borderRadius:10,padding:12}}><b>{title}</b><div style={{fontSize:12,color:'#64748b',margin:'3px 0 8px'}}>{selected[kind].length?`${selected[kind].length} selected`:'No filter selected'}</div><label style={{display:'block',padding:'5px 0 7px',fontSize:13,fontWeight:700,borderBottom:'1px solid #e2e8f0',marginBottom:4}}><input type="checkbox" checked={allSelected} onChange={()=>toggleAll(kind,opts)}/> Select All</label><div style={{maxHeight:150,overflow:'auto'}}>{opts.map(o=><label key={o.id} style={{display:'block',padding:'4px 0',fontSize:13}}><input type="checkbox" checked={selected[kind].includes(o.id)} onChange={()=>toggle(kind,o.id)}/> {o.name}</label>)}</div></div>}
 return <><section className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><h2>Contacts</h2><p style={{color:'#64748b',marginTop:4}}>Manage Admin and Coach access to game information.</p></div><button className="primary" onClick={openNew}>+ Add Contact</button></div>{notice&&<div style={{marginTop:12,padding:10,borderRadius:8,background:'#f1f5f9'}}>{notice}</div>}</section>
 {showForm&&<section className="card"><h2>{editing?'Edit Contact':'Add Contact'}</h2><form onSubmit={save}><div className="formGrid"><label>Contact Type<select value={form.contact_type} onChange={e=>setForm({...form,contact_type:e.target.value as 'admin'|'coach'})}><option value="admin">Admin</option><option value="coach">Coach</option></select></label><label>First Name<input value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Last Name<input value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></div><div style={{margin:'18px 0 10px'}}><h3>Games Access</h3><p style={{fontSize:13,color:'#64748b'}}>Choose one or many filters. A game must match every category that has selections. Leave a category blank to allow all values in that category. Admin with no selections can see all games.</p></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12}}><Selector title="Locations / Sites" kind="locations" opts={locations}/><Selector title="Leagues" kind="leagues" opts={leagues}/><Selector title="Levels" kind="levels" opts={levels}/><Selector title="Teams" kind="teams" opts={teams}/></div><div style={{display:'flex',gap:10,marginTop:18}}><button className="primary" disabled={busy}>{busy?'Saving…':'Save Contact'}</button><button type="button" className="secondary" onClick={()=>setShowForm(false)}>Cancel</button></div></form></section>}
 <section className="card"><div style={{overflowX:'auto'}}><table><thead><tr><th>Name</th><th>Type</th><th>Email / Phone</th><th>Locations</th><th>Leagues</th><th>Levels</th><th>Teams</th><th></th></tr></thead><tbody>{contacts.map(c=><tr key={c.id}><td><b>{c.first_name} {c.last_name}</b>{!c.active&&<div style={{fontSize:11,color:'#94a3b8'}}>Inactive</div>}</td><td><span className={`badge ${c.contact_type==='admin'?'blue':''}`}>{c.contact_type==='admin'?'Admin':'Coach'}</span></td><td>{c.email}<div style={{fontSize:12,color:'#64748b'}}>{c.phone||'—'}</div></td><td>{names('locations',locations,c.id)}</td><td>{names('leagues',leagues,c.id)}</td><td>{names('levels',levels,c.id)}</td><td>{names('teams',teams,c.id)}</td><td><button className="secondary" onClick={()=>openEdit(c)}>Edit</button></td></tr>)}{!contacts.length&&<tr><td colSpan={8} style={{color:'#64748b'}}>No contacts added yet.</td></tr>}</tbody></table></div></section></>
}
