"use client";

import { addReportCopyright } from "../lib/pdfCopyright";

import { useEffect, useMemo, useState } from "react";

type Named = { id?: string; name: string } | null;
type Official = { id: string; first_name: string; last_name: string; active?: boolean } | null;
type Game = { id: string; game_number: string | null; status: string; starts_at: string; leagues: Named; levels: Named; location: Named; home: Named; away: Named };
type Assignment = { id: string; game_id: string; position_id: string; official_id: string; status: string; assigned_at: string; responded_at: string | null; decline_reason: string | null; officials: Official; sport_positions: Named; games: Game };
type Decline = { key: string; assignment_id: string | null; game_id: string | null; position_id: string | null; official_id: string | null; declined_at: string; decline_reason: string | null; replacement_official_id: string | null; replaced_at: string | null };
type Period = "30" | "90" | "year" | "season" | "all";
type Dimension = "reason" | "organization" | "level" | "location" | "team" | "position" | "day" | "time";
type Row = Decline & { assignment: Assignment | null; game: Game | null; official: Official; replacement: Official; hours: number | null; outcome: "Replaced" | "Open" };

const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const officialName = (official: Official) => official ? `${official.first_name} ${official.last_name}`.trim() : "Unknown official";
const dayPart = (date: Date) => date.getHours() < 12 ? "Morning" : date.getHours() < 17 ? "Afternoon" : "Evening";
const duration = (hours: number | null) => hours === null ? "Open" : hours < 1 ? `${Math.max(1, Math.round(hours * 60))} min` : `${hours.toFixed(1)} hrs`;
const quote = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;

export default function DeclineReplacementReport({ organizationId }: { organizationId?: string }) {
  const [assignments, setAssignments] = useState<Assignment[]>([]), [officials, setOfficials] = useState<Exclude<Official, null>[]>([]), [declines, setDeclines] = useState<Decline[]>([]), [reportingAccess, setReportingAccess] = useState<"standard" | "premium">("standard"), [historyAvailable, setHistoryAvailable] = useState(false), [period, setPeriod] = useState<Period>("season"), [organization, setOrganization] = useState("all"), [level, setLevel] = useState("all"), [location, setLocation] = useState("all"), [team, setTeam] = useState("all"), [position, setPosition] = useState("all"), [reason, setReason] = useState("all"), [outcome, setOutcome] = useState("all"), [dimension, setDimension] = useState<Dimension>("reason"), [alertCount, setAlertCount] = useState(3), [loading, setLoading] = useState(true), [error, setError] = useState("");

  useEffect(() => { void (async () => {
    try {
      const response = await fetch(`/api/reports/declines?organizationId=${encodeURIComponent(organizationId || "")}`, { cache: "no-store" }), result = await response.json();
      if (!response.ok) throw new Error(result.error || "Decline reporting could not be loaded.");
      setAssignments(result.assignments || []); setOfficials(result.officials || []); setDeclines(result.declines || []); setHistoryAvailable(Boolean(result.historyAvailable)); setReportingAccess(result.reportingAccess === "premium" ? "premium" : "standard");
      const stored = window.localStorage.getItem("refassign-decline-alert-count"); if (stored) setAlertCount(Math.max(1, Number(stored) || 3));
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Decline reporting could not be loaded."); }
    setLoading(false);
  })(); }, []);

  const premium = reportingAccess === "premium", assignmentMap = useMemo(() => new Map(assignments.map((row) => [row.id, row])), [assignments]), gameMap = useMemo(() => new Map(assignments.map((row) => [row.game_id, row.games])), [assignments]), officialMap = useMemo(() => new Map(officials.map((official) => [official.id, official])), [officials]);
  const rows = useMemo<Row[]>(() => declines.map((decline) => { const assignment = decline.assignment_id ? assignmentMap.get(decline.assignment_id) || null : null, game = (decline.game_id ? gameMap.get(decline.game_id) : null) || assignment?.games || null, hours = decline.replaced_at ? Math.max(0, (new Date(decline.replaced_at).getTime() - new Date(decline.declined_at).getTime()) / 3600000) : null; return { ...decline, assignment, game, official: decline.official_id ? officialMap.get(decline.official_id) || assignment?.officials || null : null, replacement: decline.replacement_official_id ? officialMap.get(decline.replacement_official_id) || null : null, hours, outcome: decline.replaced_at ? "Replaced" : "Open" }; }), [declines, assignmentMap, gameMap, officialMap]);
  const options = useMemo(() => ({ organizations: [...new Map(assignments.filter((row) => row.games?.leagues?.id).map((row) => [row.games.leagues!.id!, row.games.leagues!.name])).entries()].sort((a, b) => a[1].localeCompare(b[1])), levels: [...new Set(assignments.map((row) => row.games?.levels?.name).filter(Boolean) as string[])].sort(), locations: [...new Set(assignments.map((row) => row.games?.location?.name).filter(Boolean) as string[])].sort(), teams: [...new Set(assignments.flatMap((row) => [row.games?.home?.name, row.games?.away?.name]).filter(Boolean) as string[])].sort(), positions: [...new Set(assignments.map((row) => row.sport_positions?.name).filter(Boolean) as string[])].sort(), reasons: [...new Set(rows.map((row) => row.decline_reason || "No reason provided"))].sort() }), [assignments, rows]);
  const visible = useMemo(() => { const now = new Date(), cutoff = new Date(now); if (period === "30") cutoff.setDate(cutoff.getDate() - 30); if (period === "90") cutoff.setDate(cutoff.getDate() - 90); if (period === "year") cutoff.setFullYear(cutoff.getFullYear() - 1); return rows.filter((row) => { const date = new Date(row.declined_at), game = row.game; if (period === "season" && date.getFullYear() !== now.getFullYear()) return false; if (!["season", "all"].includes(period) && date < cutoff) return false; if (organization !== "all" && game?.leagues?.id !== organization) return false; if (level !== "all" && game?.levels?.name !== level) return false; if (location !== "all" && game?.location?.name !== location) return false; if (team !== "all" && game?.home?.name !== team && game?.away?.name !== team) return false; if (position !== "all" && row.assignment?.sport_positions?.name !== position) return false; if (reason !== "all" && (row.decline_reason || "No reason provided") !== reason) return false; return outcome === "all" || row.outcome === outcome; }).sort((a, b) => new Date(b.declined_at).getTime() - new Date(a.declined_at).getTime()); }, [rows, period, organization, level, location, team, position, reason, outcome]);
  const offers = useMemo(() => assignments.filter((row) => { const when = new Date(row.responded_at || row.assigned_at), now = new Date(), cutoff = new Date(now), game = row.games; if (period === "30") cutoff.setDate(cutoff.getDate() - 30); if (period === "90") cutoff.setDate(cutoff.getDate() - 90); if (period === "year") cutoff.setFullYear(cutoff.getFullYear() - 1); if (period !== "all" && (period === "season" ? when.getFullYear() !== now.getFullYear() : when < cutoff)) return false; if (organization !== "all" && game?.leagues?.id !== organization) return false; if (level !== "all" && game?.levels?.name !== level) return false; if (location !== "all" && game?.location?.name !== location) return false; if (team !== "all" && game?.home?.name !== team && game?.away?.name !== team) return false; return position === "all" || row.sport_positions?.name === position; }), [assignments, period, organization, level, location, team, position]);
  const replaced = visible.filter((row) => row.outcome === "Replaced"), open = visible.filter((row) => row.outcome === "Open"), averageHours = replaced.length ? replaced.reduce((sum, row) => sum + (row.hours || 0), 0) / replaced.length : 0, declineRate = offers.length ? visible.length / offers.length * 100 : 0;
  const labelFor = (row: Row, selected: Dimension) => { const game = row.game, date = new Date(row.declined_at); if (selected === "reason") return row.decline_reason || "No reason provided"; if (selected === "organization") return game?.leagues?.name || "Unassigned"; if (selected === "level") return game?.levels?.name || "Unassigned"; if (selected === "location") return game?.location?.name || "Unassigned"; if (selected === "team") return game?.home?.name || game?.away?.name || "Unassigned"; if (selected === "position") return row.assignment?.sport_positions?.name || "Official"; if (selected === "day") return date.toLocaleDateString("en-US", { weekday: "long" }); return dayPart(date); };
  const breakdown = useMemo(() => { const values = new Map<string, Row[]>(); visible.forEach((row) => { const keys = dimension === "team" ? [...new Set([row.game?.home?.name, row.game?.away?.name].filter(Boolean) as string[])] : [labelFor(row, dimension)]; keys.forEach((key) => values.set(key, [...(values.get(key) || []), row])); }); return [...values.entries()].map(([label, items]) => ({ label, declines: items.length, open: items.filter((row) => row.outcome === "Open").length, replaced: items.filter((row) => row.outcome === "Replaced").length, average: items.filter((row) => row.hours !== null).reduce((sum, row, _, list) => sum + (row.hours || 0) / list.length, 0) })).sort((a, b) => b.declines - a.declines); }, [visible, dimension]);
  const months = useMemo(() => Array.from({ length: 6 }, (_, offset) => { const month = new Date(); month.setDate(1); month.setMonth(month.getMonth() - 5 + offset); const next = new Date(month); next.setMonth(next.getMonth() + 1); const items = rows.filter((row) => new Date(row.declined_at) >= month && new Date(row.declined_at) < next); return { label: month.toLocaleDateString("en-US", { month: "short" }), declines: items.length, open: items.filter((row) => row.outcome === "Open").length }; }), [rows]);
  const alerts = breakdown.filter((row) => row.declines >= alertCount || row.open > 0).slice(0, 8);
  const recommendations = useMemo(() => open.slice(0, 10).map((row) => { const candidates = [...officialMap.entries()].filter(([id, official]) => official.active !== false && id !== row.official_id && !assignments.some((assignment) => assignment.game_id === row.game_id && assignment.official_id === id && assignment.status !== "declined")).map(([id, official]) => { const history = assignments.filter((assignment) => assignment.official_id === id), similar = history.filter((assignment) => assignment.games?.levels?.name === row.game?.levels?.name), accepted = history.filter((assignment) => ["accepted", "confirmed"].includes(assignment.status)).length; return { official, score: similar.length * 3 + accepted, similar: similar.length, accepted }; }).sort((a, b) => b.score - a.score).slice(0, 3); return { row, candidates }; }), [open, officialMap, assignments]);
  const exportCsv = () => { const headings = ["Declined", "Game", "Organization", "Level", "Location", "Teams", "Position", "Official", "Reason", "Outcome", "Replacement", "Replacement Time (Hours)"], body = visible.map((row) => [new Date(row.declined_at).toLocaleString(), row.game?.game_number, row.game?.leagues?.name, row.game?.levels?.name, row.game?.location?.name, `${row.game?.home?.name || "TBD"} vs ${row.game?.away?.name || "TBD"}`, row.assignment?.sport_positions?.name, officialName(row.official), row.decline_reason || "No reason provided", row.outcome, officialName(row.replacement), row.hours?.toFixed(2) || ""]), blob = new Blob([[headings, ...body].map((line) => line.map(quote).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }), url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; anchor.download = "refassign-decline-replacement-analysis.csv"; anchor.click(); URL.revokeObjectURL(url); };
  const exportPdf = async () => { if (!premium) return; const [{ jsPDF }, { default: autoTable }] = await Promise.all([import("jspdf"), import("jspdf-autotable")]), document = new jsPDF({ orientation: "landscape" }); document.setTextColor(12, 30, 55); document.setFontSize(18); document.text("RefAssign Decline & Replacement Analysis", 14, 16); document.setFontSize(9); document.text(`${visible.length} declines • ${replaced.length} replaced • ${open.length} open • ${averageHours.toFixed(1)} hour average replacement time`, 14, 24); autoTable(document, { startY: 31, head: [["Declined", "Game", "Organization / Level", "Position", "Official", "Reason", "Outcome", "Replacement time"]], body: visible.map((row) => [new Date(row.declined_at).toLocaleString(), row.game?.game_number || "—", `${row.game?.leagues?.name || "—"} / ${row.game?.levels?.name || "—"}`, row.assignment?.sport_positions?.name || "Official", officialName(row.official), row.decline_reason || "No reason provided", row.outcome, duration(row.hours)]), styles: { fontSize: 7 }, headStyles: { fillColor: [37, 99, 235] } }); addReportCopyright(document); document.save("refassign-decline-replacement-analysis.pdf"); };

  if (loading) return <section className="card"><p>Loading decline and replacement analysis…</p></section>;
  return <section className="card officialReports declineReport"><div className="cardHead"><div><h2>Decline &amp; Replacement Analysis</h2><p>Find recurring decline patterns and measure how quickly open positions are refilled.</p></div><div className="headerActions">{premium && <span className="badge">Premium reporting</span>}<button className="secondary" disabled={!visible.length} onClick={exportCsv}>Export CSV</button>{premium && <button className="secondary" disabled={!visible.length} onClick={exportPdf}>Export PDF</button>}</div></div>{error && <div className="errorBox">{error}</div>}{!error && <>
    <div className="reportFilters declineFilters"><label>Period<select value={period} onChange={(event) => setPeriod(event.target.value as Period)}><option value="season">Current season</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="year">Last 12 months</option><option value="all">All dates</option></select></label><label>Organization<select value={organization} onChange={(event) => setOrganization(event.target.value)}><option value="all">All organizations</option>{options.organizations.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>Level<select value={level} onChange={(event) => setLevel(event.target.value)}><option value="all">All levels</option>{options.levels.map((name) => <option key={name}>{name}</option>)}</select></label><label>Location<select value={location} onChange={(event) => setLocation(event.target.value)}><option value="all">All locations</option>{options.locations.map((name) => <option key={name}>{name}</option>)}</select></label><label>Team<select value={team} onChange={(event) => setTeam(event.target.value)}><option value="all">All teams</option>{options.teams.map((name) => <option key={name}>{name}</option>)}</select></label><label>Position<select value={position} onChange={(event) => setPosition(event.target.value)}><option value="all">All positions</option>{options.positions.map((name) => <option key={name}>{name}</option>)}</select></label><label>Reason<select value={reason} onChange={(event) => setReason(event.target.value)}><option value="all">All reasons</option>{options.reasons.map((name) => <option key={name}>{name}</option>)}</select></label><label>Outcome<select value={outcome} onChange={(event) => setOutcome(event.target.value)}><option value="all">All outcomes</option><option>Replaced</option><option>Open</option></select></label></div>
    <div className="reportMetrics operationsMetrics"><div><span>Declines</span><b>{visible.length}</b></div><div><span>Decline rate</span><b>{declineRate.toFixed(1)}%</b></div><div><span>Replaced</span><b>{replaced.length}</b></div><div><span>Still open</span><b>{open.length}</b></div><div><span>Replacement success</span><b>{visible.length ? `${Math.round(replaced.length / visible.length * 100)}%` : "0%"}</b></div><div><span>Average fill time</span><b>{replaced.length ? duration(averageHours) : "—"}</b></div></div>
    {!historyAvailable && <div className="reportDataNotice"><b>History begins with available assignment records.</b><span>Replacement timing becomes more complete as assignment audit activity accumulates.</span></div>}
    {!premium && <div className="reportPremiumNotice"><b>Standard reporting</b><span>Trend graphics, risk alerts, candidate recommendations, adjustable thresholds, and PDF export are available with Premium Reporting.</span></div>}
    {premium && <><div className="declinePremiumControls"><label>Pattern alert after <input type="number" min="1" max="25" value={alertCount} onChange={(event) => { const value = Math.max(1, Number(event.target.value) || 1); setAlertCount(value); window.localStorage.setItem("refassign-decline-alert-count", String(value)); }} /> declines</label><label>Analyze patterns by<select value={dimension} onChange={(event) => setDimension(event.target.value as Dimension)}><option value="reason">Reason</option><option value="organization">Organization</option><option value="level">Level</option><option value="location">Location</option><option value="team">Team</option><option value="position">Position</option><option value="day">Day of week</option><option value="time">Time of day</option></select></label></div><div className="reportCharts"><article className="reportChart"><h4>Six-month decline trend</h4><div className="declineTrend">{months.map((month) => { const max = Math.max(1, ...months.map((item) => item.declines)); return <div key={month.label}><span>{month.label}</span><i><em style={{ height: `${month.declines / max * 100}%` }} /><strong style={{ height: `${month.open / max * 100}%` }} /></i><b>{month.declines}</b></div>; })}</div><div className="financialLegend"><span><i className="declineTotalKey" /> Total declines</span><span><i className="declineOpenKey" /> Still open</span></div></article><article className="reportChart"><h4>Highest-risk {titleCase(dimension)} patterns</h4><div className="reportBars">{breakdown.slice(0, 8).map((row) => <div className="reportBarRow" key={row.label}><span title={row.label}>{row.label}</span><i><em style={{ width: `${breakdown[0]?.declines ? row.declines / breakdown[0].declines * 100 : 0}%` }} /></i><b>{row.declines}</b></div>)}</div></article></div>
      <div className="declineAlerts"><div><h3>Pattern alerts</h3>{alerts.length ? alerts.map((row) => <p key={row.label}><b>{row.label}</b><span>{row.declines} declines • {row.open} still open • {row.replaced ? `${row.average.toFixed(1)} hr average refill` : "No completed refill"}</span></p>) : <div className="emptyState"><p>No patterns meet the current alert threshold.</p></div>}</div><div><h3>Replacement recommendations</h3>{recommendations.length ? recommendations.map(({ row, candidates }) => <p key={row.key}><b>{row.game?.game_number || "Game"} • {row.assignment?.sport_positions?.name || "Official"}</b><span>{candidates.length ? candidates.map((candidate) => `${officialName(candidate.official)} (${candidate.similar} similar)`).join(" • ") : "No ranked candidates available"}</span></p>) : <div className="emptyState"><p>No open declined positions match these filters.</p></div>}</div></div></>}
    <h3>Breakdown by {titleCase(dimension)}</h3><div className="tableWrap"><table className="officialReportTable declineSummaryTable"><thead><tr><th>{titleCase(dimension)}</th><th>Declines</th><th>Replaced</th><th>Still open</th><th>Success rate</th><th>Average fill time</th></tr></thead><tbody>{breakdown.map((row) => <tr key={row.label}><td><b>{row.label}</b></td><td>{row.declines}</td><td>{row.replaced}</td><td>{row.open}</td><td>{Math.round(row.replaced / row.declines * 100)}%</td><td>{row.replaced ? duration(row.average) : "—"}</td></tr>)}{!breakdown.length && <tr><td colSpan={6}>No declines match these filters.</td></tr>}</tbody></table></div>
    <h3>Decline detail</h3><div className="tableWrap"><table className="officialReportTable declineDetailTable"><thead><tr><th>Declined / Game</th><th>Organization / Level</th><th>Location / Teams</th><th>Position / Official</th><th>Reason</th><th>Outcome</th><th>Replacement</th></tr></thead><tbody>{visible.map((row) => <tr key={row.key}><td><b>{new Date(row.declined_at).toLocaleDateString()}</b><small>{new Date(row.declined_at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })} • Game {row.game?.game_number || "—"}</small></td><td>{row.game?.leagues?.name || "—"}<small>{row.game?.levels?.name || "—"}</small></td><td>{row.game?.location?.name || "—"}<small>{row.game?.home?.name || "TBD"} vs {row.game?.away?.name || "TBD"}</small></td><td>{row.assignment?.sport_positions?.name || "Official"}<small>{officialName(row.official)}</small></td><td>{row.decline_reason || "No reason provided"}</td><td><span className={`budgetStatus ${row.outcome === "Open" ? "warning" : "onTrack"}`}>{row.outcome}</span><small>{duration(row.hours)}</small></td><td>{row.outcome === "Replaced" ? officialName(row.replacement) : "—"}</td></tr>)}{!visible.length && <tr><td colSpan={7}>No declines match these filters.</td></tr>}</tbody></table></div><p className="reportFootnote">Decline rate compares recorded declines with assignment offers available in the selected period. Replacement time runs from the decline response to the next assignment for the same game position.</p>
  </>}</section>;
}
