'use client'

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react'
import { createClient } from '../lib/supabase/client'

type Sport={id:string;name:string;default_officials:number}
type Team={id:string;name:string;level:string|null;sport_id:string|null}
type Venue={id:string;name:string;city:string|null;state:string|null}
type GameRow={id:string;sport_id:string;home_team_id:string|null;away_team_id:string|null;venue_id:string|null;starts_at:string;level:string|null;officials_needed:number;status:string;notes:string|null;sports:Sport|null;home:Team|null;away:Team|null;venue:Venue|null}
type ImportRow={row:number;sport:string;level:string;home_team:string;away_team:string;date:string;time:string;venue:string;city:string;state:string;officials_needed:string;notes:string;valid:boolean;issue:string}
const blank={sport_id:'',home_name:'',away_name:'',venue_name:'',venue_city:'',venue_state:'IA',date:'',time:'',level:'Varsity',officials_needed:3,notes:''}
const REQUIRED=['sport','level','home_team','away_team','date','time','venue','city','state','officials_needed','notes']

export default function GamesManager(){
 const supabase=useMemo(()=>createClient(),[]);const [games,setGames]=useState<GameRow[]>([]);const [sports,setSports]=useState<Sport[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [show,setShow]=useState(false);const [form,setForm]=useState(blank);const [filter,setFilter]=useState('All');const [showImport,setShowImport]=useState(false);const [importRows,setImportRows]=useState<ImportRow[]>([]);const [importing,setImporting]=useState(false);const [importMessage,setImportMessage]=useState('')
 async function load(){setLoading(true);setError('');const [{data:s,error:se},{data:g,error:ge}]=await Promise.all([supabase.from('sports').select('id,name,default_officials').eq('active',true).order('name'),supabase.from('games').select('id,sport_id,home_team_id,away_team_id,venue_id,starts_at,level,officials_needed,status,notes,sports(id,name,default_officials),home:teams!games_home_team_id_fkey(id,name,level,sport_id),away:teams!games_away_team_id_fkey(id,name,level,sport_id),venue:venues(id,name,city,state)').order('starts_at')]);if(se||ge)setError((se||ge)?.message||'Unable to load games');else{setSports((s||[]) as Sport[]);setGames((g||[]) as unknown as GameRow[])}setLoading(false)}
 useEffect(()=>{load()},[])
 function chooseSport(id:string){const s=sports.find(x=>x.id===id);setForm(f=>({...f,sport_id:id,officials_needed:s?.default_officials||1}))}
 async function findOrCreateTeam(name:string,sportId:string,level:string){const clean=name.trim();const {data}=await supabase.from('teams').select('id').eq('name',clean).eq('sport_id',sportId).eq('level',level).maybeSingle();if(data)return data.id;const {data:newTeam,error}=await supabase.from('teams').insert({name:clean,sport_id:sportId,level}).select('id').single();if(error)throw error;return newTeam.id}
 async function findOrCreateVenue(name:string,city:string,state:string){const clean=name.trim();if(!clean)return null;let q=supabase.from('venues').select('id').eq('name',clean);if(city.trim())q=q.eq('city',city.trim());const {data}=await q.maybeSingle();if(data)return data.id;const {data:newVenue,error}=await supabase.from('venues').insert({name:clean,city:city.trim()||null,state:state.trim()||null}).select('id').single();if(error)throw error;return newVenue.id}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{const home=await findOrCreateTeam(form.home_name,form.sport_id,form.level);const away=await findOrCreateTeam(form.away_name,form.sport_id,form.level);const venue=await findOrCreateVenue(form.venue_name,form.venue_city,form.venue_state);const starts=new Date(`${form.date}T${form.time}:00`).toISOString();const {error}=await supabase.from('games').insert({sport_id:form.sport_id,home_team_id:home,away_team_id:away,venue_id:venue,starts_at:starts,level:form.level,officials_needed:Number(form.officials_needed),notes:form.notes.trim()||null,status:'open'});if(error)throw error;setForm(blank);setShow(false);await load()}catch(err){setError(err instanceof Error?err.message:'Unable to save game')}finally{setSaving(false)}}
 function parseCSV(text:string){const rows:string[][]=[];let row:string[]=[];let cell='';let quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell.trim());cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());cell='';if(row.some(v=>v!==''))rows.push(row);row=[]}else cell+=ch}row.push(cell.trim());if(row.some(v=>v!==''))rows.push(row);return rows}
 function validateImport(raw:string[][]){if(!raw.length)throw new Error('The CSV file is empty.');const headers=raw[0].map(h=>h.toLowerCase().trim().replace(/\s+/g,'_'));const missing=REQUIRED.filter(h=>!headers.includes(h));if(missing.length)throw new Error(`Missing columns: ${missing.join(', ')}`);return raw.slice(1).map((r,index)=>{const get=(h:string)=>r[headers.indexOf(h)]?.trim()||'';const sport=get('sport');const level=get('level');const home=get('home_team');const away=get('away_team');const date=get('date');const time=get('time');const officials=get('officials_needed');const sportExists=sports.some(s=>s.name.toLowerCase()===sport.toLowerCase());const dateOk=/^\d{4}-\d{2}-\d{2}$/.test(date)&&!Number.isNaN(new Date(`${date}T00:00:00`).getTime());const timeOk=/^([01]\d|2[0-3]):[0-5]\d$/.test(time);const officialsNum=Number(officials);const issues:string[]=[];if(!sportExists)issues.push('Unknown sport');if(!level)issues.push('Missing level');if(!home)issues.push('Missing home team');if(!away)issues.push('Missing away team');if(!dateOk)issues.push('Date must be YYYY-MM-DD');if(!timeOk)issues.push('Time must be HH:MM');if(!Number.isInteger(officialsNum)||officialsNum<1||officialsNum>20)issues.push('Officials needed must be 1-20');return{row:index+2,sport,level,home_team:home,away_team:away,date,time,venue:get('venue'),city:get('city'),state:get('state'),officials_needed:officials,notes:get('notes'),valid:issues.length===0,issue:issues.join('; ')}})}
 async function handleFile(e:ChangeEvent<HTMLInputElement>){setError('');setImportMessage('');setImportRows([]);const file=e.target.files?.[0];if(!file)return;try{const text=await file.text();setImportRows(validateImport(parseCSV(text)))}catch(err){setError(err instanceof Error?err.message:'Unable to read CSV file')}finally{e.target.value=''}}
 function downloadTemplate(){const csv='sport,level,home_team,away_team,date,time,venue,city,state,officials_needed,notes\nSoccer,Varsity,Ankeny,Johnston,2026-09-01,19:00,Ankeny Stadium,Ankeny,IA,3,Conference game\n';const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='refassign-game-import-template.csv';a.click();URL.revokeObjectURL(url)}
 async function importGames(){const valid=importRows.filter(r=>r.valid);if(!valid.length)return;setImporting(true);setError('');setImportMessage('');let added=0,skipped=0;try{for(const r of valid){const sport=sports.find(s=>s.name.toLowerCase()===r.sport.toLowerCase());if(!sport)continue;const home=await findOrCreateTeam(r.home_team,sport.id,r.level);const away=await findOrCreateTeam(r.away_team,sport.id,r.level);const venue=await findOrCreateVenue(r.venue,r.city,r.state);const starts=new Date(`${r.date}T${r.time}:00`).toISOString();const {data:existing,error:checkError}=await supabase.from('games').select('id').eq('sport_id',sport.id).eq('home_team_id',home).eq('away_team_id',away).eq('starts_at',starts).maybeSingle();if(checkError)throw checkError;if(existing){skipped++;continue}const {error}=await supabase.from('games').insert({sport_id:sport.id,home_team_id:home,away_team_id:away,venue_id:venue,starts_at:starts,level:r.level,officials_needed:Number(r.officials_needed),notes:r.notes||null,status:'open'});if(error)throw error;added++}setImportMessage(`Import complete: ${added} game${added===1?'':'s'} added${skipped?`, ${skipped} duplicate${skipped===1?'':'s'} skipped`:''}.`);setImportRows([]);await load()}catch(err){setError(err instanceof Error?err.message:'Import failed')}finally{setImporting(false)}}
 const visible=filter==='All'?games:games.filter(g=>g.sports?.name===filter);const invalidCount=importRows.filter(r=>!r.valid).length
 return <section className="card"><div className="cardHead"><div><h2>Live Game Schedule</h2><p>{games.length} games in Supabase</p></div><div className="headerActions"><button className="secondary" onClick={()=>{setShowImport(v=>!v);setShow(false)}}>{showImport?'Close Import':'Import CSV'}</button><button className="primary" onClick={()=>{setShow(v=>!v);setShowImport(false)}}>{show?'Cancel':'+ Add Game'}</button></div></div><div className="toolbar"><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{sports.map(s=><option key={s.id}>{s.name}</option>)}</select></div>
 {showImport&&<div className="importPanel"><div className="cardHead"><div><h3>Bulk Schedule Import</h3><p>Upload a CSV using the RefAssign column format. Rows are previewed and validated before import.</p></div><button className="secondary" onClick={downloadTemplate}>Download CSV Template</button></div><input type="file" accept=".csv,text/csv" onChange={handleFile}/>{importRows.length>0&&<><p>{importRows.length} rows found • {invalidCount?`${invalidCount} need attention`:'all rows valid'}</p><div className="tableWrap"><table><thead><tr><th>Row</th><th>Date/Time</th><th>Game</th><th>Sport</th><th>Venue</th><th>Officials</th><th>Validation</th></tr></thead><tbody>{importRows.map(r=><tr key={r.row}><td>{r.row}</td><td>{r.date}<small>{r.time}</small></td><td><b>{r.home_team} vs {r.away_team}</b><small>{r.level}</small></td><td>{r.sport}</td><td>{r.venue||'TBD'}<small>{[r.city,r.state].filter(Boolean).join(', ')}</small></td><td>{r.officials_needed}</td><td><span className={`badge ${r.valid?'green':'red'}`}>{r.valid?'Ready':r.issue}</span></td></tr>)}</tbody></table></div><div className="formActions"><button className="primary" disabled={importing||invalidCount>0} onClick={importGames}>{importing?'Importing…':`Import ${importRows.length} Games`}</button></div></>}</div>}
 {show&&<form className="officialForm" onSubmit={save}><label>Sport<select required value={form.sport_id} onChange={e=>chooseSport(e.target.value)}><option value="">Select sport</option>{sports.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Level<input required value={form.level} onChange={e=>setForm({...form,level:e.target.value})}/></label><label>Home team<input required value={form.home_name} onChange={e=>setForm({...form,home_name:e.target.value})}/></label><label>Away team<input required value={form.away_name} onChange={e=>setForm({...form,away_name:e.target.value})}/></label><label>Date<input type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Time<input type="time" required value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label><label>Venue<input value={form.venue_name} onChange={e=>setForm({...form,venue_name:e.target.value})}/></label><label>Venue city<input value={form.venue_city} onChange={e=>setForm({...form,venue_city:e.target.value})}/></label><label>State<input value={form.venue_state} onChange={e=>setForm({...form,venue_state:e.target.value})}/></label><label>Officials needed<input type="number" min="1" max="20" required value={form.officials_needed} onChange={e=>setForm({...form,officials_needed:Number(e.target.value)})}/></label><label>Notes<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="formActions"><button type="button" className="secondary" onClick={()=>setShow(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save Game'}</button></div></form>}
 {error&&<div className="errorBox">{error}</div>}{importMessage&&<div className="loginMessage">{importMessage}</div>}{loading?<p>Loading games…</p>:visible.length===0?<div className="emptyState"><h3>No games yet</h3><p>Add your first live game to start scheduling officials.</p></div>:<div className="tableWrap"><table><thead><tr><th>Date</th><th>Game</th><th>Sport</th><th>Location</th><th>Officials</th><th>Status</th></tr></thead><tbody>{visible.map(g=>{const d=new Date(g.starts_at);return <tr key={g.id}><td>{d.toLocaleDateString()}<small>{d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></td><td><b>{g.home?.name||'TBD'} vs {g.away?.name||'TBD'}</b><small>{g.level||''}</small></td><td>{g.sports?.name||'—'}</td><td>{g.venue?.name||'TBD'}<small>{[g.venue?.city,g.venue?.state].filter(Boolean).join(', ')}</small></td><td>0/{g.officials_needed}</td><td><span className="badge red">{g.status==='open'?'Needs officials':g.status}</span></td></tr>})}</tbody></table></div>}</section>
}
