'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {createClient} from '../lib/supabase/client'
import TeamsRosterManager from './TeamsRosterManager'

type Sport={id:string;name:string}
type Level={id:string;name:string}
type League={id:string;name:string}
type Team={id:string;name:string;sport_id:string|null;level_id:string|null;level:string|null}
type Location={id:string;name:string;address:string|null;city:string|null;state:string|null}
type View='Leagues'|'Levels'|'Teams'|'Locations'

export default function GameSetup({view}:{view:View}){
 const supabase=useMemo(()=>createClient(),[])
 const [allowed,setAllowed]=useState(false),[sports,setSports]=useState<Sport[]>([]),[levels,setLevels]=useState<Level[]>([]),[leagues,setLeagues]=useState<League[]>([]),[teams,setTeams]=useState<Team[]>([]),[locations,setLocations]=useState<Location[]>([])
 const [levelName,setLevelName]=useState(''),[leagueName,setLeagueName]=useState(''),[team,setTeam]=useState({name:'',sport_id:'',level_id:''}),[location,setLocation]=useState({name:'',address:'',city:'',state:'IA'})
 const [editingTeamId,setEditingTeamId]=useState<string|null>(null),[editingLocationId,setEditingLocationId]=useState<string|null>(null),[showTeamImport,setShowTeamImport]=useState(false),[error,setError]=useState('')
 async function load(){setError('');const {data:u}=await supabase.auth.getUser();if(!u.user)return;const {data:p}=await supabase.from('profiles').select('role').eq('id',u.user.id).maybeSingle();const ok=['admin','assignor'].includes(p?.role||'');setAllowed(ok);if(!ok)return;const [s,l,lg,t,loc]=await Promise.all([supabase.from('sports').select('id,name').eq('active',true).order('name'),supabase.from('levels').select('id,name').eq('active',true).order('name'),supabase.from('leagues').select('id,name').eq('active',true).order('name'),supabase.from('teams').select('id,name,sport_id,level_id,level').order('name'),supabase.from('locations').select('id,name,address,city,state').eq('active',true).order('name')]);const err=s.error||l.error||lg.error||t.error||loc.error;if(err)setError(err.message);else{setSports(s.data||[]);setLevels(l.data||[]);setLeagues(lg.data||[]);setTeams(t.data||[]);setLocations((loc.data||[]) as Location[])}}
 useEffect(()=>{load()},[])
 async function addLevel(e:FormEvent){e.preventDefault();const r=await supabase.from('levels').insert({name:levelName.trim()});if(r.error)setError(r.error.message);else{setLevelName('');load()}}
 async function addLeague(e:FormEvent){e.preventDefault();const r=await supabase.from('leagues').insert({name:leagueName.trim()});if(r.error)setError(r.error.message);else{setLeagueName('');load()}}
 async function saveTeam(e:FormEvent){e.preventDefault();const level=levels.find(l=>l.id===team.level_id);const payload={name:team.name.trim(),sport_id:team.sport_id,level_id:team.level_id,level:level?.name||null};const r=editingTeamId?await supabase.from('teams').update(payload).eq('id',editingTeamId):await supabase.from('teams').insert(payload);if(r.error)setError(r.error.message);else{setTeam({name:'',sport_id:'',level_id:''});setEditingTeamId(null);load()}}
 function editTeam(t:Team){setEditingTeamId(t.id);setTeam({name:t.name,sport_id:t.sport_id||'',level_id:t.level_id||''})}
 async function saveLocation(e:FormEvent){e.preventDefault();const payload={name:location.name.trim(),level_id:null,address:location.address.trim()||null,city:location.city.trim()||null,state:location.state.trim()||null};const r=editingLocationId?await supabase.from('locations').update(payload).eq('id',editingLocationId):await supabase.from('locations').insert(payload);if(r.error)setError(r.error.message);else{setLocation({name:'',address:'',city:'',state:'IA'});setEditingLocationId(null);load()}}
 function editLocation(v:Location){setEditingLocationId(v.id);setLocation({name:v.name,address:v.address||'',city:v.city||'',state:v.state||''})}
 async function remove(table:'levels'|'leagues'|'teams'|'locations',id:string){if(!confirm('Remove this setup option? Existing records may prevent deletion.'))return;const r=await supabase.from(table).delete().eq('id',id);if(r.error)setError(r.error.message);else load()}
 if(!allowed)return <section className="card"><h2>{view}</h2><p>Only Administrators and Assignors can manage Game Setup.</p></section>
 return <>{error&&<div className="errorBox">{error}</div>}
 {view==='Leagues'&&<section className="card"><h2>Leagues</h2><p>Create and manage the leagues available for games and official eligibility.</p><form className="toolbar" onSubmit={addLeague}><input required placeholder="Example: Iowa Soccer League" value={leagueName} onChange={e=>setLeagueName(e.target.value)}/><button className="primary">Add League</button></form><div className="tableWrap"><table><tbody>{leagues.map(l=><tr key={l.id}><td><b>{l.name}</b></td><td><button className="tableButton" onClick={()=>remove('leagues',l.id)}>Remove</button></td></tr>)}</tbody></table></div></section>}
 {view==='Levels'&&<section className="card"><h2>Levels</h2><p>Create and manage the competition levels used by teams, games, and official eligibility.</p><form className="toolbar" onSubmit={addLevel}><input required placeholder="Example: U19" value={levelName} onChange={e=>setLevelName(e.target.value)}/><button className="primary">Add Level</button></form><div className="tableWrap"><table><tbody>{levels.map(l=><tr key={l.id}><td><b>{l.name}</b></td><td><button className="tableButton" onClick={()=>remove('levels',l.id)}>Remove</button></td></tr>)}</tbody></table></div></section>}
 {view==='Teams'&&<section className="card"><div className="cardHead"><div><h2>Teams</h2><p>Manage Home and Away team choices, or bulk update them with the uploader.</p></div><button className="secondary" onClick={()=>setShowTeamImport(!showTeamImport)}>{showTeamImport?'Close Team Uploader':'Team Import / Export'}</button></div>{showTeamImport&&<TeamsRosterManager/>}<form className="officialForm" onSubmit={saveTeam}><label>Team Name<input required value={team.name} onChange={e=>setTeam({...team,name:e.target.value})}/></label><label>Sport<select required value={team.sport_id} onChange={e=>setTeam({...team,sport_id:e.target.value})}><option value="">Select sport</option>{sports.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Level<select required value={team.level_id} onChange={e=>setTeam({...team,level_id:e.target.value})}><option value="">Select level</option>{levels.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><div className="formActions">{editingTeamId&&<button type="button" className="secondary" onClick={()=>{setEditingTeamId(null);setTeam({name:'',sport_id:'',level_id:''})}}>Cancel Edit</button>}<button className="primary">{editingTeamId?'Save Team Changes':'Add Team'}</button></div></form><div className="tableWrap"><table><thead><tr><th>Team</th><th>Sport</th><th>Level</th><th></th></tr></thead><tbody>{teams.map(t=><tr key={t.id}><td>{t.name}</td><td>{sports.find(s=>s.id===t.sport_id)?.name||'—'}</td><td>{levels.find(l=>l.id===t.level_id)?.name||t.level||'—'}</td><td><button className="tableButton" onClick={()=>editTeam(t)}>Edit</button> <button className="tableButton" onClick={()=>remove('teams',t.id)}>Remove</button></td></tr>)}</tbody></table></div></section>}
 {view==='Locations'&&<section className="card"><h2>Locations</h2><p>Manage game locations independently of Level.</p><form className="officialForm" onSubmit={saveLocation}><label>Location Name<input required value={location.name} onChange={e=>setLocation({...location,name:e.target.value})}/></label><label>Address<input value={location.address} onChange={e=>setLocation({...location,address:e.target.value})}/></label><label>City<input value={location.city} onChange={e=>setLocation({...location,city:e.target.value})}/></label><label>State<input value={location.state} onChange={e=>setLocation({...location,state:e.target.value})}/></label><div className="formActions">{editingLocationId&&<button type="button" className="secondary" onClick={()=>{setEditingLocationId(null);setLocation({name:'',address:'',city:'',state:'IA'})}}>Cancel Edit</button>}<button className="primary">{editingLocationId?'Save Location Changes':'Add Location'}</button></div></form><div className="tableWrap"><table><thead><tr><th>Location</th><th>Address</th><th></th></tr></thead><tbody>{locations.map(v=><tr key={v.id}><td>{v.name}</td><td>{[v.address,v.city,v.state].filter(Boolean).join(', ')}</td><td><button className="tableButton" onClick={()=>editLocation(v)}>Edit</button> <button className="tableButton" onClick={()=>remove('locations',v.id)}>Remove</button></td></tr>)}</tbody></table></div></section>}
 </>}
