'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {createClient} from '../lib/supabase/client'
type Sport={id:string;name:string};type Level={id:string;name:string};type Team={id:string;name:string;sport_id:string|null;level_id:string|null;level:string|null};type Venue={id:string;name:string;address:string|null;city:string|null;state:string|null}
export default function GameSetup(){const supabase=useMemo(()=>createClient(),[]);const [allowed,setAllowed]=useState(false);const [sports,setSports]=useState<Sport[]>([]);const [levels,setLevels]=useState<Level[]>([]);const [teams,setTeams]=useState<Team[]>([]);const [venues,setVenues]=useState<Venue[]>([]);const [levelName,setLevelName]=useState('');const [team,setTeam]=useState({name:'',sport_id:'',level_id:''});const [venue,setVenue]=useState({name:'',address:'',city:'',state:'IA'});const [error,setError]=useState('')
async function load(){setError('');const {data:u}=await supabase.auth.getUser();if(!u.user)return;const {data:p}=await supabase.from('profiles').select('role').eq('id',u.user.id).maybeSingle();const ok=['admin','assignor'].includes(p?.role||'');setAllowed(ok);if(!ok)return;const [s,l,t,v]=await Promise.all([supabase.from('sports').select('id,name').eq('active',true).order('name'),supabase.from('levels').select('id,name').eq('active',true).order('name'),supabase.from('teams').select('id,name,sport_id,level_id,level').order('name'),supabase.from('venues').select('id,name,address,city,state').order('name')]);if(s.error||l.error||t.error||v.error)setError((s.error||l.error||t.error||v.error)?.message||'Unable to load setup');else{setSports(s.data||[]);setLevels(l.data||[]);setTeams(t.data||[]);setVenues(v.data||[])}}
useEffect(()=>{load()},[])
async function addLevel(e:FormEvent){e.preventDefault();const {error}=await supabase.from('levels').insert({name:levelName.trim()});if(error)setError(error.message);else{setLevelName('');load()}}
async function addTeam(e:FormEvent){e.preventDefault();const level=levels.find(l=>l.id===team.level_id);const {error}=await supabase.from('teams').insert({name:team.name.trim(),sport_id:team.sport_id,level_id:team.level_id,level:level?.name||null});if(error)setError(error.message);else{setTeam({name:'',sport_id:'',level_id:''});load()}}
async function addVenue(e:FormEvent){e.preventDefault();const {error}=await supabase.from('venues').insert({name:venue.name.trim(),address:venue.address.trim()||null,city:venue.city.trim()||null,state:venue.state.trim()||null});if(error)setError(error.message);else{setVenue({name:'',address:'',city:'',state:'IA'});load()}}
async function remove(table:'levels'|'teams'|'venues',id:string){if(!confirm('Remove this setup option? Existing games may prevent deletion.'))return;const {error}=await supabase.from(table).delete().eq('id',id);if(error)setError(error.message);else load()}
if(!allowed)return <section className="card"><h2>Game Setup</h2><p>Only Administrators and Assignors can manage levels, teams and venues.</p></section>
return <><section className="card"><h2>Game Setup</h2><p>Create the approved choices used by game entry and schedule imports. Games cannot use free-text levels, teams, or venues.</p>{error&&<div className="errorBox">{error}</div>}</section><section className="card"><h3>Levels</h3><form className="toolbar" onSubmit={addLevel}><input required placeholder="Example: U19" value={levelName} onChange={e=>setLevelName(e.target.value)}/><button className="primary">Add Level</button></form><div className="tableWrap"><table><tbody>{levels.map(l=><tr key={l.id}><td><b>{l.name}</b></td><td><button className="tableButton" onClick={()=>remove('levels',l.id)}>Remove</button></td></tr>)}</tbody></table></div></section><section className="card"><h3>Teams / Locations</h3><form className="officialForm" onSubmit={addTeam}><label>Name<input required value={team.name} onChange={e=>setTeam({...team,name:e.target.value})}/></label><label>Sport<select required value={team.sport_id} onChange={e=>setTeam({...team,sport_id:e.target.value})}><option value="">Select sport</option>{sports.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Level<select required value={team.level_id} onChange={e=>setTeam({...team,level_id:e.target.value})}><option value="">Select level</option>{levels.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><button className="primary">Add Team</button></form><div className="tableWrap"><table><thead><tr><th>Team</th><th>Sport</th><th>Level</th><th></th></tr></thead><tbody>{teams.map(t=><tr key={t.id}><td>{t.name}</td><td>{sports.find(s=>s.id===t.sport_id)?.name||'—'}</td><td>{levels.find(l=>l.id===t.level_id)?.name||t.level||'—'}</td><td><button className="tableButton" onClick={()=>remove('teams',t.id)}>Remove</button></td></tr>)}</tbody></table></div></section><section className="card"><h3>Venues</h3><form className="officialForm" onSubmit={addVenue}><label>Venue name<input required value={venue.name} onChange={e=>setVenue({...venue,name:e.target.value})}/></label><label>Address<input value={venue.address} onChange={e=>setVenue({...venue,address:e.target.value})}/></label><label>City<input value={venue.city} onChange={e=>setVenue({...venue,city:e.target.value})}/></label><label>State<input value={venue.state} onChange={e=>setVenue({...venue,state:e.target.value})}/></label><button className="primary">Add Venue</button></form><div className="tableWrap"><table><thead><tr><th>Venue</th><th>Location</th><th></th></tr></thead><tbody>{venues.map(v=><tr key={v.id}><td>{v.name}</td><td>{[v.address,v.city,v.state].filter(Boolean).join(', ')}</td><td><button className="tableButton" onClick={()=>remove('venues',v.id)}>Remove</button></td></tr>)}</tbody></table></div></section></>}
