"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {createClient} from "../lib/supabase/client";
type Official={id:string;first_name:string;last_name:string;email:string|null};type Member={official_id:string};type Module={id:string;title:string;category:string;active:boolean};type StoredFile={name:string;id:string|null;created_at:string|null;metadata?:{size?:number}|null};
export default function IowaSoccerDevelopmentAdmin(){const supabase=useMemo(()=>createClient(),[]),[programId,setProgramId]=useState(""),[officials,setOfficials]=useState<Official[]>([]),[members,setMembers]=useState<Member[]>([]),[modules,setModules]=useState<Module[]>([]),[files,setFiles]=useState<StoredFile[]>([]),[selectedOfficial,setSelectedOfficial]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function loadFiles(){const{data,error:e}=await supabase.storage.from("iowa-training-materials").list("materials",{limit:100,sortBy:{column:"name",order:"asc"}});if(e)setError(e.message);else setFiles((data||[]) as StoredFile[])}
 async function load(){setError("");const{data:program,error:pe}=await supabase.from("registration_programs").select("id").eq("slug","iowa-soccer").single();if(pe)return setError(pe.message);setProgramId(program.id);const[o,m,t]=await Promise.all([supabase.rpc("list_development_program_officials",{p_program_id:program.id}),supabase.from("registration_program_officials").select("official_id").eq("program_id",program.id),supabase.from("development_modules").select("id,title,category,active").eq("program_id",program.id).order("sort_order")]);const e=o.error||m.error||t.error;if(e)return setError(e.message);setOfficials((o.data||[]) as Official[]);setMembers((m.data||[]) as Member[]);setModules((t.data||[]) as Module[]);await loadFiles()}useEffect(()=>{void load()},[]);
 async function addOfficial(){if(!selectedOfficial||!programId)return;setBusy(true);setError("");setNotice("");const{data:{user}}=await supabase.auth.getUser();const{error:e}=await supabase.from("registration_program_officials").insert({program_id:programId,official_id:selectedOfficial,source:"registrar",added_by:user?.id||null});if(e)setError(e.message);else{setNotice("Official added to Iowa Soccer Development.");setSelectedOfficial("");await load()}setBusy(false)}
 async function removeOfficial(id:string){if(!window.confirm("Remove this official's Iowa Soccer Development access?"))return;const{error:e}=await supabase.from("registration_program_officials").delete().eq("program_id",programId).eq("official_id",id);if(e)setError(e.message);else await load()}
 async function addModule(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const{data:{user}}=await supabase.auth.getUser();const{error:e}=await supabase.from("development_modules").insert({program_id:programId,title:form.get("title"),category:form.get("category")||"Training",description:form.get("description")||"",resource_url:form.get("resource_url")||null,required:form.get("required")==="on",sort_order:modules.length*10+10,created_by:user?.id||null});if(e)setError(e.message);else{setNotice("Training module added.");event.currentTarget.reset();await load()}setBusy(false)}
 async function uploadMaterial(event:FormEvent<HTMLFormElement>){event.preventDefault();const input=event.currentTarget.elements.namedItem("material") as HTMLInputElement,file=input.files?.[0];if(!file)return;setBusy(true);setError("");setNotice("");const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-");const path=`materials/${Date.now()}-${safe}`;const{error:e}=await supabase.storage.from("iowa-training-materials").upload(path,file,{upsert:false});if(e)setError(e.message);else{setNotice(`${file.name} uploaded to the Training Materials Library.`);event.currentTarget.reset();await loadFiles()}setBusy(false)}
 async function deleteMaterial(name:string){if(!window.confirm("Delete this training material?"))return;const{error:e}=await supabase.storage.from("iowa-training-materials").remove([`materials/${name}`]);if(e)setError(e.message);else await loadFiles()}
 async function postAnnouncement(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const{data:{user}}=await supabase.auth.getUser();const{error:e}=await supabase.from("development_announcements").insert({program_id:programId,title:form.get("title"),message:form.get("message"),created_by:user?.id||null});if(e)setError(e.message);else{setNotice("Program announcement posted.");event.currentTarget.reset()}setBusy(false)}
 const memberIds=new Set(members.map(m=>m.official_id)),available=officials.filter(o=>!memberIds.has(o.id));function fileUrl(name:string){return supabase.storage.from("iowa-training-materials").getPublicUrl(`materials/${name}`).data.publicUrl}
 return <><section className="card"><div className="cardHead"><div><h2>Iowa Soccer Development Administration</h2><p>Add participating officials and manage their training experience.</p></div></div>{error&&<div className="errorBox">{error}</div>}{notice&&<div className="loginMessage">{notice}</div>}<div className="toolbar"><label>Add Existing Official<select value={selectedOfficial} onChange={e=>setSelectedOfficial(e.target.value)}><option value="">Select an official</option>{available.map(o=><option value={o.id} key={o.id}>{o.last_name}, {o.first_name}</option>)}</select></label><button className="primary" disabled={busy||!selectedOfficial} onClick={()=>void addOfficial()}>Add to Program</button></div><div className="developmentRoster">{officials.filter(o=>memberIds.has(o.id)).map(o=><div key={o.id}><span><b>{o.first_name} {o.last_name}</b><small>{o.email}</small></span><button className="secondary" onClick={()=>void removeOfficial(o.id)}>Remove Access</button></div>)}</div></section>
 <section className="card"><h2>Training Content</h2><form className="officialForm" onSubmit={addModule}><label>Module Title<input name="title" required/></label><label>Category<input name="category" placeholder="Laws of the Game, Positioning, Communication"/></label><label className="fullSpan">Description<textarea name="description" required/></label><label className="fullSpan">Resource Link<input name="resource_url" type="url" placeholder="Paste a link from the Materials Library or another training resource"/></label><label><input name="required" type="checkbox"/> Required Training</label><button className="primary" disabled={busy}>Add Training Module</button></form><div className="developmentRoster">{modules.map(m=><div key={m.id}><span><b>{m.title}</b><small>{m.category}</small></span><span className={`badge ${m.active?"green":"yellow"}`}>{m.active?"Active":"Hidden"}</span></div>)}</div></section>
 <section className="card"><div className="trainingSectionHead"><div><h2>Training Materials Library</h2><p>Upload and store PDFs, videos, presentations, documents, and images for Iowa Soccer training.</p></div></div><form className="trainingAdminUpload" onSubmit={uploadMaterial}><label className="fullSpan">Choose Material<input name="material" type="file" required accept=".pdf,.mp4,.webm,.png,.jpg,.jpeg,.webp,.pptx,.docx"/></label><button className="primary" disabled={busy}>Upload Material</button><small>Maximum file size: 50 MB.</small></form><div className="trainingAdminFiles">{files.length?files.map(f=><div key={f.name}><span><b>{f.name.replace(/^\d+-/,"")}</b><small>{f.metadata?.size?` • ${(f.metadata.size/1024/1024).toFixed(1)} MB`:""}</small></span><span><a className="secondary" href={fileUrl(f.name)} target="_blank" rel="noreferrer">Open</a> <button className="secondary" onClick={()=>void deleteMaterial(f.name)}>Delete</button></span></div>):<p>No materials uploaded yet.</p>}</div></section>
 <section className="card"><h2>Post Program Update</h2><form className="officialForm" onSubmit={postAnnouncement}><label>Title<input name="title" required/></label><label className="fullSpan">Message<textarea name="message" required/></label><button className="primary" disabled={busy}>Post Announcement</button></form></section></>}
