"use client";
import {useEffect,useMemo,useState} from "react";
import {IOWA_ENTRY_RULES_PASS_PERCENT,iowaEntryRulesQuestions} from "../lib/iowaEntryRulesQuiz";

type ScoreResult={correctCount:number;totalQuestions:number;scorePercent:number;passed:boolean;passPercent:number;results:{id:string;selected:string;correct:string;isCorrect:boolean;explanation:string}[]};
type SavedPass={passed:true;correctCount:number;totalQuestions:number;scorePercent:number;completedAt:string};
export default function IowaRulesQuiz({moduleId,onClose,onPassed}:{moduleId:string;onClose:()=>void;onPassed:(completedAt:string)=>void}){const[step,setStep]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[score,setScore]=useState<ScoreResult|null>(null),[savedPass,setSavedPass]=useState<SavedPass|null>(null),[checkingResult,setCheckingResult]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),question=iowaEntryRulesQuestions[step],answered=Object.keys(answers).length,allAnswered=answered===iowaEntryRulesQuestions.length,resultMap=useMemo(()=>new Map(score?.results.map(result=>[result.id,result])||[]),[score]);
 useEffect(()=>{let active=true;void(async()=>{try{const response=await fetch(`/api/training/rules-quiz?moduleId=${encodeURIComponent(moduleId)}`,{cache:"no-store",credentials:"same-origin"}),data=await response.json().catch(()=>({})) as SavedPass&{error?:string};if(active&&response.ok&&data.passed)setSavedPass(data)}catch{}finally{if(active)setCheckingResult(false)}})();return()=>{active=false}},[moduleId]);
 async function submit(){
  if(!allAnswered)return setError("Please answer all 25 questions before submitting.");
  setBusy(true);setError("");
  try{
   const response=await fetch("/api/training/rules-quiz",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({moduleId,answers})}),data=await response.json().catch(()=>({})) as ScoreResult&{error?:string};
   if(!response.ok){setError(data.error||"The test could not be scored. Your answers are still saved on this page; please try again.");return}
   setScore(data);if(data.passed)onPassed(new Date().toISOString());window.scrollTo({top:0,behavior:"smooth"});
  }catch{
   setError("We could not connect to RefAssign to score your test. Your answers are still saved on this page. Check your connection, then select Submit Test again.");
  }finally{setBusy(false)}
 }
 function restart(){setAnswers({});setScore(null);setStep(0);setError("")}
 if(checkingResult)return <section className="rulesQuiz" aria-label="Entry-Level Soccer Rules Test"><p>Checking your saved test result…</p></section>;
 if(savedPass&&!score)return <section className="rulesQuiz" aria-label="Entry-Level Soccer Rules Test results"><div className="quizScore passed"><span>✓</span><div><h2>You Passed!</h2><p><b>{savedPass.correctCount} of {savedPass.totalQuestions} correct · {savedPass.scorePercent}%</b></p><p>Your test is complete and has been added to your training progress.</p></div></div><div className="quizFooter"><button className="secondary" onClick={onClose}>Return to Training</button></div></section>;
 if(score)return <section className="rulesQuiz" aria-label="Entry-Level Soccer Rules Test results"><div className={`quizScore ${score.passed?"passed":"retry"}`}><span>{score.passed?"✓":"↻"}</span><div><h2>{score.passed?"You Passed!":"Keep Learning — Try Again"}</h2><p><b>{score.correctCount} of {score.totalQuestions} correct · {score.scorePercent}%</b></p><p>{score.passed?"Your test is complete and has been added to your training record.":`A score of ${score.passPercent}% (${Math.ceil(score.totalQuestions*score.passPercent/100)} correct) is needed to pass.`}</p></div></div><div className="quizReview"><h3>Answer Review</h3>{iowaEntryRulesQuestions.map((item,index)=>{const result=resultMap.get(item.id),selected=item.options.find(option=>option.value===result?.selected),correct=item.options.find(option=>option.value===result?.correct);return <article className={result?.isCorrect?"correct":"incorrect"} key={item.id}><div className="quizReviewTitle"><b>{index+1}. {item.question}</b><span>{result?.isCorrect?"✓ Correct":"✕ Review"}</span></div><p>Your answer: {selected?.label}</p>{!result?.isCorrect&&<p><b>Correct answer: {correct?.label}</b></p>}<small>{result?.explanation}</small></article>})}</div><div className="quizFooter"><button className="secondary" onClick={onClose}>Return to Training</button><button className="primary" onClick={restart}>Take Test Again</button></div></section>;
 return <section className="rulesQuiz" aria-label="Entry-Level Soccer Rules Test"><div className="quizHeader"><div><span className="quizEyebrow">REQUIRED TRAINING</span><h2>Entry-Level Soccer Rules Test</h2><p>Choose the best answer for each question. You need {IOWA_ENTRY_RULES_PASS_PERCENT}% to pass, and you may retake the test.</p></div><button className="quizClose" aria-label="Close test" onClick={onClose}>×</button></div><div className="quizProgress"><div><i style={{width:`${answered/iowaEntryRulesQuestions.length*100}%`}}/></div><span>{answered} of {iowaEntryRulesQuestions.length} answered</span></div><article className="quizQuestion"><span>Question {step+1} of {iowaEntryRulesQuestions.length}</span><h3>{question.question}</h3><details><summary>Need a hint?</summary><p>{question.hint}</p></details><div className="quizOptions">{question.options.map(option=><label className={answers[question.id]===option.value?"selected":""} key={option.value}><input type="radio" name={question.id} value={option.value} checked={answers[question.id]===option.value} onChange={()=>setAnswers(old=>({...old,[question.id]:option.value}))}/><b>{option.value}</b><span>{option.label}</span></label>)}</div></article>{error&&<div className="errorBox">{error}</div>}<div className="quizFooter"><button className="secondary" disabled={step===0} onClick={()=>setStep(old=>old-1)}>Previous</button><span>{iowaEntryRulesQuestions.map((item,index)=><button aria-label={`Go to question ${index+1}`} className={`${index===step?"current":""} ${answers[item.id]?"answered":""}`} key={item.id} onClick={()=>setStep(index)}>{index+1}</button>)}</span>{step<iowaEntryRulesQuestions.length-1?<button className="primary" onClick={()=>setStep(old=>old+1)}>Next</button>:<button className="primary" disabled={!allAnswered||busy} onClick={()=>void submit()}>{busy?"Scoring…":"Submit Test"}</button>}</div></section>}
