"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {createClient} from "../lib/supabase/client";
type Module={id:string;title:string;description:string;category:string;resource_url:string|null;required:boolean;sort_order:number};
type Progress={module_id:string;status:string};type Announcement={id:string;title:string;message:string;published_at:string};
type MentorRequest={id:string;game_id:string|null;request_details:string|null;status:string;response:string|null;requested_at:string;responded_at:string|null};
type Question={id:string;question:string;status:string;response:string|null;responder_name:string|null;asked_at:string;responded_at:string|null};
type GameAssignment={game_id:string;game_number:string|null;game_status:string;starts_at:string;duration_minutes:number;home_team:string|null;away_team:string|null;location_name:string|null;location_city:string|null;location_state:string|null;league_name:string|null;level_name:string|null;status:string};
export default function IowaSoccerDevelopment(){const supabase=useMemo(()=>createClient(),[]),[officialId,setOfficialId]=useState(""),[programId,setProgramId]=useState(""),[modules,setModules]=useState<Module[]>([]),[progress,setProgress]=useState<Record<string,string>>({}),[announcements,setAnnouncements]=useState<Announcement[]>([]),[requests,setRequests]=useState<MentorRequest[]>([]),[questions,setQuestions]=useState<Question[]>([]),[games,setGames]=useState<GameAssignment[]>([]),[showQuestion,setShowQuestion]=useState(false),[showMentorRequest,setShowMentorRequest]=useState(false),[selectedGame,setSelectedGame]=useState(""),[mentorDetails,setMentorDetails]=useState(""),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){setError("");const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:official,error:officialError}=await supabase.from("officials").select("id").eq("auth_user_id",user.id).maybeSingle();if(officialError||!official)return setError("Your official account is not connected to the Iowa Soccer development program.");setOfficialId(official.id);const{data:program,error:programError}=await supabase.from("registration_programs").select("id").eq("slug","iowa-soccer").single();if(programError)return setError(programError.message);setProgramId(program.id);const[m,p,a,r,q,g]=await Promise.all([supabase.from("development_modules").select("id,title,description,category,resource_url,required,sort_order").eq("program_id",program.id).eq("active",true).order("sort_order"),supabase.from("official_development_progress").select("module_id,status").eq("official_id",official.id),supabase.from("development_announcements").select("id,title,message,published_at").eq("program_id",program.id).eq("active",true).order("published_at",{ascending:false}),supabase.from("development_mentor_requests").select("id,game_id,request_details,status,response,requested_at,responded_at").eq("official_id",official.id).order("requested_at",{ascending:false}),supabase.from("development_questions").select("id,question,status,response,responder_name,asked_at,responded_at").eq("official_id",official.id).order("asked_at",{ascending:false}),supabase.rpc("my_official_assignments")]);const e=m.error||p.error||a.error||r.error||q.error||g.error;if(e)return setError(e.message);setModules((m.data||[]) as Module[]);const map:Record<string,string>={};for(const row of (p.data||[]) as Progress[])map[row.module_id]=row.status;setProgress(map);setAnnouncements((a.data||[]) as Announcement[]);setRequests((r.data||[]) as MentorRequest[]);setQuestions((q.data||[]) as Question[]);const unique=new Map<string,GameAssignment>();for(const row of (g.data||[]) as GameAssignment[]){if(new Date(row.starts_at).getTime()>=Date.now()&&["accepted","confirmed"].includes(row.status)&&!["canceled","cancelled","rained_out"].includes(row.game_status))unique.set(row.game_id,row)}setGames([...unique.values()].sort((x,y)=>new Date(x.starts_at).getTime()-new Date(y.starts_at).getTime()))}
 useEffect(()=>{void load()},[]);
 async function setStatus(moduleId:string,status:string){if(!officialId)return;setBusy(moduleId);setError("");const{error:e}=await supabase.from("official_development_progress").upsert({module_id:moduleId,official_id:officialId,status,completed_at:status==="completed"?new Date().toISOString():null,updated_at:new Date().toISOString()});if(e)setError(e.message);else setProgress(old=>({...old,[moduleId]:status}));setBusy("")}
 async function requestMentor(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!officialId||!programId||!selectedGame)return;setBusy("mentor");setError("");setNotice("");const{error:e}=await supabase.from("development_mentor_requests").insert({program_id:programId,official_id:officialId,game_id:selectedGame,request_details:mentorDetails.trim()||null});if(e)setError(e.code==="23505"?"You already have a pending mentor request for this game.":e.message);else{setSelectedGame("");setMentorDetails("");setShowMentorRequest(false);setNotice("Your game-specific mentor request was sent to all Iowa Soccer mentors.");await load()}setBusy("")}
 async function askQuestion(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement);setBusy("question");setError("");setNotice("");try{const{error:e}=await supabase.from("development_questions").insert({program_id:programId,official_id:officialId,question:String(form.get("question")||"")});if(e)setError(e.message);else{formElement.reset();setShowQuestion(false);setNotice("Your question was sent to the mentors.");await load()}}finally{setBusy("")}}
 const complete=modules.filter(module=>progress[module.id]==="completed").length,percent=modules.length?Math.round(complete/modules.length*100):0,pendingGameIds=new Set(requests.filter(request=>request.status==="pending"&&request.game_id).map(request=>request.game_id)),requestableGames=games.filter(game=>!pendingGameIds.has(game.game_id));
 function gameLabel(game:GameAssignment){return `${new Date(game.starts_at).toLocaleString()} — ${game.home_team||"TBD"} vs ${game.away_team||"TBD"} — ${game.location_name||"Location TBD"}`}
 return <><section className="card developmentHero"><div><span className="developmentEyebrow">IOWA SOCCER</span><h2>Official Development</h2><p>Build confidence, strengthen your knowledge, and prepare for successful match assignments.</p><div className="headerActions" style={{marginTop:18}}><button className="primary" disabled={busy==="mentor"} onClick={()=>setShowMentorRequest(value=>!value)}>Request a Mentor</button><button className="secondary" onClick={()=>setShowQuestion(value=>!value)}>Ask a Question</button></div></div><div className="developmentProgress"><strong>{percent}%</strong><span>{complete} of {modules.length} modules complete</span><div><i style={{width:`${percent}%`}}/></div></div></section>
 {error&&<div className="errorBox">{error}</div>}{notice&&<div className="loginMessage">{notice}</div>}
 {showMentorRequest&&<section className="card"><h2>Request a Mentor for a Game</h2><p>Select the game where you would like a mentor present. The complete date, time, teams, and location will be shared with every Iowa Soccer mentor.</p><form className="officialForm" onSubmit={requestMentor}><label className="fullSpan">Game<select required value={selectedGame} onChange={event=>setSelectedGame(event.target.value)}><option value="">Select an accepted upcoming game</option>{requestableGames.map(game=><option key={game.game_id} value={game.game_id}>{gameLabel(game)}</option>)}</select></label>{selectedGame&&(()=>{const game=games.find(item=>item.game_id===selectedGame);return game?<div className="fullSpan mentorGamePreview"><b>{game.home_team||"TBD"} vs {game.away_team||"TBD"}</b><span>{new Date(game.starts_at).toLocaleString()} • {game.duration_minutes||110} minutes</span><span>{game.location_name||"Location TBD"}{game.location_city?` • ${game.location_city}, ${game.location_state||""}`:""}</span><span>{[game.league_name,game.level_name,game.game_number&&`Game ${game.game_number}`].filter(Boolean).join(" • ")}</span></div>:null})()}<label className="fullSpan">What would you like the mentor to focus on?<textarea maxLength={5000} rows={5} value={mentorDetails} onChange={event=>setMentorDetails(event.target.value)} placeholder="Optional: positioning, foul selection, communication, confidence, or another development goal"/></label><div className="formActions"><button type="button" className="secondary" onClick={()=>setShowMentorRequest(false)}>Cancel</button><button className="primary" disabled={busy==="mentor"||!selectedGame}>{busy==="mentor"?"Sending…":"Send Mentor Request"}</button></div></form>{!requestableGames.length&&<p>You do not currently have an accepted upcoming game available for a new mentor request.</p>}</section>}
 {showQuestion&&<section className="card"><h2>Ask a Mentor</h2><form className="officialForm" onSubmit={askQuestion}><label className="fullSpan">Your Question<textarea name="question" required maxLength={5000} rows={4} placeholder="What would you like help with?"/></label><button className="primary" disabled={busy==="question"}>Send Question</button></form></section>}
 {(requests.length>0||questions.length>0)&&<section className="card"><h2>Mentor Messages</h2><div className="developmentModules mentorInbox">{requests.map(request=><article key={request.id}><div className="moduleBody"><span>{new Date(request.requested_at).toLocaleString()} • Mentor Request</span><h3>{request.status==="pending"?"Waiting for a mentor response":"Mentor request updated"}</h3>{request.response&&<p>{request.response}</p>}</div></article>)}{questions.map(question=><article key={question.id}><div className="moduleBody"><span>{new Date(question.asked_at).toLocaleString()} • {question.status}</span><h3>{question.question}</h3>{question.response?<p><b>{question.responder_name||"Iowa Soccer Mentor"}:</b> {question.response}</p>:<p>Waiting for a mentor response.</p>}</div></article>)}</div></section>}
 {announcements.length>0&&<section className="card"><h2>Program Updates</h2><div className="announcementGrid">{announcements.map(announcement=><article key={announcement.id}><small>{new Date(announcement.published_at).toLocaleDateString()}</small><h3>{announcement.title}</h3><p>{announcement.message}</p></article>)}</div></section>}
 <section className="card"><div className="cardHead"><div><h2>Training Path</h2><p>Complete each module at your own pace.</p></div></div><div className="developmentModules">{modules.map((module,index)=>{const status=progress[module.id]||"not_started";return <article key={module.id} className={status==="completed"?"complete":""}><div className="moduleNumber">{status==="completed"?"✓":index+1}</div><div className="moduleBody"><span>{module.category}{module.required?" • Required":""}</span><h3>{module.title}</h3><p>{module.description}</p>{module.resource_url&&<a href={module.resource_url} target="_blank" rel="noreferrer">Open Training Resource</a>}</div><div className="moduleActions"><select aria-label={`Progress for ${module.title}`} value={status} disabled={busy===module.id} onChange={event=>void setStatus(module.id,event.target.value)}><option value="not_started">Not Started</option><option value="in_progress">In Progress</option><option value="completed">Completed</option></select></div></article>})}</div></section></>}
