"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../lib/supabase/client";
type Module={id:string;title:string;description:string;category:string;resource_url:string|null;required:boolean;sort_order:number};
type Progress={module_id:string;status:string};
type Announcement={id:string;title:string;message:string;published_at:string};
export default function IowaSoccerDevelopment(){const supabase=useMemo(()=>createClient(),[]),[officialId,setOfficialId]=useState(""),[modules,setModules]=useState<Module[]>([]),[progress,setProgress]=useState<Record<string,string>>({}),[announcements,setAnnouncements]=useState<Announcement[]>([]),[busy,setBusy]=useState(""),[error,setError]=useState("");
 async function load(){setError("");const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:official,error:officialError}=await supabase.from("officials").select("id").eq("auth_user_id",user.id).maybeSingle();if(officialError||!official)return setError("Your official account is not connected to the Iowa Soccer development program.");setOfficialId(official.id);const{data:program,error:programError}=await supabase.from("registration_programs").select("id").eq("slug","iowa-soccer").single();if(programError)return setError(programError.message);const[m,p,a]=await Promise.all([supabase.from("development_modules").select("id,title,description,category,resource_url,required,sort_order").eq("program_id",program.id).eq("active",true).order("sort_order"),supabase.from("official_development_progress").select("module_id,status").eq("official_id",official.id),supabase.from("development_announcements").select("id,title,message,published_at").eq("program_id",program.id).eq("active",true).order("published_at",{ascending:false})]);const e=m.error||p.error||a.error;if(e)return setError(e.message);setModules((m.data||[]) as Module[]);const map:Record<string,string>={};for(const row of (p.data||[]) as Progress[])map[row.module_id]=row.status;setProgress(map);setAnnouncements((a.data||[]) as Announcement[])}
 useEffect(()=>{void load()},[]);
 async function setStatus(moduleId:string,status:string){if(!officialId)return;setBusy(moduleId);setError("");const{error:e}=await supabase.from("official_development_progress").upsert({module_id:moduleId,official_id:officialId,status,completed_at:status==="completed"?new Date().toISOString():null,updated_at:new Date().toISOString()});if(e)setError(e.message);else setProgress(old=>({...old,[moduleId]:status}));setBusy("")}
 const complete=modules.filter(m=>progress[m.id]==="completed").length,percent=modules.length?Math.round(complete/modules.length*100):0;
 return <><section className="card developmentHero"><div><span className="developmentEyebrow">IOWA SOCCER</span><h2>Young Official Development</h2><p>Build confidence, strengthen your knowledge, and prepare for successful match assignments.</p></div><div className="developmentProgress"><strong>{percent}%</strong><span>{complete} of {modules.length} modules complete</span><div><i style={{width:`${percent}%`}}/></div></div></section>
 {error&&<div className="errorBox">{error}</div>}
 {announcements.length>0&&<section className="card"><h2>Program Updates</h2><div className="announcementGrid">{announcements.map(a=><article key={a.id}><small>{new Date(a.published_at).toLocaleDateString()}</small><h3>{a.title}</h3><p>{a.message}</p></article>)}</div></section>}
 <section className="card"><div className="cardHead"><div><h2>Training Path</h2><p>Complete each module at your own pace.</p></div></div><div className="developmentModules">{modules.map((module,index)=>{const status=progress[module.id]||"not_started";return <article key={module.id} className={status==="completed"?"complete":""}><div className="moduleNumber">{status==="completed"?"✓":index+1}</div><div className="moduleBody"><span>{module.category}{module.required?" • Required":""}</span><h3>{module.title}</h3><p>{module.description}</p>{module.resource_url&&<a href={module.resource_url} target="_blank" rel="noreferrer">Open Training Resource</a>}</div><div className="moduleActions"><select aria-label={`Progress for ${module.title}`} value={status} disabled={busy===module.id} onChange={e=>void setStatus(module.id,e.target.value)}><option value="not_started">Not Started</option><option value="in_progress">In Progress</option><option value="completed">Completed</option></select></div></article>})}</div></section></>}
