"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {createClient} from "../lib/supabase/client";
type Person={id:string;first_name:string;last_name:string;email:string|null;is_mentor:boolean};
type InboxItem={item_type:"mentor_request"|"question";id:string;official_id:string;official_name:string;body:string;status:string;created_at:string;response:string|null;responder_name:string|null};
export default function IowaDevelopmentMentors(){const supabase=useMemo(()=>createClient(),[]),[people,setPeople]=useState<Person[]>([]),[inbox,setInbox]=useState<InboxItem[]>([]),[selected,setSelected]=useState(""),[programId,setProgramId]=useState(""),[isStaff,setIsStaff]=useState(false),[replying,setReplying]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){setError("");const[{data,error:e},{data:program},{data:staff},{data:items,error:inboxError}]=await Promise.all([supabase.rpc("list_iowa_development_people"),supabase.from("registration_programs").select("id").eq("slug","iowa-soccer").single(),supabase.rpc("is_iowa_soccer_development_staff"),supabase.rpc("list_iowa_development_inbox")]);if(e||inboxError)setError((e||inboxError)!.message);else{setPeople((data||[]) as Person[]);setInbox((items||[]) as InboxItem[])}if(program)setProgramId(program.id);setIsStaff(Boolean(staff))}
 useEffect(()=>{void load()},[]);
 async function add(){if(!selected)return;setBusy(true);const{data:{user}}=await supabase.auth.getUser(),{error:e}=await supabase.from("development_mentors").insert({program_id:programId,official_id:selected,added_by:user?.id});if(e)setError(e.message);else{setNotice("Mentor added.");setSelected("");await load()}setBusy(false)}
 async function remove(id:string){if(!window.confirm("Remove this mentor from the Iowa Soccer development team?"))return;const{error:e}=await supabase.from("development_mentors").delete().eq("program_id",programId).eq("official_id",id);if(e)setError(e.message);else await load()}
 async function respond(event:FormEvent<HTMLFormElement>,item:InboxItem){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget),response=String(form.get("response")||""),{data:{user}}=await supabase.auth.getUser(),{data:profile}=await supabase.from("profiles").select("full_name").eq("id",user?.id||"").maybeSingle(),now=new Date().toISOString();const result=item.item_type==="question"?await supabase.from("development_questions").update({response,status:"answered",responded_by:user?.id,responder_name:profile?.full_name||user?.email||"Iowa Soccer Mentor",responded_at:now}).eq("id",item.id):await supabase.from("development_mentor_requests").update({response,status:"assigned",handled_by:user?.id,responded_at:now}).eq("id",item.id);if(result.error)setError(result.error.message);else{setNotice("Response sent to "+item.official_name+".");setReplying("");await load()}setBusy(false)}
 const mentors=people.filter(person=>person.is_mentor),available=people.filter(person=>!person.is_mentor),openItems=inbox.filter(item=>item.status==="open"||item.status==="pending");
 return <><section className="card"><div className="cardHead"><div><h2>Mentor Inbox</h2><p>Respond directly to referee questions and mentor requests.</p></div><span className="badge yellow">{openItems.length} open</span></div>{error&&<div className="errorBox">{error}</div>}{notice&&<div className="loginMessage">{notice}</div>}<div className="developmentModules">{inbox.length?inbox.map(item=><article key={item.id}><div className="moduleBody"><span>{new Date(item.created_at).toLocaleString()} • {item.item_type==="question"?"Question":"Mentor Request"} • {item.status}</span><h3>{item.official_name}</h3>{item.item_type==="question"&&<p>{item.body}</p>}{item.response&&<p><b>Response:</b> {item.response}</p>}{!item.response&&<button className="secondary" onClick={()=>setReplying(item.id)}>Respond</button>}{replying===item.id&&<form className="officialForm" onSubmit={event=>void respond(event,item)}><label className="fullSpan">Response<textarea name="response" required maxLength={5000} rows={3}/></label><div className="headerActions"><button className="primary" disabled={busy}>Send Response</button><button type="button" className="secondary" onClick={()=>setReplying("")}>Cancel</button></div></form>}</div></article>):<p>No mentor requests or questions have been submitted.</p>}</div></section>
 {isStaff&&<section className="card"><div className="cardHead"><div><h2>Development Mentors</h2><p>Mentors can view program referees, answer questions, and add shared developmental notes.</p></div></div><div className="toolbar"><label>Add Program Referee as Mentor<select value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Select a referee</option>{available.map(person=><option key={person.id} value={person.id}>{person.last_name}, {person.first_name}</option>)}</select></label><button className="primary" disabled={busy||!selected} onClick={()=>void add()}>Add Mentor</button></div><div className="developmentRoster">{mentors.length?mentors.map(person=><div key={person.id}><span><b>{person.first_name} {person.last_name}</b><small>{person.email}</small></span><button className="secondary" onClick={()=>void remove(person.id)}>Remove Mentor</button></div>):<p>No mentors have been added yet.</p>}</div></section>}</>}
