'use client'

import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../lib/supabase/client'

type Game={id:string;game_number:string;starts_at:string;sport_id:string;officials_needed:number;home:{name:string}|null;away:{name:string}|null;location:{name:string}|null}
type Group={id:string;name:string;created_at:string}
type Member={group_id:string;game_id:string;sort_order:number}
type Assignment={id:string;game_id:string;official_id:string;position_id:string;status:string;published_at:string|null}
type Position={id:string;sport_id:string;name:string;sort_order:number}

export default function LinkedGamesManager(){
 const supabase=useMemo(()=>createClient(),[])
 const [games,setGames]=useState<Game[]>([]),[groups,setGroups]=useState<Group[]>([]),[members,setMembers]=useState<Member[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[positions,setPositions]=useState<Position[]>([])
 const [name,setName]=useState(''),[selectedGroup,setSelectedGroup]=useState(''),[addGame,setAddGame]=useState(''),[sourceGame,setSourceGame]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 async function load(){setError('');const [g,gr,m,a,p]=await Promise.all([supabase.from('games').select('id,game_number,starts_at,sport_id,officials_needed,home:teams!games_home_team_id_fkey(name),away:teams!games_away_team_id_fkey(name),location:locations(name)').order('starts_at'),supabase.from('game_link_groups').select('id,name,created_at').order('created_at',{ascending:false}),supabase.from('game_link_members').select('group_id,game_id,sort_order').order('sort_order'),supabase.from('assignments').select('id,game_id,official_id,position_id,status,published_at'),supabase.from('sport_positions').select('id,sport_id,name,sort_order').order('sort_order')]);const e=g.error||gr.error||m.error||a.error||p.error;if(e){setError(e.message);return}setGames((g.data||[]) as unknown as Game[]);setGroups((gr.data||[]) as Group[]);setMembers((m.data||[]) as Member[]);setAssignments((a.data||[]) as Assignment[]);setPositions((p.data||[]) as Position[]);const groupIds=new Set(((gr.data||[]) as Group[]).map(x=>x.id));setSelectedGroup(x=>x&&groupIds.has(x)?x:(((gr.data||[])[0] as Group|undefined)?.id||''))}
 useEffect(()=>{void load()},[])
 const groupMembers=members.filter(m=>m.group_id===selectedGroup).map(m=>games.find(g=>g.id===m.game_id)).filter(Boolean) as Game[]
 const linkedIds=new Set(members.map(m=>m.game_id)),availableGames=games.filter(g=>!linkedIds.has(g.id))
 function label(g:Game){const d=new Date(g.starts_at);return `${g.game_number} — ${g.home?.name||'TBD'} vs ${g.away?.name||'TBD'} — ${d.toLocaleDateString()} ${d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`}
 async function createGroup(){const clean=name.trim();if(!clean)return;setBusy(true);setError('');setNotice('');const {data:user}=await supabase.auth.getUser();const {data,error:e}=await supabase.from('game_link_groups').insert({name:clean,created_by:user.user?.id||null}).select('id').single();if(e)setError(e.message);else{setName('');setSelectedGroup(data.id);setNotice('Linked game group created.')}await load();setBusy(false)}
 async function addMember(){if(!selectedGroup||!addGame)return;setBusy(true);setError('');setNotice('');const order=members.filter(m=>m.group_id===selectedGroup).length;const {error:e}=await supabase.from('game_link_members').insert({group_id:selectedGroup,game_id:addGame,sort_order:order});if(e)setError(e.message);else{setAddGame('');setNotice('Game linked.')}await load();setBusy(false)}
 async function removeMember(gameId:string){setBusy(true);setError('');setNotice('');const {error:e}=await supabase.from('game_link_members').delete().eq('group_id',selectedGroup).eq('game_id',gameId);if(e)setError(e.message);else setNotice('Game unlinked.');await load();setBusy(false)}
 async function deleteGroup(){if(!selectedGroup||!confirm('Delete this linked-game group? The games and assignments will not be deleted.'))return;setBusy(true);const {error:e}=await supabase.from('game_link_groups').delete().eq('id',selectedGroup);if(e)setError(e.message);else{setSelectedGroup('');setNotice('Linked-game group deleted.')}await load();setBusy(false)}
 async function copyCrew(){const source=games.find(g=>g.id===sourceGame);if(!source||groupMembers.length<2)return;const sourceAssignments=assignments.filter(a=>a.game_id===source.id&&a.status!=='declined');if(!sourceAssignments.length){setError('The source game has no crew to copy.');return}if(!confirm(`Copy the crew from ${source.game_number} into open matching positions on the other linked games? Existing assignments will be left unchanged.`))return;setBusy(true);setError('');setNotice('');let copied=0,skipped=0;for(const target of groupMembers){if(target.id===source.id)continue;const targetPositions=positions.filter(p=>p.sport_id===target.sport_id).sort((a,b)=>a.sort_order-b.sort_order).slice(0,target.officials_needed);const sourcePositions=positions.filter(p=>p.sport_id===source.sport_id);for(const sa of sourceAssignments){const sp=sourcePositions.find(p=>p.id===sa.position_id);if(!sp){skipped++;continue}const tp=targetPositions.find(p=>p.name.trim().toLowerCase()===sp.name.trim().toLowerCase());if(!tp){skipped++;continue}const existing=assignments.find(a=>a.game_id===target.id&&a.position_id===tp.id&&a.status!=='declined');if(existing){skipped++;continue}const duplicate=assignments.find(a=>a.game_id===target.id&&a.official_id===sa.official_id&&a.status!=='declined');if(duplicate){skipped++;continue}const {error:e}=await supabase.from('assignments').insert({game_id:target.id,official_id:sa.official_id,position_id:tp.id,status:'proposed'});if(e){skipped++;continue}copied++}}
 setNotice(`Crew copy complete: ${copied} assignment${copied===1?'':'s'} added${skipped?`, ${skipped} skipped`:''}. New assignments are not published.`);await load();setBusy(false)}
 return <section className="card"><div className="cardHead"><div><h2>Linked Games</h2><p>Group games together and carry the same crew into matching open positions.</p></div></div>{error&&<div className="errorBox">{error}</div>}{notice&&<div className="loginMessage">{notice}</div>}<div style={{display:'grid',gridTemplateColumns:'minmax(220px,1fr) auto',gap:8,margin:'14px 0'}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Group name — e.g. Saturday Doubleheader"/><button className="primary" disabled={busy||!name.trim()} onClick={()=>void createGroup()}>Create Group</button></div>{groups.length?<><div style={{display:'grid',gridTemplateColumns:'minmax(220px,1fr) auto',gap:8,alignItems:'end'}}><label>Linked Group<select value={selectedGroup} onChange={e=>{setSelectedGroup(e.target.value);setSourceGame('')}}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><button className="secondary" disabled={busy||!selectedGroup} onClick={()=>void deleteGroup()}>Delete Group</button></div><div style={{marginTop:14,border:'1px solid #e2e8f0',borderRadius:10,overflow:'hidden'}}>{groupMembers.length?groupMembers.map(g=><div key={g.id} style={{display:'grid',gridTemplateColumns:'1fr auto',gap:10,alignItems:'center',padding:'10px 12px',borderBottom:'1px solid #e2e8f0'}}><div><b>{g.home?.name||'TBD'} vs {g.away?.name||'TBD'}</b><small style={{display:'block',color:'#64748b'}}>{g.game_number} • {new Date(g.starts_at).toLocaleString()} • {g.location?.name||'TBD'}</small></div><button className="secondary" disabled={busy} onClick={()=>void removeMember(g.id)}>Unlink</button></div>):<div style={{padding:14,color:'#64748b'}}>No games linked yet.</div>}</div><div style={{display:'grid',gridTemplateColumns:'minmax(240px,1fr) auto',gap:8,marginTop:14,alignItems:'end'}}><label>Add Game<select value={addGame} onChange={e=>setAddGame(e.target.value)}><option value="">Select an unlinked game</option>{availableGames.map(g=><option key={g.id} value={g.id}>{label(g)}</option>)}</select></label><button className="primary" disabled={busy||!addGame} onClick={()=>void addMember()}>Link Game</button></div>{groupMembers.length>1&&<div style={{display:'grid',gridTemplateColumns:'minmax(240px,1fr) auto',gap:8,marginTop:14,alignItems:'end',paddingTop:14,borderTop:'1px solid #e2e8f0'}}><label>Copy Crew From<select value={sourceGame} onChange={e=>setSourceGame(e.target.value)}><option value="">Select source game</option>{groupMembers.map(g=><option key={g.id} value={g.id}>{label(g)}</option>)}</select></label><button className="primary" disabled={busy||!sourceGame} onClick={()=>void copyCrew()}>Assign Crew to Linked Games</button></div>}<p><small>Copy Crew only fills matching open positions. Existing assignments are preserved, and copied assignments remain Not Published until you review and publish them.</small></p></>:<p style={{color:'#64748b'}}>Create your first linked-game group to get started.</p>}</section>
}
