'use client'
import {ChangeEvent,useEffect,useMemo,useState} from 'react'
import {createClient} from '../lib/supabase/client'

type Location={id:string;name:string;address:string|null;city:string|null;state:string|null;active:boolean}
type Row={row:number;id:string;name:string;address:string;city:string;state:string;active:string;action:'Add'|'Update';valid:boolean;issue:string}
const REQUIRED=['name','address','city','state','active']
function esc(v:string){return /[",\n]/.test(v)?`"${v.replace(/"/g,'""')}"`:v}
function parseCSV(text:string){const rows:string[][]=[];let row:string[]=[];let cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(v=>v.trim()))rows.push(row);row=[]}else cell+=ch}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows}

export default function LocationsRosterManager(){
 const supabase=useMemo(()=>createClient(),[])
 const [allowed,setAllowed]=useState(false),[locations,setLocations]=useState<Location[]>([]),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[importing,setImporting]=useState(false)
 async function load(){setError('');const {data:u}=await supabase.auth.getUser();if(!u.user)return;const {data:p}=await supabase.from('profiles').select('role').eq('id',u.user.id).maybeSingle();const ok=['admin','assignor'].includes(p?.role||'');setAllowed(ok);if(!ok)return;const {data,error}=await supabase.from('locations').select('id,name,address,city,state,active').order('name');if(error)setError(error.message);else setLocations((data||[]) as Location[])}
 useEffect(()=>{load()},[])
 function downloadCurrent(){const head=['id',...REQUIRED].join(',');const lines=locations.map(v=>[v.id,v.name,v.address||'',v.city||'',v.state||'',v.active?'true':'false'].map(x=>esc(String(x))).join(','));const blob=new Blob([[head,...lines].join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='refassign-locations.csv';a.click();URL.revokeObjectURL(url)}
 function resolveExistingId(suppliedId:string,name:string){if(suppliedId&&locations.some(v=>v.id===suppliedId))return suppliedId;const match=locations.find(v=>v.name.trim().toLowerCase()===name.trim().toLowerCase());return match?.id||''}
 function validate(raw:string[][]):Row[]{if(!raw.length)throw new Error('Import file is empty.');const h=raw[0].map(x=>String(x).trim().toLowerCase().replace(/\s+/g,'_'));const missing=REQUIRED.filter(x=>!h.includes(x));if(missing.length)throw new Error(`Missing column(s): ${missing.join(', ')}`);return raw.slice(1).map((r,i)=>{const get=(x:string)=>String(r[h.indexOf(x)]??'').trim();const name=get('name'),active=get('active').toLowerCase(),id=resolveExistingId(get('id'),name);const issues:string[]=[];if(!name)issues.push('Column name: missing value');if(!['true','false','yes','no','1','0'].includes(active))issues.push(`Column active: must be true/false (received "${get('active')}")`);return{row:i+2,id,name,address:get('address'),city:get('city'),state:get('state'),active:get('active'),action:id?'Update':'Add',valid:!issues.length,issue:issues.join('; ')}})}
 async function handleFile(e:ChangeEvent<HTMLInputElement>){setRows([]);setMessage('');setError('');const f=e.target.files?.[0];if(!f)return;try{const buffer=await f.arrayBuffer();let raw:string[][]|null=null;try{const XLSX=await import('xlsx');const wb=XLSX.read(buffer,{type:'array'});if(wb.SheetNames.length){const ws=wb.Sheets[wb.SheetNames[0]];raw=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false}) as string[][]}}catch{}if(!raw||!raw.length){raw=parseCSV(new TextDecoder('utf-8').decode(buffer))}setRows(validate(raw))}catch(err){setError(err instanceof Error?`${err.message} Selected file: ${f.name}`:`Unable to read locations file: ${f.name}`)}finally{e.target.value=''}}
 async function applyImport(){if(!rows.length||rows.some(r=>!r.valid))return;setImporting(true);setError('');let added=0,updated=0;try{for(const r of rows){try{const payload={name:r.name,address:r.address||null,city:r.city||null,state:r.state||null,level_id:null,active:['true','yes','1'].includes(r.active.toLowerCase())};if(r.id){const x=await supabase.from('locations').update(payload).eq('id',r.id);if(x.error)throw x.error;updated++}else{const x=await supabase.from('locations').insert(payload);if(x.error)throw x.error;added++}}catch(rowErr){const msg=rowErr instanceof Error?rowErr.message:String(rowErr);throw new Error(`Location row ${r.row} (${r.name}) failed: ${msg}`)}}setMessage(`Locations import complete: ${updated} updated, ${added} added.`);setRows([]);await load()}catch(err){setError(err instanceof Error?err.message:'Locations import failed')}finally{setImporting(false)}}
 if(!allowed)return <section className="card"><h3>Locations Import / Export</h3><p>Only Administrators and Assignors can use the locations uploader.</p></section>
 const invalid=rows.filter(r=>!r.valid).length
 return <section className="card"><div className="cardHead"><div><h3>Locations Import / Export</h3><p>Download current locations, edit or add rows in Excel/Sheets, then upload the updated file.</p></div><button className="secondary" onClick={downloadCurrent}>Download Current Locations</button></div><input type="file" onChange={handleFile}/><p><small>RefAssign accepts spreadsheet or CSV content. Existing locations match by exported ID first, then by Location Name. Leave ID blank for new locations.</small></p>{error&&<div className="errorBox">{error}</div>}{message&&<div className="loginMessage">{message}</div>}{rows.length>0&&<><p>{rows.length} rows • {rows.filter(r=>r.action==='Update').length} updates • {rows.filter(r=>r.action==='Add').length} additions • {invalid} errors</p><div className="tableWrap"><table><thead><tr><th>Row</th><th>Action</th><th>Location</th><th>Address</th><th>City</th><th>State</th><th>Active</th><th>Validation</th></tr></thead><tbody>{rows.map(r=><tr key={r.row}><td>{r.row}</td><td><span className={`badge ${r.action==='Add'?'blue':'amber'}`}>{r.action}</span></td><td><b>{r.name}</b></td><td>{r.address}</td><td>{r.city}</td><td>{r.state}</td><td>{r.active}</td><td><span className={`badge ${r.valid?'green':'red'}`}>{r.valid?'Ready':r.issue}</span></td></tr>)}</tbody></table></div><button className="primary" disabled={importing||invalid>0} onClick={applyImport}>{importing?'Updating Locations…':'Apply Location Changes'}</button></>}</section>
}
