"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "../lib/supabase/client";
type Program={id:string;name:string;slug:string;registration_fee_cents:number|null};
type Registration={id:string;first_name:string;last_name:string;email:string;phone:string|null;sport:string;status:string;payment_status:string;fee_cents:number|null;paid_at:string|null;created_at:string;official_id:string|null;registration_program_id:string;registration_programs:{name:string;slug:string}|null};
type Level={id:string;name:string};type TrainingModule={id:string;title:string;delivery_type:string;requires_instructor:boolean;instructor_official_id:string|null;course_start_at:string|null};type TrainingRegistration={module_id:string;status:string};
export default function RegistrarManager(){
 const supabase=useMemo(()=>createClient(),[]),[registrations,setRegistrations]=useState<Registration[]>([]),[levels,setLevels]=useState<Level[]>([]),[programs,setPrograms]=useState<Program[]>([]),[trainingModules,setTrainingModules]=useState<TrainingModule[]>([]),[trainingRegistrations,setTrainingRegistrations]=useState<TrainingRegistration[]>([]),[fees,setFees]=useState<Record<string,string>>({}),[eligibility,setEligibility]=useState<Record<string,string[]>>({}),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){setError("");const[r,l,p,tm,tr]=await Promise.all([supabase.from("official_registrations").select("id,first_name,last_name,email,phone,sport,status,payment_status,fee_cents,paid_at,created_at,official_id,registration_program_id,registration_programs(name,slug)").order("created_at",{ascending:false}),supabase.from("levels").select("id,name").eq("active",true).order("name"),supabase.from("registration_programs").select("id,name,slug,registration_fee_cents").eq("active",true).order("name"),supabase.from("development_modules").select("id,title,delivery_type,requires_instructor,instructor_official_id,course_start_at").eq("active",true),supabase.from("development_training_registrations").select("module_id,status").eq("status","approved")]);const e=r.error||l.error||p.error||tm.error||tr.error;if(e)return setError(e.message);setRegistrations((r.data||[]) as unknown as Registration[]);setLevels((l.data||[]) as Level[]);setPrograms((p.data||[]) as Program[]);setTrainingModules((tm.data||[]) as TrainingModule[]);setTrainingRegistrations((tr.data||[]) as TrainingRegistration[]);const f:Record<string,string>={};for(const row of p.data||[])f[row.id]=row.registration_fee_cents==null?"":(Number(row.registration_fee_cents)/100).toFixed(2);setFees(f)}
 useEffect(()=>{void load()},[]);
 async function saveFee(program:Program){const amount=Number(fees[program.id]);if(!Number.isFinite(amount)||amount<=0)return setError("Enter a registration fee greater than $0.");setBusy(`fee-${program.id}`);setError("");setNotice("");const{data:u}=await supabase.auth.getUser();const{error:e}=await supabase.from("registration_programs").update({registration_fee_cents:Math.round(amount*100),registration_open:true,updated_at:new Date().toISOString(),updated_by:u.user?.id||null}).eq("id",program.id);if(e)setError(e.message);else setNotice(`${program.name} fee saved.`);setBusy("");await load()}
 function toggle(registrationId:string,levelId:string){setEligibility(current=>{const selected=current[registrationId]||[];return{...current,[registrationId]:selected.includes(levelId)?selected.filter(id=>id!==levelId):[...selected,levelId]}})}
 async function markPaid(registration:Registration){if(!window.confirm(`Mark ${registration.first_name} ${registration.last_name} paid for ${registration.registration_programs?.name||"this registration"}?`))return;setBusy(registration.id);setError("");setNotice("");const{error:e}=await supabase.rpc("mark_registration_paid",{p_registration_id:registration.id});if(e)setError(e.message);else setNotice("Registration marked paid. It can now be approved.");setBusy("");await load()}
 async function approve(registration:Registration){const isCourse=registration.registration_programs?.slug==="small-sided-referee-course",selected=eligibility[registration.id]||[];if(!isCourse&&!selected.length)return setError("Select at least one eligible level.");setBusy(registration.id);setError("");setNotice("");const{error:e}=await supabase.rpc("approve_official_registration",{p_registration_id:registration.id,p_level_ids:isCourse?[]:selected});if(e)setError(e.message);else setNotice(isCourse?`${registration.first_name} ${registration.last_name} is approved for the Small Sided Referee Course.`:`${registration.first_name} ${registration.last_name} is now registered and available for assignment.`);setBusy("");await load()}
 async function copyLink(){await navigator.clipboard.writeText(`${window.location.origin}/register`);setNotice("Registration link copied.")}
 const review=registrations.filter(r=>r.payment_status==="paid"&&r.status!=="approved"),waiting=registrations.filter(r=>r.payment_status!=="paid"&&r.status!=="approved"),approved=registrations.filter(r=>r.status==="approved"),action=[...waiting,...review],courseApproved=approved.filter(r=>r.registration_programs?.slug==="small-sided-referee-course").length,courseTotal=registrations.filter(r=>r.registration_programs?.slug==="small-sided-referee-course").length,approvedTrainingIds=new Set(trainingRegistrations.map(r=>r.module_id)),missingInstructorCourses=trainingModules.filter(m=>m.delivery_type==="in_person"&&m.requires_instructor&&approvedTrainingIds.has(m.id)&&!m.instructor_official_id);
 return <><section className="card"><div className="cardHead"><div><h2>Registration Programs</h2><p>Manage fees and applicants for registration programs assigned to your account.</p></div><button className="primary" onClick={()=>void copyLink()}>Copy Registration Link</button></div>{error&&<div className="errorBox">{error}</div>}{notice&&<div className="loginMessage">{notice}</div>}{missingInstructorCourses.length>0&&<div className="errorBox" style={{borderColor:"#dc2626",background:"#fff1f2",color:"#991b1b"}}><b>🚩 Instructor Required</b>{missingInstructorCourses.map(course=><div key={course.id} style={{marginTop:6}}><b>{course.title}</b>{course.course_start_at?` — ${new Date(course.course_start_at).toLocaleString()}`:""} has an approved registration and no instructor assigned.</div>)}</div>}<div className="registrarMetrics"><div><strong>{review.length}</strong><span>Paid — Needs Review</span></div><div><strong>{waiting.length}</strong><span>Awaiting Payment</span></div><div><strong>{approved.length}</strong><span>Approved Registrations</span></div><div><strong>{courseApproved}</strong><span>Small Sided Course Approved</span></div></div><h3>Registration Fees</h3><div className="eligibilityGrid">{programs.map(program=><div className="leagueFee" key={program.id}><label>{program.name}<input type="number" min="0.01" step="0.01" placeholder="Fee" value={fees[program.id]||""} onChange={e=>setFees(old=>({...old,[program.id]:e.target.value}))}/></label><button className="secondary" disabled={busy===`fee-${program.id}`} onClick={()=>void saveFee(program)}>Save Fee</button></div>)}</div>{programs.some(p=>p.slug==="small-sided-referee-course")&&<p style={{marginTop:12}}><b>Small Sided Referee Course:</b> {courseApproved} approved of {courseTotal} total registrations.</p>}</section>
 <section className="card"><h2>Registrations Needing Action</h2>{action.length===0?<p>No registrations are waiting for action.</p>:action.map(registration=>{const isCourse=registration.registration_programs?.slug==="small-sided-referee-course";return <div className="registrationReview" key={registration.id}><div><h3>{registration.first_name} {registration.last_name}</h3><p>{registration.email}{registration.phone?` • ${registration.phone}`:""} • {registration.registration_programs?.name}</p><small>{registration.payment_status==="paid"?`Paid ${registration.paid_at?new Date(registration.paid_at).toLocaleString():""}`:"Payment not yet confirmed"}</small></div>{registration.payment_status!=="paid"?<button className="secondary" disabled={busy===registration.id} onClick={()=>void markPaid(registration)}>Mark Paid</button>:<>{!isCourse&&<fieldset><legend>Eligible Levels</legend><div className="eligibilityGrid">{levels.map(level=><label key={level.id}><input type="checkbox" checked={(eligibility[registration.id]||[]).includes(level.id)} onChange={()=>toggle(registration.id,level.id)}/>{level.name}</label>)}</div></fieldset>}<button className="primary" disabled={busy===registration.id} onClick={()=>void approve(registration)}>{isCourse?"Approve Course Registration":"Approve Registration & Eligibility"}</button></>}</div>})}</section>
 <section className="card"><h2>Registration History</h2><div className="tableWrap"><table><thead><tr><th>Official</th><th>Program</th><th>Submitted</th><th>Payment</th><th>Status</th></tr></thead><tbody>{registrations.map(row=><tr key={row.id}><td><b>{row.first_name} {row.last_name}</b><small>{row.email}</small></td><td>{row.registration_programs?.name||"—"}</td><td>{new Date(row.created_at).toLocaleDateString()}</td><td><span className={`badge ${row.payment_status==="paid"?"green":"yellow"}`}>{row.payment_status}</span></td><td>{row.status}</td></tr>)}</tbody></table></div></section></>;
}
