"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "../lib/supabase/client";
type League={id:string;name:string};
type Registration={id:string;first_name:string;last_name:string;email:string;phone:string|null;sport:string;status:string;payment_status:string;fee_cents:number|null;paid_at:string|null;created_at:string;official_id:string|null;league_id:string;leagues:{name:string}|null};
type Level={id:string;name:string};
export default function RegistrarManager(){
 const supabase=useMemo(()=>createClient(),[]),[registrations,setRegistrations]=useState<Registration[]>([]),[levels,setLevels]=useState<Level[]>([]),[leagues,setLeagues]=useState<League[]>([]),[fees,setFees]=useState<Record<string,string>>({}),[eligibility,setEligibility]=useState<Record<string,string[]>>({}),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){setError("");const[r,l,g,s]=await Promise.all([supabase.from("official_registrations").select("id,first_name,last_name,email,phone,sport,status,payment_status,fee_cents,paid_at,created_at,official_id,league_id,leagues(name)").order("created_at",{ascending:false}),supabase.from("levels").select("id,name").eq("active",true).order("name"),supabase.from("leagues").select("id,name").eq("active",true).order("name"),supabase.from("league_registration_settings").select("league_id,registration_fee_cents")]);const e=r.error||l.error||g.error||s.error;if(e)return setError(e.message);setRegistrations((r.data||[]) as unknown as Registration[]);setLevels((l.data||[]) as Level[]);setLeagues((g.data||[]) as League[]);const f:Record<string,string>={};for(const row of s.data||[])f[row.league_id]=(Number(row.registration_fee_cents)/100).toFixed(2);setFees(f)}
 useEffect(()=>{void load()},[]);
 async function saveFee(league:League){const amount=Number(fees[league.id]);if(!Number.isFinite(amount)||amount<=0)return setError("Enter a registration fee greater than $0.");setBusy(`fee-${league.id}`);setError("");setNotice("");const{data:u}=await supabase.auth.getUser();const{error:e}=await supabase.from("league_registration_settings").upsert({league_id:league.id,registration_fee_cents:Math.round(amount*100),registration_open:true,updated_at:new Date().toISOString(),updated_by:u.user?.id||null});if(e)setError(e.message);else setNotice(`${league.name} registration fee saved.`);setBusy("");await load()}
 function toggle(registrationId:string,levelId:string){setEligibility(current=>{const selected=current[registrationId]||[];return{...current,[registrationId]:selected.includes(levelId)?selected.filter(id=>id!==levelId):[...selected,levelId]}})}
 async function markPaid(registration:Registration){if(!window.confirm(`Mark ${registration.first_name} ${registration.last_name} paid for ${registration.leagues?.name||"this league"}?`))return;setBusy(registration.id);setError("");setNotice("");const{error:e}=await supabase.rpc("mark_registration_paid",{p_registration_id:registration.id});if(e)setError(e.message);else setNotice("Registration marked paid. It can now be approved.");setBusy("");await load()}
 async function approve(registration:Registration){const selected=eligibility[registration.id]||[];if(!selected.length)return setError("Select at least one eligible level.");setBusy(registration.id);setError("");setNotice("");const{error:e}=await supabase.rpc("approve_official_registration",{p_registration_id:registration.id,p_level_ids:selected});if(e)setError(e.message);else setNotice(`${registration.first_name} ${registration.last_name} is now registered and available for assignment.`);setBusy("");await load()}
 async function copyLink(){await navigator.clipboard.writeText(`${window.location.origin}/register`);setNotice("New-official registration link copied.")}
 const review=registrations.filter(r=>r.payment_status==="paid"&&r.status!=="approved"),waiting=registrations.filter(r=>r.payment_status!=="paid"&&r.status!=="approved"),approved=registrations.filter(r=>r.status==="approved"),action=[...waiting,...review];
 return <><section className="card"><div className="cardHead"><div><h2>League Registration</h2><p>Manage registration only for leagues assigned to your account.</p></div><button className="primary" onClick={()=>void copyLink()}>Copy New Official Registration Link</button></div>{error&&<div className="errorBox">{error}</div>}{notice&&<div className="loginMessage">{notice}</div>}<div className="registrarMetrics"><div><strong>{review.length}</strong><span>Paid — Needs Review</span></div><div><strong>{waiting.length}</strong><span>Awaiting Payment</span></div><div><strong>{approved.length}</strong><span>Registered Officials</span></div></div><h3>Registration Fees by League</h3><div className="eligibilityGrid">{leagues.map(league=><div className="leagueFee" key={league.id}><label>{league.name}<input type="number" min="0.01" step="0.01" placeholder="Fee" value={fees[league.id]||""} onChange={e=>setFees(old=>({...old,[league.id]:e.target.value}))}/></label><button className="secondary" disabled={busy===`fee-${league.id}`} onClick={()=>void saveFee(league)}>Save Fee</button></div>)}</div></section>
 <section className="card"><h2>Registrations Needing Action</h2>{action.length===0?<p>No registrations are waiting for action.</p>:action.map(registration=><div className="registrationReview" key={registration.id}><div><h3>{registration.first_name} {registration.last_name}</h3><p>{registration.email}{registration.phone?` • ${registration.phone}`:""} • {registration.leagues?.name}</p><small>{registration.payment_status==="paid"?`Paid ${registration.paid_at?new Date(registration.paid_at).toLocaleString():""}`:"Payment not yet confirmed"}</small></div>{registration.payment_status!=="paid"?<button className="secondary" disabled={busy===registration.id} onClick={()=>void markPaid(registration)}>Mark Paid</button>:<><fieldset><legend>Eligible Levels</legend><div className="eligibilityGrid">{levels.map(level=><label key={level.id}><input type="checkbox" checked={(eligibility[registration.id]||[]).includes(level.id)} onChange={()=>toggle(registration.id,level.id)}/>{level.name}</label>)}</div></fieldset><button className="primary" disabled={busy===registration.id} onClick={()=>void approve(registration)}>Approve Registration & Eligibility</button></>}</div>)}</section>
 <section className="card"><h2>Registration History</h2><div className="tableWrap"><table><thead><tr><th>Official</th><th>League</th><th>Submitted</th><th>Payment</th><th>Status</th></tr></thead><tbody>{registrations.map(row=><tr key={row.id}><td><b>{row.first_name} {row.last_name}</b><small>{row.email}</small></td><td>{row.leagues?.name||"—"}</td><td>{new Date(row.created_at).toLocaleDateString()}</td><td><span className={`badge ${row.payment_status==="paid"?"green":"yellow"}`}>{row.payment_status}</span></td><td>{row.status}</td></tr>)}</tbody></table></div></section></>;
}
