"use client";

import { useEffect, useState } from "react";

type SavedView = { id: string; name: string; filters: Record<string, string>; is_favorite: boolean; recipient_email: string | null; frequency: "weekly" | "monthly"; send_day: number; schedule_enabled: boolean; next_send_at: string | null };
export default function ReportSavedViews({ organizationId, reportKey, filters, onApply }: { organizationId?: string; reportKey: "operations" | "coverage" | "audit" | "payroll"; filters: Record<string, string>; onApply: (filters: Record<string, string>) => void }) {
  const [views, setViews] = useState<SavedView[]>([]), [access, setAccess] = useState<"standard" | "premium">("standard"), [selected, setSelected] = useState(""), [name, setName] = useState(""), [favorite, setFavorite] = useState(false), [email, setEmail] = useState(""), [frequency, setFrequency] = useState<"weekly" | "monthly">("weekly"), [sendDay, setSendDay] = useState(1), [scheduled, setScheduled] = useState(false), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const endpoint = `/api/reports/saved-views?organizationId=${encodeURIComponent(organizationId || "")}&reportKey=${reportKey}`;
  const load = async () => { const response = await fetch(endpoint, { cache: "no-store" }), result = await response.json(); if (!response.ok) throw new Error(result.error || "Saved views could not be loaded."); setViews(result.views || []); setAccess(result.reportingAccess === "premium" ? "premium" : "standard"); setEmail((value) => value || result.defaultEmail || ""); };
  useEffect(() => { void load().catch((reason) => setMessage(reason instanceof Error ? reason.message : "Saved views could not be loaded.")); }, [endpoint]);
  const choose = (id: string) => { setSelected(id); const view = views.find((item) => item.id === id); if (!view) return; setName(view.name); setFavorite(view.is_favorite); setEmail(view.recipient_email || ""); setFrequency(view.frequency); setSendDay(view.send_day); setScheduled(view.schedule_enabled); onApply(view.filters); setMessage(`Applied “${view.name}”.`); };
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("savedView"); if (requested && views.some((view) => view.id === requested) && selected !== requested) choose(requested); }, [views, selected]);
  const save = async () => { setBusy(true); setMessage(""); try { const response = await fetch(`/api/reports/saved-views?organizationId=${encodeURIComponent(organizationId || "")}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: selected || undefined, reportKey, name: access === "premium" ? name : "My saved view", filters, isFavorite: favorite, recipientEmail: email, frequency, sendDay, scheduleEnabled: scheduled }) }), result = await response.json(); if (!response.ok) throw new Error(result.error || "The view could not be saved."); setSelected(result.view.id); setName(result.view.name); await load(); setMessage("Saved view updated."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "The view could not be saved."); } finally { setBusy(false); } };
  const remove = async () => { if (!selected) return; setBusy(true); const response = await fetch(`/api/reports/saved-views?organizationId=${encodeURIComponent(organizationId || "")}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "delete", id: selected, reportKey }) }); if (response.ok) { setSelected(""); setName(""); await load(); setMessage("Saved view deleted."); } setBusy(false); };
  const newView = () => { setSelected(""); setName(""); setFavorite(false); setScheduled(false); setMessage(""); };
  return <section className="savedViewsPanel" aria-label="Saved report views"><div className="savedViewsHead"><div><b>Saved view</b><small>{access === "premium" ? "Unlimited named views, favorites, and delivery" : "One saved view for this report"}</small></div><select value={selected} onChange={(event) => choose(event.target.value)}><option value="">Current filters</option>{views.map((view) => <option key={view.id} value={view.id}>{view.is_favorite ? "★ " : ""}{view.name}</option>)}</select>{access === "premium" ? <button type="button" className="tableButton" onClick={newView}>New</button> : null}</div>{access === "premium" ? <div className="savedViewsOptions"><label>Name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Friday coverage gaps" /></label><label><input type="checkbox" checked={favorite} onChange={(event) => setFavorite(event.target.checked)} /> Favorite</label><label><input type="checkbox" checked={scheduled} onChange={(event) => setScheduled(event.target.checked)} /> Scheduled delivery</label>{scheduled ? <><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Frequency<select value={frequency} onChange={(event) => setFrequency(event.target.value as "weekly" | "monthly")}><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label>{frequency === "weekly" ? "Weekday" : "Day of month"}<input type="number" min={frequency === "weekly" ? 0 : 1} max={frequency === "weekly" ? 6 : 28} value={sendDay} onChange={(event) => setSendDay(Number(event.target.value))} /></label></> : null}</div> : null}<div className="savedViewsActions"><button type="button" className="secondary" disabled={busy || (access === "premium" && !name.trim())} onClick={() => void save()}>{busy ? "Saving…" : selected ? "Update view" : "Save current filters"}</button>{access === "premium" && selected ? <button type="button" className="tableButton" disabled={busy} onClick={() => void remove()}>Delete</button> : null}<span aria-live="polite">{message}</span></div></section>;
}
