"use client";
import {FormEvent,useEffect,useState} from "react";
type Access={user_id:string;league_id:string;role:string};
type Account={id:string;email:string;full_name:string;active:boolean;roles:string[];league_access:Access[];protected:boolean};
type League={id:string;name:string};
const roleLabels:Record<string,string>={admin:"Administrator",assignor:"Assignor",league_admin:"League Administrator",registrar:"Registrar",official:"Official",contact:"Contact"};
export default function SuperAdminManager(){const[accounts,setAccounts]=useState<Account[]>([]),[leagues,setLeagues]=useState<League[]>([]),[selected,setSelected]=useState<Account|null>(null),[role,setRole]=useState("official"),[leagueIds,setLeagueIds]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){const response=await fetch("/api/super-admin/accounts");const result=await response.json();if(!response.ok)return setError(result.error||"Unable to load accounts.");setAccounts(result.accounts);setLeagues(result.leagues)}useEffect(()=>{void load()},[]);
 function choose(account:Account){setSelected(account);setRole(account.roles[0]||"official");setLeagueIds(account.league_access.map(a=>a.league_id));setError("");setNotice("")}
 function toggleLeague(id:string){setLeagueIds(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id])}
 async function createAccount(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget),newRole=String(form.get("role")||"official");const response=await fetch("/api/super-admin/accounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:form.get("email"),full_name:form.get("full_name"),role:newRole,league_ids:newRole==="registrar"||newRole==="league_admin"?leagueIds:[]})});const result=await response.json();if(!response.ok)setError(result.error);else{setNotice("Account created and invitation sent.");event.currentTarget.reset();setLeagueIds([]);await load()}setBusy(false)}
 async function save(){if(!selected)return;setBusy(true);setError("");const response=await fetch("/api/super-admin/accounts",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,role,active:selected.active,league_ids:leagueIds})});const result=await response.json();if(!response.ok)setError(result.error);else{setNotice("Account access updated.");await load()}setBusy(false)}
 async function remove(){if(!selected||selected.protected||!window.confirm(`Permanently delete ${selected.email}?`))return;setBusy(true);const response=await fetch("/api/super-admin/accounts",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id})});const result=await response.json();if(!response.ok)setError(result.error);else{setSelected(null);setNotice("Account deleted.");await load()}setBusy(false)}
 async function supportLink(){if(!selected||selected.protected)return;setBusy(true);const response=await fetch("/api/super-admin/support-link",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target_user_id:selected.id})});const result=await response.json();if(!response.ok)setError(result.error);else{await navigator.clipboard.writeText(result.url);setNotice("One-time support sign-in link copied. Open it in a private/incognito window so your super-admin session stays signed in.")}setBusy(false)}
 const needsLeague=role==="registrar"||role==="league_admin";
 return <><section className="card"><div className="cardHead"><div><h2>Super Admin</h2><p>Private account control and audited technical-support access.</p></div><span className="badge green">Protected Owner</span></div>{error&&<div className="errorBox">{error}</div>}{notice&&<div className="loginMessage">{notice}</div>}<form className="officialForm" onSubmit={createAccount}><label>Name<input name="full_name" required/></label><label>Email<input name="email" type="email" required/></label><label>Account Type<select name="role" defaultValue="official" onChange={e=>setRole(e.target.value)}>{Object.entries(roleLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{needsLeague&&<fieldset><legend>League Access</legend><div className="eligibilityGrid">{leagues.map(l=><label key={l.id}><input type="checkbox" checked={leagueIds.includes(l.id)} onChange={()=>toggleLeague(l.id)}/>{l.name}</label>)}</div></fieldset>}<button className="primary" disabled={busy}>Create Account & Send Invitation</button></form></section>
 <section className="card"><h2>Account Management</h2><div className="tableWrap"><table><thead><tr><th>Account</th><th>Type</th><th>League Access</th><th>Status</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id} onClick={()=>choose(a)} className={selected?.id===a.id?"selectedRow":""}><td><b>{a.full_name||a.email}</b><small>{a.email}</small></td><td>{a.protected?"Protected Owner":a.roles.map(r=>roleLabels[r]||r).join(", ")}</td><td>{a.league_access.map(x=>leagues.find(l=>l.id===x.league_id)?.name).filter(Boolean).join(", ")||"—"}</td><td>{a.active?"Active":"Inactive"}</td></tr>)}</tbody></table></div>{selected&&<div className="registrationReview"><h3>{selected.full_name||selected.email}</h3>{selected.protected?<p>This owner account is locked. No other account can edit, delete, or impersonate it.</p>:<><label>Account Type<select value={role} onChange={e=>setRole(e.target.value)}>{Object.entries(roleLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{needsLeague&&<fieldset><legend>League Access</legend><div className="eligibilityGrid">{leagues.map(l=><label key={l.id}><input type="checkbox" checked={leagueIds.includes(l.id)} onChange={()=>toggleLeague(l.id)}/>{l.name}</label>)}</div></fieldset>}<div className="toolbar"><button className="primary" disabled={busy} onClick={()=>void save()}>Save Access</button><button className="secondary" disabled={busy} onClick={()=>void supportLink()}>Copy One-Time Support Login</button><button className="danger" disabled={busy} onClick={()=>void remove()}>Delete Account</button></div></>}</div>}</section></>}
