"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {createClient} from "../lib/supabase/client";

type Ticket={id:string;ticket_number:string;subject:string;category:string;priority:string;status:string;description:string;organization_id:string|null;page_url:string|null;browser:string|null;device:string|null;last_error:string|null;screenshot_path:string|null;requester_user_id:string;assigned_to:string|null;created_at:string;updated_at:string};
type Message={id:string;ticket_id:string;author_user_id:string;message:string;internal_note:boolean;created_at:string};
const statusLabels:Record<string,string>={new:"New",reviewing:"Reviewing",waiting_on_customer:"Waiting on Customer",in_progress:"In Progress",resolved:"Resolved",closed:"Closed"};
const categories=["technical","assignment","billing","account","reporting","other"];
export default function SupportCenter({organizationId,isSuperAdmin=false}:{organizationId?:string;isSuperAdmin?:boolean}){
 const supabase=useMemo(()=>createClient(),[]),[tickets,setTickets]=useState<Ticket[]>([]),[messages,setMessages]=useState<Message[]>([]),[selected,setSelected]=useState<Ticket|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[filter,setFilter]=useState("open");
 async function load(){setError("");let query=supabase.from("support_tickets").select("*").order("updated_at",{ascending:false});if(isSuperAdmin&&filter!=="all")query=filter==="open"?query.not("status","in",'(resolved,closed)'):query.eq("status",filter);const{data,error}=await query;if(error)setError(error.message);else{setTickets((data||[]) as Ticket[]);if(selected){const fresh=(data||[]).find((x:any)=>x.id===selected.id);if(fresh)setSelected(fresh as Ticket)}}}
 async function loadMessages(ticket:Ticket){setSelected(ticket);const{data,error}=await supabase.from("support_ticket_messages").select("*").eq("ticket_id",ticket.id).order("created_at");if(error)setError(error.message);else setMessages((data||[]) as Message[])}
 useEffect(()=>{void load()},[filter]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");setNotice("");const form=e.currentTarget,fd=new FormData(form),{data:{user}}=await supabase.auth.getUser();if(!user){setError("Please sign in again.");setBusy(false);return}let screenshotPath:string|null=null;const screenshot=fd.get("screenshot") as File;if(screenshot?.size){if(screenshot.size>5242880){setError("Screenshot must be 5 MB or smaller.");setBusy(false);return}const ext=(screenshot.name.split(".").pop()||"png").toLowerCase(),path=`${user.id}/${crypto.randomUUID()}.${ext}`;const uploaded=await supabase.storage.from("support-ticket-screenshots").upload(path,screenshot);if(uploaded.error){setError(uploaded.error.message);setBusy(false);return}screenshotPath=path}const payload={requester_user_id:user.id,organization_id:organizationId||null,category:String(fd.get("category")),subject:String(fd.get("subject")).trim(),description:String(fd.get("description")).trim(),priority:String(fd.get("priority")),page_url:location.href,browser:navigator.userAgent,device:`${navigator.platform||"Unknown"} · ${screen.width}×${screen.height}`,last_error:String(fd.get("last_error")||"").trim()||null,screenshot_path:screenshotPath};const{data,error}=await supabase.from("support_tickets").insert(payload).select("*").single();if(error)setError(error.message);else{setNotice(`${data.ticket_number} was submitted.`);form.reset();await load();await loadMessages(data as Ticket)}setBusy(false)}
 async function reply(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setBusy(true);const fd=new FormData(e.currentTarget),{data:{user}}=await supabase.auth.getUser();const{error}=await supabase.from("support_ticket_messages").insert({ticket_id:selected.id,author_user_id:user!.id,message:String(fd.get("message")).trim(),internal_note:isSuperAdmin&&fd.get("internal_note")==="on"});if(error)setError(error.message);else{e.currentTarget.reset();await loadMessages(selected);await load()}setBusy(false)}
 async function updateTicket(patch:Partial<Ticket>){if(!selected)return;setBusy(true);const next={...patch,...(patch.status==="resolved"?{resolved_at:new Date().toISOString()}: {})};const{error}=await supabase.from("support_tickets").update(next).eq("id",selected.id);if(error)setError(error.message);else await load();setBusy(false)}
 async function openScreenshot(path:string){const{data,error}=await supabase.storage.from("support-ticket-screenshots").createSignedUrl(path,300);if(error)setError(error.message);else window.open(data.signedUrl,"_blank","noopener,noreferrer")}
 return <div className="supportLayout">
  {!isSuperAdmin&&<section className="card supportCreate"><div className="cardHead"><div><p className="eyebrow">Customer support</p><h2>Report an Issue</h2><p>Tell us what happened. RefAssign automatically includes the current page and device details.</p></div></div>{error&&<div className="errorBox">{error}</div>}{notice&&<div className="loginMessage">{notice}</div>}
   <form className="officialForm" onSubmit={submit}><label>Category<select name="category" defaultValue="technical">{categories.map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select></label><label>Urgency<select name="priority" defaultValue="normal"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent — work is blocked</option></select></label><label className="supportWide">Short summary<input name="subject" minLength={3} maxLength={160} required placeholder="What is not working?"/></label><label className="supportWide">What happened?<textarea name="description" minLength={10} maxLength={5000} required rows={5} placeholder="Include what you selected, what you expected, and what appeared instead."/></label><label className="supportWide">Error message (optional)<input name="last_error" placeholder="Paste the exact error text"/></label><label className="supportWide">Screenshot (optional)<input name="screenshot" type="file" accept="image/png,image/jpeg,image/webp"/></label><button className="primary" disabled={busy}>{busy?"Submitting…":"Submit Issue"}</button></form>
  </section>}
  <section className="card supportTickets"><div className="cardHead"><div><h2>{isSuperAdmin?"Support Queue":"My Tickets"}</h2><p>{isSuperAdmin?"Review and resolve customer issues.":"Track updates and reply to support."}</p></div>{isSuperAdmin&&<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Open tickets</option><option value="new">New</option><option value="reviewing">Reviewing</option><option value="waiting_on_customer">Waiting on customer</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option><option value="all">All</option></select>}</div>
   <div className="supportTicketList">{tickets.length===0?<p>No tickets found.</p>:tickets.map(t=><button key={t.id} className={selected?.id===t.id?"supportTicket active":"supportTicket"} onClick={()=>void loadMessages(t)}><span><b>{t.ticket_number}</b> {t.subject}</span><small>{statusLabels[t.status]||t.status} · {t.priority} · {new Date(t.updated_at).toLocaleString()}</small></button>)}</div>
  </section>
  {selected&&<section className="card supportDetail"><div className="cardHead"><div><p className="eyebrow">{selected.ticket_number}</p><h2>{selected.subject}</h2><p>{selected.category} · submitted {new Date(selected.created_at).toLocaleString()}</p></div><span className={`badge ${selected.status==="resolved"?"green":""}`}>{statusLabels[selected.status]}</span></div><p className="supportDescription">{selected.description}</p>{selected.last_error&&<div className="errorBox"><b>Reported error:</b> {selected.last_error}</div>}{selected.screenshot_path&&<button className="secondary" onClick={()=>void openScreenshot(selected.screenshot_path!)}>View Screenshot</button>}<details className="supportContext"><summary>Technical details</summary><p><b>Page:</b> {selected.page_url||"Not captured"}</p><p><b>Device:</b> {selected.device||"Not captured"}</p><p><b>Browser:</b> {selected.browser||"Not captured"}</p></details>
   {isSuperAdmin&&<div className="supportAdminControls"><label>Status<select value={selected.status} onChange={e=>void updateTicket({status:e.target.value})}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Priority<select value={selected.priority} onChange={e=>void updateTicket({priority:e.target.value})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label></div>}
   <div className="supportThread">{messages.map(m=><article key={m.id} className={m.internal_note?"supportMessage internal":"supportMessage"}><b>{m.internal_note?"Internal note":m.author_user_id===selected.requester_user_id?"Customer":"Support"}</b><p>{m.message}</p><small>{new Date(m.created_at).toLocaleString()}</small></article>)}</div><form className="supportReply" onSubmit={reply}><textarea name="message" required rows={3} placeholder={isSuperAdmin?"Reply to the customer or add an internal note":"Reply to support"}/>{isSuperAdmin&&<label><input type="checkbox" name="internal_note"/> Internal note (customer cannot see this)</label>}<button className="primary" disabled={busy}>Send Reply</button></form>
  </section>}
 </div>
}
