'use client'
import {ChangeEvent,useEffect,useMemo,useState} from 'react'
import {createClient} from '../lib/supabase/client'
type Team={id:string;name:string;sport_id:string|null;level_id:string|null;active:boolean};type Choice={id:string;name:string};type Row={row:number;id:string;name:string;sport:string;level:string;active:string;action:'Add'|'Update';valid:boolean;issue:string}
const REQUIRED=['name','sport','level','active']
function esc(v:string){return /[",\n]/.test(v)?`"${v.replace(/"/g,'""')}"`:v}
function parseCSV(text:string){const rows:string[][]=[];let row:string[]=[];let cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(v=>v.trim()))rows.push(row);row=[]}else cell+=ch}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows}
export default function TeamsRosterManager(){const supabase=useMemo(()=>createClient(),[]);const [allowed,setAllowed]=useState(false);const [teams,setTeams]=useState<Team[]>([]);const [sports,setSports]=useState<Choice[]>([]);const [levels,setLevels]=useState<Choice[]>([]);const [rows,setRows]=useState<Row[]>([]);const [error,setError]=useState('');const [message,setMessage]=useState('');const [importing,setImporting]=useState(false)
async function load(){setError('');const {data:u}=await supabase.auth.getUser();if(!u.user)return;const {data:p}=await supabase.from('profiles').select('role').eq('id',u.user.id).maybeSingle();const ok=['admin','assignor'].includes(p?.role||'');setAllowed(ok);if(!ok)return;const [t,s,l]=await Promise.all([supabase.from('teams').select('id,name,sport_id,level_id,active').order('name'),supabase.from('sports').select('id,name').eq('active',true).order('name'),supabase.from('levels').select('id,name').eq('active',true).order('name')]);const err=t.error||s.error||l.error;if(err){setError(err.message);return}setTeams((t.data||[]) as Team[]);setSports(s.data||[]);setLevels(l.data||[])}useEffect(()=>{load()},[])
function downloadCurrent(){const head=['id',...REQUIRED].join(',');const lines=teams.map(t=>[t.id,t.name,sports.find(s=>s.id===t.sport_id)?.name||'',levels.find(l=>l.id===t.level_id)?.name||'',t.active?'true':'false'].map(v=>esc(String(v))).join(','));const blob=new Blob([[head,...lines].join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='refassign-teams.csv';a.click();URL.revokeObjectURL(url)}
function validate(raw:string[][]):Row[]{if(!raw.length)throw new Error('Import file is empty.');const h=raw[0].map(x=>String(x).trim().toLowerCase().replace(/\s+/g,'_'));const missing=REQUIRED.filter(x=>!h.includes(x));if(missing.length)throw new Error(`Missing columns: ${missing.join(', ')}`);return raw.slice(1).map((r,i)=>{const get=(x:string)=>String(r[h.indexOf(x)]??'').trim();const id=get('id'),name=get('name'),sport=get('sport'),level=get('level'),active=get('active').toLowerCase();const issues:string[]=[];if(!name)issues.push('Missing team name');if(!sports.some(s=>s.name.toLowerCase()===sport.toLowerCase()))issues.push('Unknown sport');if(!levels.some(l=>l.name.toLowerCase()===level.toLowerCase()))issues.push('Unknown level');if(!['true','false','yes','no','1','0'].includes(active))issues.push('Active must be true/false');if(id&&!teams.some(t=>t.id===id))issues.push('ID not found in current teams');return{row:i+2,id,name,sport,level,active,action:id?'Update':'Add',valid:!issues.length,issue:issues.join('; ')}})}
async function handleFile(e:ChangeEvent<HTMLInputElement>){setRows([]);setMessage('');setError('');const f=e.target.files?.[0];if(!f)return;try{let raw:string[][];if(/\.xlsx?$/i.test(f.name)){const XLSX=await import('xlsx');const wb=XLSX.read(await f.arrayBuffer(),{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];raw=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false}) as string[][]}else raw=parseCSV(await f.text());setRows(validate(raw))}catch(err){setError(err instanceof Error?err.message:'Unable to read team CSV or Excel file')}finally{e.target.value=''}}
async function applyImport(){if(rows.some(r=>!r.valid)||!rows.length)return;setImporting(true);setError('');let added=0,updated=0;try{for(const r of rows){const sport=sports.find(s=>s.name.toLowerCase()===r.sport.toLowerCase())!,level=levels.find(l=>l.name.toLowerCase()===r.level.toLowerCase())!;const payload={name:r.name,sport_id:sport.id,level_id:level.id,level:level.name,active:['true','yes','1'].includes(r.active.toLowerCase())};if(r.id){const x=await supabase.from('teams').update(payload).eq('id',r.id);if(x.error)throw x.error;updated++}else{const x=await supabase.from('teams').insert(payload);if(x.error)throw x.error;added++}}setMessage(`Teams import complete: ${updated} updated, ${added} added.`);setRows([]);await load()}catch(err){setError(err instanceof Error?err.message:'Teams import failed')}finally{setImporting(false)}}
if(!allowed)return <section className="card"><h2>Teams Import / Export</h2><p>Only Administrators and Assignors can use the teams uploader.</p></section>;const invalid=rows.filter(r=>!r.valid).length;return <section className="card"><div className="cardHead"><div><h3>Teams Import / Export</h3><p>Download the current teams, update them in Excel or Sheets, add new rows, then upload the CSV or Excel workbook directly.</p></div><button className="secondary" onClick={downloadCurrent}>Download Current Teams</button></div><input type="file" accept=".csv,.xlsx,.xls,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" onChange={handleFile}/><p><small>Leave id blank for new teams. Existing teams are updated by their exported id.</small></p>{error&&<div className="errorBox">{error}</div>}{message&&<div className="loginMessage">{message}</div>}{rows.length>0&&<><p>{rows.length} rows • {rows.filter(r=>r.action==='Update').length} updates • {rows.filter(r=>r.action==='Add').length} additions • {invalid} errors</p><div className="tableWrap"><table><thead><tr><th>Row</th><th>Action</th><th>Team</th><th>Sport</th><th>Level</th><th>Active</th><th>Validation</th></tr></thead><tbody>{rows.map(r=><tr key={r.row}><td>{r.row}</td><td><span className={`badge ${r.action==='Add'?'blue':'amber'}`}>{r.action}</span></td><td><b>{r.name}</b></td><td>{r.sport}</td><td>{r.level}</td><td>{r.active}</td><td><span className={`badge ${r.valid?'green':'red'}`}>{r.valid?'Ready':r.issue}</span></td></tr>)}</tbody></table></div><button className="primary" disabled={importing||invalid>0} onClick={applyImport}>{importing?'Updating Teams…':'Apply Team Changes'}</button></>}</section>}
