"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {createClient} from "../lib/supabase/client";
type Quiz={id:string;title:string;description:string;passing_percent:number;allow_retakes:boolean;active:boolean;updated_at:string};
type QuestionDraft={question_text:string;options:string[];correct_option:number;explanation:string};
type Attempt={id:string;quiz_id:string|null;official_id:string;correct_count:number;total_questions:number;score_percent:number;passed:boolean;completed_at:string;answers:Record<string,number>};
type Official={id:string;first_name:string;last_name:string;email:string|null};
type SavedQuestion={id:string;quiz_id:string;question_text:string;options:string[];correct_option:number;sort_order:number};
const blankQuestion=():QuestionDraft=>({question_text:"",options:["","","",""],correct_option:0,explanation:""});
export default function TrainingQuizManager({programId,onChanged}:{programId:string;onChanged?:()=>void}){const supabase=useMemo(()=>createClient(),[]),[quizzes,setQuizzes]=useState<Quiz[]>([]),[attempts,setAttempts]=useState<Attempt[]>([]),[savedQuestions,setSavedQuestions]=useState<SavedQuestion[]>([]),[officials,setOfficials]=useState<Official[]>([]),[questions,setQuestions]=useState<QuestionDraft[]>([blankQuestion()]),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[passing,setPassing]=useState(80),[retakes,setRetakes]=useState(true),[activeView,setActiveView]=useState<"repository"|"create"|"answers">("repository"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){if(!programId)return;const[q,a,o]=await Promise.all([supabase.from("training_quizzes").select("id,title,description,passing_percent,allow_retakes,active,updated_at").eq("program_id",programId).order("updated_at",{ascending:false}),supabase.from("development_quiz_attempts").select("id,quiz_id,official_id,correct_count,total_questions,score_percent,passed,completed_at,answers").not("quiz_id","is",null).order("completed_at",{ascending:false}).limit(250),supabase.rpc("list_development_program_officials",{p_program_id:programId})]);const e=q.error||a.error||o.error;if(e)return setError(e.message);const quizRows=(q.data||[]) as Quiz[];setQuizzes(quizRows);setAttempts((a.data||[]) as Attempt[]);setOfficials((o.data||[]) as Official[]);if(quizRows.length){const sq=await supabase.from("training_quiz_questions").select("id,quiz_id,question_text,options,correct_option,sort_order").in("quiz_id",quizRows.map(x=>x.id)).order("sort_order");if(sq.error)setError(sq.error.message);else setSavedQuestions((sq.data||[]) as SavedQuestion[])}else setSavedQuestions([])}
 useEffect(()=>{void load()},[programId]);
 function updateQuestion(index:number,patch:Partial<QuestionDraft>){setQuestions(old=>old.map((q,i)=>i===index?{...q,...patch}:q))}
 async function createQuiz(event:FormEvent){event.preventDefault();setError("");setNotice("");const clean=questions.map(q=>({...q,options:q.options.map(x=>x.trim()).filter(Boolean)}));if(clean.some(q=>!q.question_text.trim()||q.options.length<2||q.correct_option>=q.options.length))return setError("Each question needs text, at least two answer choices, and one correct answer.");setBusy(true);try{const response=await fetch("/api/training/quizzes",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({programId,title,description,passingPercent:passing,allowRetakes:retakes,questions:clean})}),result=await response.json().catch(()=>({})) as{error?:string};if(!response.ok)throw new Error(result.error||"Quiz could not be saved.");setNotice("Quiz saved to the repository. It is now available in each training card’s Attach Quiz list.");setTitle("");setDescription("");setPassing(80);setRetakes(true);setQuestions([blankQuestion()]);setActiveView("repository");await load();onChanged?.()}catch(reason){setError(reason instanceof Error?reason.message:"Quiz could not be saved. Please try again.");document.querySelector(".quizManager")?.scrollIntoView({behavior:"smooth",block:"start"})}finally{setBusy(false)}}
 async function toggleQuiz(quiz:Quiz){const{error:e}=await supabase.from("training_quizzes").update({active:!quiz.active,updated_at:new Date().toISOString()}).eq("id",quiz.id);if(e)setError(e.message);else{await load();onChanged?.()}}
 const officialName=(id:string)=>{const o=officials.find(x=>x.id===id);return o?`${o.first_name} ${o.last_name}`:"Unknown official"},quizName=(id:string|null)=>quizzes.find(q=>q.id===id)?.title||"Archived quiz";
 return <section className="card quizManager"><div className="trainingSectionHead"><div><h2>Quiz Center</h2><p>Create reusable quizzes, attach them to video cards above, and review user answers.</p></div></div><div className="quizManagerTabs"><button className={activeView==="repository"?"primary":"secondary"} onClick={()=>setActiveView("repository")}>Saved Quizzes ({quizzes.length})</button><button className={activeView==="create"?"primary":"secondary"} onClick={()=>setActiveView("create")}>+ Create Quiz</button><button className={activeView==="answers"?"primary":"secondary"} onClick={()=>setActiveView("answers")}>Answer Log ({attempts.length})</button></div>{error&&<div className="errorBox">{error}</div>}{notice&&<div className="loginMessage">{notice}</div>}
 {activeView==="repository"&&<div className="quizRepository">{quizzes.length?quizzes.map(q=><article key={q.id}><div><b>{q.title}</b><p>{q.description||"No description"}</p><small>{q.passing_percent}% to pass • {q.allow_retakes?"Retakes allowed":"One attempt"} • {attempts.filter(a=>a.quiz_id===q.id).length} attempts</small></div><button className="secondary" onClick={()=>void toggleQuiz(q)}>{q.active?"Archive":"Restore"}</button></article>):<p>No saved quizzes yet. Select <b>Create Quiz</b> to build the first one.</p>}</div>}
 {activeView==="create"&&<form onSubmit={createQuiz} className="quizBuilder"><div className="officialForm"><label>Quiz Title<input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Video Review Quiz"/></label><label>Passing Score<input type="number" min="1" max="100" value={passing} onChange={e=>setPassing(Number(e.target.value))} required/></label><label className="fullSpan">Instructions / Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Answer the questions after watching the video."/></label><label><input type="checkbox" checked={retakes} onChange={e=>setRetakes(e.target.checked)}/> Allow users to retake this quiz</label></div><div className="quizBuilderQuestions">{questions.map((q,index)=><fieldset key={index}><legend>Question {index+1}</legend><label>Question<input value={q.question_text} onChange={e=>updateQuestion(index,{question_text:e.target.value})} required/></label><div className="quizChoiceEditor">{q.options.map((option,choice)=><label key={choice}><input type="radio" name={`correct-${index}`} checked={q.correct_option===choice} onChange={()=>updateQuestion(index,{correct_option:choice})} aria-label={`Mark answer ${choice+1} correct`}/><span>{String.fromCharCode(65+choice)}</span><input value={option} onChange={e=>{const options=[...q.options];options[choice]=e.target.value;updateQuestion(index,{options})}} placeholder={`Answer choice ${choice+1}`} required={choice<2}/></label>)}</div><label>Explanation shown after submission<input value={q.explanation} onChange={e=>updateQuestion(index,{explanation:e.target.value})} placeholder="Optional explanation"/></label>{questions.length>1&&<button type="button" className="dangerButton" onClick={()=>setQuestions(old=>old.filter((_,i)=>i!==index))}>Remove Question</button>}</fieldset>)}</div><div className="quizBuilderActions"><button type="button" className="secondary" onClick={()=>setQuestions(old=>[...old,blankQuestion()])}>+ Add Question</button><button className="primary" disabled={busy}>{busy?"Saving…":"Save Quiz to Repository"}</button></div></form>}
 {activeView==="answers"&&<div className="tableScroll"><table className="trainingCompleted"><thead><tr><th>User</th><th>Quiz</th><th>Submitted</th><th>Score</th><th>Result</th><th>Recorded Answers</th></tr></thead><tbody>{attempts.map(a=><tr key={a.id}><td>{officialName(a.official_id)}</td><td>{quizName(a.quiz_id)}</td><td>{new Date(a.completed_at).toLocaleString()}</td><td>{a.correct_count}/{a.total_questions} ({a.score_percent}%)</td><td><span className={`badge ${a.passed?"green":"yellow"}`}>{a.passed?"Passed":"Not passed"}</span></td><td><details><summary>View answers</summary><ol className="quizAnswerLog">{savedQuestions.filter(q=>q.quiz_id===a.quiz_id).map(q=>{const selected=a.answers[q.id],correct=selected===q.correct_option;return <li key={q.id}><b>{q.question_text}</b><span className={correct?"answerCorrect":"answerIncorrect"}>User: {q.options[selected]||"No answer"} {correct?"✓":"✕"}</span>{!correct&&<small>Correct: {q.options[q.correct_option]}</small>}</li>})}</ol></details></td></tr>)}</tbody></table>{!attempts.length&&<p>No quiz responses have been submitted yet.</p>}</div>}</section>}
