"use client";
import {useEffect,useState} from "react";
type Question={id:string;question:string;options:string[]};type Quiz={id:string;title:string;description:string;passingPercent:number;allowRetakes:boolean;questions:Question[]};
type Score={correctCount:number;totalQuestions:number;scorePercent:number;passed:boolean;passPercent:number;results:Array<{id:string;selected:number;correct:number;isCorrect:boolean;explanation:string}>};
export default function TrainingCardQuiz({moduleId,onClose,onPassed}:{moduleId:string;onClose:()=>void;onPassed:(date:string)=>void}){const[quiz,setQuiz]=useState<Quiz|null>(null),[answers,setAnswers]=useState<Record<string,number>>({}),[step,setStep]=useState(0),[score,setScore]=useState<Score|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{void(async()=>{const response=await fetch(`/api/training/quiz?moduleId=${encodeURIComponent(moduleId)}`,{cache:"no-store"}),data=await response.json().catch(()=>({}));if(!response.ok)setError(data.error||"The quiz could not be loaded.");else setQuiz(data.quiz)})()},[moduleId]);
 async function submit(){if(!quiz||Object.keys(answers).length!==quiz.questions.length)return setError("Please answer every question before submitting.");setBusy(true);setError("");const response=await fetch("/api/training/quiz",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({moduleId,answers})}),data=await response.json().catch(()=>({}));if(!response.ok)setError(data.error||"The quiz could not be scored.");else{setScore(data);if(data.passed)onPassed(new Date().toISOString());window.scrollTo({top:0,behavior:"smooth"})}setBusy(false)}
 if(error&&!quiz)return <section className="rulesQuiz"><div className="errorBox">{error}</div><button className="secondary" onClick={onClose}>Return to Training</button></section>;
 if(!quiz)return <section className="rulesQuiz"><p>Loading quiz…</p></section>;
 if(score)return <section className="rulesQuiz"><div className={`quizScore ${score.passed?"passed":"retry"}`}><span>{score.passed?"✓":"↻"}</span><div><h2>{score.passed?"You Passed!":"Keep Learning — Try Again"}</h2><p><b>{score.correctCount} of {score.totalQuestions} correct · {score.scorePercent}%</b></p><p>{score.passed?"This training card is now complete.":`${score.passPercent}% is required to pass.`}</p></div></div><div className="quizReview"><h3>Answer Review</h3>{quiz.questions.map((q,i)=>{const r=score.results.find(x=>x.id===q.id);return <article className={r?.isCorrect?"correct":"incorrect"} key={q.id}><div className="quizReviewTitle"><b>{i+1}. {q.question}</b><span>{r?.isCorrect?"✓ Correct":"✕ Review"}</span></div><p>Your answer: {q.options[r?.selected??0]}</p>{!r?.isCorrect&&<p><b>Correct answer: {q.options[r?.correct??0]}</b></p>}{r?.explanation&&<small>{r.explanation}</small>}</article>})}</div><div className="quizFooter"><button className="secondary" onClick={onClose}>Return to Training</button>{quiz.allowRetakes&&<button className="primary" onClick={()=>{setScore(null);setAnswers({});setStep(0)}}>Take Quiz Again</button>}</div></section>;
 const question=quiz.questions[step],answered=Object.keys(answers).length;
 return <section className="rulesQuiz"><div className="quizHeader"><div><span className="quizEyebrow">VIDEO FOLLOW-UP QUIZ</span><h2>{quiz.title}</h2><p>{quiz.description||`Answer each question. A score of ${quiz.passingPercent}% is required to pass.`}</p></div><button className="quizClose" aria-label="Close quiz" onClick={onClose}>×</button></div><div className="quizProgress"><div><i style={{width:`${answered/quiz.questions.length*100}%`}}/></div><span>{answered} of {quiz.questions.length} answered</span></div><article className="quizQuestion"><span>Question {step+1} of {quiz.questions.length}</span><h3>{question.question}</h3><div className="quizOptions">{question.options.map((option,index)=><label className={answers[question.id]===index?"selected":""} key={index}><input type="radio" name={question.id} checked={answers[question.id]===index} onChange={()=>setAnswers(old=>({...old,[question.id]:index}))}/><b>{String.fromCharCode(65+index)}</b><span>{option}</span></label>)}</div></article>{error&&<div className="errorBox">{error}</div>}<div className="quizFooter"><button className="secondary" disabled={!step} onClick={()=>setStep(s=>s-1)}>Previous</button><span>{quiz.questions.map((q,index)=><button aria-label={`Question ${index+1}`} className={`${index===step?"current":""} ${answers[q.id]!==undefined?"answered":""}`} key={q.id} onClick={()=>setStep(index)}>{index+1}</button>)}</span>{step<quiz.questions.length-1?<button className="primary" onClick={()=>setStep(s=>s+1)}>Next</button>:<button className="primary" disabled={answered!==quiz.questions.length||busy} onClick={()=>void submit()}>{busy?"Scoring…":"Submit Quiz"}</button>}</div></section>}
