export type IowaRulesQuizOption={value:string;label:string};
export type IowaRulesQuizQuestion={id:string;question:string;hint:string;options:IowaRulesQuizOption[]};

export const IOWA_ENTRY_RULES_QUIZ_KEY="iowa-entry-rules-2026";
export const IOWA_ENTRY_RULES_PASS_PERCENT=80;

export const iowaEntryRulesQuestions:IowaRulesQuizQuestion[]=[
 {id:"q1",question:"What is the maximum number of players one team may have on the field at one time?",hint:"Count the goalkeeper as one of the players.",options:[{value:"A",label:"9"},{value:"B",label:"10"},{value:"C",label:"11"},{value:"D",label:"12"}]},
 {id:"q2",question:"What is the minimum number of players a team must have for a match to start or continue?",hint:"A full team may be reduced by four players.",options:[{value:"A",label:"6"},{value:"B",label:"7"},{value:"C",label:"8"},{value:"D",label:"9"}]},
 {id:"q3",question:"In a standard adult match, how long is each half?",hint:"A standard match is 90 minutes before added time.",options:[{value:"A",label:"30 minutes"},{value:"B",label:"35 minutes"},{value:"C",label:"40 minutes"},{value:"D",label:"45 minutes"}]},
 {id:"q4",question:"When is the ball out of play at a boundary line?",hint:"The position of the whole ball matters.",options:[{value:"A",label:"When any part of it touches the line"},{value:"B",label:"When most of it crosses the line"},{value:"C",label:"When it wholly crosses the line on the ground or in the air"},{value:"D",label:"When a player stops playing"}]},
 {id:"q5",question:"When is a goal scored?",hint:"The entire ball must pass the goal line in the legal goal area.",options:[{value:"A",label:"When most of the ball crosses the goal line"},{value:"B",label:"When the whole ball crosses between the posts and under the crossbar, with no attacking offence"},{value:"C",label:"When the goalkeeper touches the ball behind the line"},{value:"D",label:"Whenever the referee blows the whistle near the goal"}]},
 {id:"q6",question:"Who receives a throw-in when the ball last touches a Blue player before crossing the touchline?",hint:"The restart goes to the opponents of the player who touched it last.",options:[{value:"A",label:"Blue team"},{value:"B",label:"The team that is losing"},{value:"C",label:"The referee chooses"},{value:"D",label:"The opposing team"}]},
 {id:"q7",question:"Which describes a legal throw-in?",hint:"Think about the hands, head and feet.",options:[{value:"A",label:"One hand throws while both feet are in the field"},{value:"B",label:"Both hands deliver the ball from behind and over the head, with part of each foot on the line or on the ground outside it"},{value:"C",label:"Both hands throw from the chest with one foot raised"},{value:"D",label:"The ball is rolled onto the field"}]},
 {id:"q8",question:"How far must an opponent stand from the place where a throw-in is taken?",hint:"The required distance is a little over six feet.",options:[{value:"A",label:"At least 1 yard (1 m)"},{value:"B",label:"At least 2 yards (2 m)"},{value:"C",label:"At least 5 yards (4.5 m)"},{value:"D",label:"At least 10 yards (9.15 m)"}]},
 {id:"q9",question:"The attacking team last touches the ball before it crosses the defending team's goal line without a goal. What is the restart?",hint:"This restart is taken by the defending team.",options:[{value:"A",label:"Corner kick"},{value:"B",label:"Throw-in"},{value:"C",label:"Goal kick"},{value:"D",label:"Dropped ball"}]},
 {id:"q10",question:"The defending team last touches the ball before it crosses its own goal line without a goal. What is the restart?",hint:"This restart is taken from the nearest corner area.",options:[{value:"A",label:"Corner kick"},{value:"B",label:"Goal kick"},{value:"C",label:"Kick-off"},{value:"D",label:"Indirect free kick"}]},
 {id:"q11",question:"Is a player penalized simply for standing in an offside position?",hint:"Position and offence are not the same thing.",options:[{value:"A",label:"Yes, always"},{value:"B",label:"Yes, if the assistant referee sees the player"},{value:"C",label:"No, being in an offside position alone is not an offence"},{value:"D",label:"No, but only during the first half"}]},
 {id:"q12",question:"A player receives the ball directly from a goal kick while in an offside position. What is the decision?",hint:"Some restarts are exceptions to offside.",options:[{value:"A",label:"Penalize offside"},{value:"B",label:"Allow play to continue"},{value:"C",label:"Retake the goal kick"},{value:"D",label:"Award a corner kick"}]},
 {id:"q13",question:"Can a goal be scored directly against the opponents from a direct free kick?",hint:"The name of the restart gives a clue.",options:[{value:"A",label:"Yes"},{value:"B",label:"No, another player must touch it"},{value:"C",label:"Only in the second half"},{value:"D",label:"Only if the goalkeeper agrees"}]},
 {id:"q14",question:"How does the referee signal an indirect free kick?",hint:"The signal stays visible until the kick's outcome is known.",options:[{value:"A",label:"Both arms point toward the goal"},{value:"B",label:"One arm is raised above the head"},{value:"C",label:"Both hands are placed on the hips"},{value:"D",label:"The referee shows a yellow card"}]},
 {id:"q15",question:"How far is the penalty mark from the goal line?",hint:"This is the traditional distance used for a penalty kick.",options:[{value:"A",label:"10 yards"},{value:"B",label:"11 yards"},{value:"C",label:"12 yards"},{value:"D",label:"15 yards"}]},
 {id:"q16",question:"At the moment a penalty kick is taken, where must the defending goalkeeper have at least part of one foot?",hint:"The goalkeeper may move sideways but cannot be entirely in front of the line.",options:[{value:"A",label:"Touching, in line with, or behind the goal line"},{value:"B",label:"On the penalty mark"},{value:"C",label:"Outside the goal area"},{value:"D",label:"At least one yard in front of the goal line"}]},
 {id:"q17",question:"A player makes a careless challenge. What disciplinary card is normally required?",hint:"Careless is the lowest of the three foul-severity levels.",options:[{value:"A",label:"No card"},{value:"B",label:"Yellow card"},{value:"C",label:"Red card"},{value:"D",label:"Both yellow and red cards"}]},
 {id:"q18",question:"A player makes a reckless challenge. What disciplinary action is required?",hint:"Reckless means the player disregarded the danger to an opponent.",options:[{value:"A",label:"No card"},{value:"B",label:"A verbal warning only"},{value:"C",label:"Yellow card"},{value:"D",label:"Red card"}]},
 {id:"q19",question:"A player uses excessive force in a challenge and endangers an opponent's safety. What disciplinary action is required?",hint:"This is the most serious challenge category.",options:[{value:"A",label:"No card"},{value:"B",label:"Yellow card"},{value:"C",label:"Blue card"},{value:"D",label:"Red card"}]},
 {id:"q20",question:"What does a yellow card communicate?",hint:"It records a formal warning, not removal from the match.",options:[{value:"A",label:"The player has been cautioned"},{value:"B",label:"The player has been sent off"},{value:"C",label:"The team has scored"},{value:"D",label:"A substitution is required"}]},
 {id:"q21",question:"What does a red card communicate?",hint:"The person may no longer participate in the match.",options:[{value:"A",label:"The player receives a warning"},{value:"B",label:"The player must change equipment"},{value:"C",label:"The player has been sent off"},{value:"D",label:"The team receives a free kick"}]},
 {id:"q22",question:"May a player cover an earring with tape and play?",hint:"The Laws require jewellery to be removed.",options:[{value:"A",label:"Yes, if the tape matches the uniform"},{value:"B",label:"Yes, with the coach's permission"},{value:"C",label:"Yes, if the earring is small"},{value:"D",label:"No, jewellery must be removed and cannot simply be taped over"}]},
 {id:"q23",question:"How must a player's shinguards be worn?",hint:"One required uniform item must cover them.",options:[{value:"A",label:"Over the socks"},{value:"B",label:"Covered by the socks"},{value:"C",label:"Only on the kicking leg"},{value:"D",label:"Attached to the shoes"}]},
 {id:"q24",question:"When is the ball in play at a kick-off?",hint:"The ball no longer has to travel forward.",options:[{value:"A",label:"When the referee enters the center circle"},{value:"B",label:"When every player touches the ball"},{value:"C",label:"When it is kicked and clearly moves"},{value:"D",label:"When it leaves the center circle"}]},
 {id:"q25",question:"A teammate deliberately kicks the ball to their goalkeeper, who handles it inside the penalty area. What is the restart?",hint:"This restriction produces a free kick that cannot score directly.",options:[{value:"A",label:"Penalty kick"},{value:"B",label:"Direct free kick"},{value:"C",label:"Indirect free kick"},{value:"D",label:"Dropped ball"}]}
];
