import { NextRequest, NextResponse } from "next/server";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { createServiceClient } from "../../../../lib/supabase/admin";
import { buildCustomReport, dimensionLabels, metricLabels, normalizeReportFacts, type CustomReportDefinition, type ReportMetric } from "../../../../lib/customReportBuilder";

export const maxDuration = 60;
const esc = (value: unknown) => String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]!);
const money = new Set<ReportMetric>(["gameFees", "mileagePay", "totalCost", "averageFee"]), decimal = new Set<ReportMetric>(["miles", "averageMiles"]);
const format = (metric: ReportMetric, value: number) => money.has(metric) ? value.toLocaleString("en-US", { style: "currency", currency: "USD" }) : metric === "coverageRate" ? `${value.toFixed(1)}%` : decimal.has(metric) ? value.toFixed(1) : Math.round(value).toLocaleString();
const advance = (frequency: string, day: number) => { const next = new Date(); next.setUTCHours(13, 0, 0, 0); if (frequency === "monthly") { next.setUTCDate(Math.min(28, day)); if (next <= new Date()) next.setUTCMonth(next.getUTCMonth() + 1); } else { const distance = (day - next.getUTCDay() + 7) % 7 || 7; next.setUTCDate(next.getUTCDate() + distance); } return next.toISOString(); };

export async function GET(request: NextRequest) {
  if (!process.env.CRON_SECRET || request.headers.get("authorization") !== `Bearer ${process.env.CRON_SECRET}`) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  if (!process.env.RESEND_API_KEY) return NextResponse.json({ error: "RESEND_API_KEY is not configured." }, { status: 500 });
  const service = createServiceClient(), now = new Date().toISOString(), { data: schedules, error } = await service.from("custom_report_templates").select("id,organization_id,user_id,name,definition,recipient_email,frequency,send_day").eq("schedule_enabled", true).lte("next_send_at", now).limit(15);
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  let sent = 0; const failures: string[] = [];
  for (const schedule of schedules || []) {
    try {
      const definition = schedule.definition as CustomReportDefinition, selectedIds = Array.isArray(definition.organizationIds) ? definition.organizationIds : [], { data: memberships } = await service.from("organization_memberships").select("organization_id,role").eq("user_id", schedule.user_id), managedIds = [...new Set((memberships || []).filter((item) => ["owner", "admin", "assignor"].includes(item.role)).map((item) => item.organization_id))], { data: subscriptions } = managedIds.length ? await service.from("refassign_subscriptions").select("organization_id,reporting_access,created_at").in("organization_id", managedIds).in("status", ["active", "trialing", "pending"]).order("created_at", { ascending: false }) : { data: [] }, latest = new Map<string, string>();
      (subscriptions || []).forEach((item) => { if (item.organization_id && !latest.has(item.organization_id)) latest.set(item.organization_id, item.reporting_access); });
      const premiumIds = managedIds.filter((id) => latest.get(id) !== "standard"), requestedIds = selectedIds.length ? selectedIds : premiumIds, allowedIds = requestedIds.filter((id) => premiumIds.includes(id));
      if (!allowedIds.includes(schedule.organization_id) || allowedIds.length !== requestedIds.length) { await service.from("custom_report_templates").update({ schedule_enabled: false, next_send_at: null, updated_at: now }).eq("id", schedule.id); throw new Error(`${schedule.name}: schedule disabled because organization access or Premium Reporting changed`); }
      const [{ data: organizations }, { data: games, error: gamesError }] = await Promise.all([service.from("organizations").select("id,name").in("id", allowedIds), service.from("games").select("id,organization_id,game_number,status,starts_at,officials_needed,leagues(id,name),levels(id,name),location:locations(id,name),home:teams!games_home_team_id_fkey(id,name),away:teams!games_away_team_id_fkey(id,name)").in("organization_id", allowedIds).order("starts_at", { ascending: false })]);
      if (gamesError) throw gamesError;
      const gameIds = (games || []).map((game) => game.id), { data: assignments, error: assignmentError } = gameIds.length ? await service.from("assignments").select("id,game_id,official_id,status,game_fee,mileage_miles,mileage_rate,payment_status,officials(id,first_name,last_name),sport_positions(id,name)").in("game_id", gameIds) : { data: [], error: null };
      if (assignmentError) throw assignmentError;
      const rows = buildCustomReport(normalizeReportFacts(games || [], assignments || [], organizations || []), { ...definition, organizationIds: allowedIds }), metrics = definition.metrics || [], groups = definition.groupBy || [];
      const pdf = new jsPDF({ orientation: "landscape" }); pdf.setTextColor(12, 30, 55); pdf.setFontSize(18); pdf.text(definition.title || schedule.name, 14, 17); pdf.setFontSize(9); pdf.text(`${(organizations || []).map((item) => item.name).join(" • ")} • Generated ${new Date().toLocaleString("en-US", { timeZone: "America/Chicago" })}`, 14, 25); autoTable(pdf, { startY: 32, head: [[...groups.map((item) => dimensionLabels[item]), ...metrics.map((item) => metricLabels[item])]], body: rows.map((row) => [...row.dimensions, ...metrics.map((metric) => format(metric, row.values[metric]))]), styles: { fontSize: 7 }, headStyles: { fillColor: [37, 99, 235] } });
      const summaryRows = rows.slice(0, 8).map((row) => `<tr><td style="padding:8px;border-bottom:1px solid #e2e8f0">${esc(row.dimensions.join(" / ") || "All records")}</td>${metrics.slice(0, 4).map((metric) => `<td style="padding:8px;border-bottom:1px solid #e2e8f0"><b>${esc(format(metric, row.values[metric]))}</b><br><small>${esc(metricLabels[metric])}</small></td>`).join("")}</tr>`).join("");
      const html = `<div style="font-family:Arial,sans-serif;background:#f5f7fb;padding:28px"><div style="max-width:760px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:14px;overflow:hidden"><div style="background:#14233b;color:#fff;padding:24px 28px"><div style="font-size:22px;font-weight:800">REF<span style="color:#60a5fa">ASSIGN</span></div><h2 style="margin:12px 0 0">${esc(definition.title || schedule.name)}</h2><p style="color:#cbd5e1">${esc((organizations || []).map((item) => item.name).join(" • "))}</p></div><div style="padding:28px"><p>${rows.length} grouped result${rows.length === 1 ? "" : "s"}. The complete organization-branded report is attached as a PDF.</p><table style="width:100%;border-collapse:collapse">${summaryRows}</table><p style="margin-top:24px"><a href="${request.nextUrl.origin}/workspace?section=reports" style="background:#2563eb;color:#fff;text-decoration:none;padding:11px 17px;border-radius:8px;font-weight:700">Open Custom Report Builder</a></p></div></div></div>`;
      const response = await fetch("https://api.resend.com/emails", { method: "POST", headers: { Authorization: `Bearer ${process.env.RESEND_API_KEY}`, "Content-Type": "application/json", "Idempotency-Key": `custom-report-${schedule.id}-${now.slice(0, 10)}` }, body: JSON.stringify({ from: "RefAssign <notifications@assignments.ref-assign.com>", to: [schedule.recipient_email], reply_to: "assignments@ref-assign.com", subject: `${definition.title || schedule.name} — RefAssign`, html, attachments: [{ filename: `${schedule.name.toLowerCase().replace(/[^a-z0-9]+/g, "-") || "custom-report"}.pdf`, content: Buffer.from(pdf.output("arraybuffer")).toString("base64") }] }) });
      if (!response.ok) { const detail = await response.json().catch(() => ({})) as { message?: string }; throw new Error(detail.message || `Email failed (${response.status})`); }
      await service.from("custom_report_templates").update({ last_sent_at: now, next_send_at: advance(schedule.frequency, schedule.send_day), updated_at: now }).eq("id", schedule.id); sent++;
    } catch (reason) { failures.push(reason instanceof Error ? reason.message : "Custom report delivery failed"); }
  }
  return NextResponse.json({ checked: (schedules || []).length, sent, failed: failures.length, failures });
}
